---
title: Supplementary Materials
output:
  bookdown::html_document2:
    number_sections: false
    toc: no
    toc_float: no
  bookdown::word_document2: default
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
linestretch: 1.5
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

\makeatletter
\renewcommand*{\thetable}{\arabic{table}}
\renewcommand*{\thefigure}{\arabic{figure}}
\let\c@table\c@figure
\makeatother 

\renewcommand{\figurename}{Supplementary Material S.}
\renewcommand{\tablename}{Supplementary Material S.}

```{r config, message=FALSE, warning=FALSE, include=FALSE}
rm(list = ls()); invisible(gc())
library(knitr)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(raster)
library(tidyverse)
library(ggfortify)
library(broom)
library(rstan)
library(bayesplot)
theme_set(bayesplot::theme_default())
opts_chunk$set(echo = F, message = F, warning = F, 
               fig.height = 6, fig.width = 6,
               cache = T, cache.lazy = F)
path <- "~/Documents/BIOGECO/PhD/data/Paracou/"
```

```{r data}
load("../functional_save/Individuals.Rdata")
Individuals0 <- Individuals
load("../functional_save/CompetitionMatrix.Rdata")
sdDBH <- sd(Individuals$DBH)
Individuals <- Individuals %>% 
  rename(LMA = invSLA) %>% 
  group_by(Species) %>% 
  filter(n() > 20) %>% 
  ungroup() %>% 
  left_join(Competition %>% 
              group_by(idTree) %>% 
              summarise(NCI = (1/mean(1-AreaOutside20))*sum(DBHj^2*exp(-0.25*dij)))) %>%
  mutate(NCI = log(NCI)) %>% 
  mutate_at(vars("LMA", "LDMC", "LT", "invLA", "CC", "DBH", "TWI", "NCI"),
            funs(./sd(., na.rm = T)))
```

```{r model}
load("../functional_save/InterIntraTWI.Rdata")
traits <- c("LMA", "LDMC", "LT", "invLA", "CC")
complexes <- c("Symphonia", "Eschweilera")
models <- sapply(complexes, function(complex) paste0(complex, "-", traits))
species <- lapply(models, function(model){
  trait <- strsplit(model, "-")[[1]][2]
  complex <- strsplit(model, "-")[[1]][1]
  Individuals[!is.na(unlist(Individuals[,trait])),] %>% 
    filter(Genus == complex) %>% 
    mutate(species = as.numeric(as.factor(Species))) %>% 
    mutate(SpeciesLong = paste(substr(complex, 1, 1), Species)) %>% 
   dplyr:: select(Genus, Species, SpeciesLong, species) %>% 
    unique()
}) %>% bind_rows() %>% 
  unique() %>% 
  mutate(complex = Genus)
plots <- lapply(models, function(model){
  trait <- strsplit(model, "-")[[1]][2]
  complex <- strsplit(model, "-")[[1]][1]
  Individuals[!is.na(unlist(Individuals[,trait])),] %>% 
    filter(Genus == complex) %>% 
    mutate(PlotNum = as.numeric(as.factor(Plot))) %>% 
   dplyr:: select(Genus, Plot, PlotNum) %>% 
    unique()
}) %>% bind_rows() %>% 
  unique() %>% 
  mutate(complex = Genus)
S_sqrt_trans <- function() scales::trans_new("S_sqrt",
                                             function(x) sign(x)*sqrt(abs(x)),
                                             function(x) x^2*sign(x))
fits0 <- fits
```

<!-- SUPPLEMENTARY MATERIALS -->

```{r abiotic, fig.cap='Principal Component Analysis (PCA) of abiotic topographic variables. All variables, slope, curvature, aspect, topgraphic rudgeness index (TRI), and topgraphic wetness index (TWI) are derived from the digital evlevation model (DEM) obtaine through LiDAR campaign in 2015.', fig.width=12, fig.height=12}
factoextra::fviz_pca_var(princomp(~ DEM + RelativeElevation + Slope + Curvature +
                          Aspect + TRI + TWI, Individuals, cor = T),
               axes = c(1, 2), geom = c("arrow", "text"), col.var = "contrib")
```

```{r dawkins, fig.cap='Diameter at breast height (DBH) and Dawkins index correlation. Box colors indicates the Dawkins index. DBH and Dawkins index correlation has been investigated by Anova. **** indicates a $p-value < 0.0001$. Letters indicate post-hoc groups investigated by Tukey Honest Significant Differences.'}
tHSD <- multcompView::multcompLetters((mutate(Individuals, Dawkins = substr(Dawkins, 1, 1)) %>% 
                                 aov(DBH ~ Dawkins, .) %>% 
                                 TukeyHSD(., ordered = F, conf.level = 0.95) %>% 
                                 .$Dawkins)[,4])$Letters %>% 
  data.frame(Dawkins = names(.), group = .)
Individuals %>% 
  dplyr::select(Dawkins, DBH) %>% 
  drop_na(Dawkins) %>% 
  mutate(Dawkins = substr(Dawkins, 1, 1)) %>% 
  left_join(tHSD) %>% 
  group_by(Dawkins) %>% 
  mutate(ymax = max(DBH)) %>% 
  ggplot(aes(Dawkins, DBH*sdDBH, fill = Dawkins, label = group)) + 
  geom_boxplot() + 
  geom_text(aes(y = (ymax+1)*sdDBH)) +
  ggpubr::stat_compare_means(method = "anova", aes(label = paste0("Anova", ..p.signif..))) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  ylab("Diameter at breast hiaght (dbh, cm)")
```

```{r DBH, fig.cap='Diameter at breast height (DBH) distribution between sampled indivduals and other *Symphonia* and *Eschweilera* individuals of Paracou.'}
src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>%
  filter(Genus %in% c("Lecythis", "Eschweilera") & 
           Plot %in% c(1, 6, 11, 13:15) & CensusYear == 2017 |
           Genus %in% c("Lecythis", "Eschweilera") & 
           Plot == 16 & CensusYear == 2015 |
           Genus == "Symphonia" & CensusYear == 2015) %>%
  mutate(DBH = CircCorr/pi) %>% 
  collect() %>% 
  mutate(Sample = as.numeric(idTree %in% Individuals$idTree)) %>% 
  mutate(Sample = recode_factor(Sample, 
                              `0` = "Other Symphonia and Eschweilera",
                              `1` = "Sampled individuals")) %>% 
  ggplot(aes(DBH)) +
  geom_histogram(position = "dodge") +
  facet_wrap(~ Sample, scale = "free", nrow = 2) +
  xlab("Diameter at breast height (dbh, cm)")
```


```{r ontogenyModel}
load("../functional_save/DBH.Rdata")
models <- list(michaelis = fits)
load("../functional_save/DBHlin.Rdata")
models$linear <- fits
lapply(models, function(model)
  lapply(model, function(trait)
    broom::tidyMCMC(trait, pars = "lp__", droppars = NULL, rhat = T)
  ) %>% bind_rows(.id = "Model")) %>% 
  bind_rows(.id = "Form") %>% 
  separate(Model, c("Genus", "Trait"), "-") %>% 
  mutate(Trait = recode_factor(Trait, 
                               LMA = "$LMA$",
                               LDMC = "$LDMC$", 
                               LT = "$LT$", 
                               invLA = "$\\frac{1}{LA}$",
                               CC = "$CC$")) %>% 
  mutate(Form = recode_factor(Form, 
                              linear = "Linear",
                              michaelis = "Michaelis Menten")) %>% 
  reshape2::dcast(Genus + Trait ~ Form, value.var = "estimate") %>% 
  mutate(Difference = Linear - `Michaelis Menten`) %>% 
  kable(caption = "Log-likelihood for diameter model depending on model form (linear vs Michaelis-Menten).", digits = 3, format = "pandoc", escape = F) %>% 
  kable_styling(full_width = F)
```

```{r DBH90, fig.cap="Effect of tree diameter on leaf functional trait variation. The posterior distribution of species diameter at breast height for which a given trait reaches 90% of its maximum value ($DBH_{90}$) was estimated for every trait for all species in both complexes using Bayesian inference. Circles represent the mean estimate, thick lines the 50% confidence interval and thin lines the 95% confidence interval, and color the corresponding species. Vertical lines indicate from left to right: (i) tree recruitment diameter and (ii) and (iii) 95th percentile of diameter for *Eschweilera* and *Symphonia*, respectively."}
lapply(fits, function(fit) 
  mcmc_intervals_data(as.array(fit,
                               pars = "betaDBH"))) %>% 
  bind_rows(.id = "model") %>% 
  separate(model, c("complex", "trait"), "-",remove = F) %>%
  mutate(species = gsub("([[:punct:]])", "", parameter)) %>% 
  mutate(species = gsub("([[:alpha:]])", "", species)) %>% 
   mutate(species = as.numeric(species)) %>% 
  left_join(species) %>% 
  mutate(trait = recode_factor(trait, invLA = "frac(1, LA)")) %>% 
  mutate_at(vars("ll", "l", "m", "h", "hh"), funs(.*sdDBH*9)) %>% 
  ggplot(aes(x = SpeciesLong,
             xend = SpeciesLong,
             color = SpeciesLong, fill = SpeciesLong)) +
  geom_hline(yintercept = c(10, 57, 68), color = "gray90", size = 0.5) +
  geom_point(aes(y = m), shape = 21, size = 3, alpha = 0.5) +
  geom_segment(aes(y = ll, yend = hh),
               size = 1, show.legend = F, alpha = 0.5) +
  geom_segment(aes(y = l, yend = h), size = 2, alpha = 0.5) +
  coord_flip() +
  facet_grid(trait ~ Genus, labeller = label_parsed, 
             scales = "free_y") +
  xaxis_title(F) +
  ylab(expression(DBH[90]~(cm))) +
  scale_y_log10() +
  scale_colour_brewer(guide = "none", palette = "Set1") +
  scale_fill_brewer(guide = "none", palette = "Set1")
```

```{r NicheBreadth, fig.cap="Species niche breadth along the topographic wetness index (TWI) for all species from Paracou. Niche breadth has been calculated as the difference between the 95th quantile and the 5th quantile of TWI for all species from Paracou with at least 20 individuals. Dashed vertical lines represent niche breadth value for species from this study indicated by line color. E. coriacea and the two Symphonia species have bigger niche breadth than most Paracou species but E. sagotiana and E. coriacea have niche breadth similar to the majority of Paracou species.", fig.height=3}
paracou <- src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>% 
  filter(CensusYear == 2017) %>% 
  collect() %>% 
  mutate(SpeciesLong = paste(Genus, Species))
env <- paracou %>%
   dplyr::select(SpeciesLong, idTree, Xutm, Yutm) %>%
   unique() %>% 
  na.omit()
coordinates(env) <- ~Xutm + Yutm
proj4string(env) <- '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0'
crs <- '+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0' # global crs definition
env <- spTransform(env, CRSobj = crs)
twi <- raster(file.path(path, "topography", "TWI_1m.tif"))
twi <- projectRaster(twi, crs = crs)
env <- data.frame(cbind(env@data, twi = raster::extract(twi, env)))
env %>% 
  group_by(SpeciesLong) %>% 
  filter(n() > 20) %>% 
  summarise(TWIbreadth = quantile(twi, 0.95) - quantile(twi, 0.05)) %>% 
  ggplot(aes(TWIbreadth)) + 
  geom_histogram(fill = "lightgrey", col = NA) + 
  geom_vline(aes(xintercept = breadth, col = Species), linetype = "dashed", 
               data = data.frame(breadth = c(4.12 - 0.97, 6.31 - 1.59, 3.52 - 1.06, 4.92 - 0.96, 2.78 - 1.06),
                               Species = c("S. sp1", "S. globulifera", "E. sagotiana", "E. coriacea", "E. decolorans"))) +
  scale_x_sqrt() +
  ylab("N") + xlab("Species niche breadth along the topographic wetness index (TWI)") + scale_color_discrete("Studied species") +
  theme(legend.text = element_text(face = "italic"))
```

```{r Plot, fig.cap="Caption.", fig.height=8}
fits <- fits0
lapply(fits, function(fit) 
  mcmc_intervals_data(as.array(fit,
                               pars = "delta"))) %>% 
  bind_rows(.id = "model") %>% 
  separate(model, c("complex", "trait"), "-",remove = F) %>%
  mutate(PlotNum = gsub("([[:punct:]])", "", parameter)) %>% 
  mutate(PlotNum = gsub("([[:alpha:]])", "", PlotNum)) %>% 
  mutate(PlotNum = as.numeric(PlotNum)) %>% 
  left_join(plots) %>% 
  mutate(trait = recode_factor(trait, invLA = "frac(1, LA)")) %>% 
  ggplot(aes(x = Plot,
             xend = Plot)) +
  geom_point(aes(y = m), shape = 21, size = 3, alpha = 0.5) +
  geom_segment(aes(y = ll, yend = hh),
               size = 1, show.legend = F, alpha = 0.5) +
  geom_segment(aes(y = l, yend = h), size = 2, alpha = 0.5) +
  coord_flip() +
  facet_grid(trait ~ Genus, labeller = label_parsed) +
  ylab("")
```

<!-- old supp -->

```{r varcomp, fig.cap="Variance decomposition between ecological levels.", eval=F}
traitsSymphonia <- googlesheets::gs_title("Measures_Symphonia") %>%
  googlesheets::gs_read("AllTraits") %>%
  mutate(SLA = as.numeric(SLA), LDMC = as.numeric(LDMC)) %>%
  mutate(Genus = "Symphonia") %>%
  rename(Species = Morphotype) %>%
  mutate(Species = ifelse(Species == "Indet.",
                          c("globulifera", "sp.1", "sp.1")[fct_recode(Bark, "globulifera" = "G",
                                     "sp.1" =  "S")], Species))
traitsEschweilera <- googlesheets::gs_title("Measures_Eschweilera") %>%
  googlesheets::gs_read("AllTraits") %>%
  filter(!(Plot == 14 & SubPlot == 1 & TreeFieldNum == 760)) %>%  # outlier
  filter(!(Species %in% c("congestiflora","simiorum","persistens")))
traits <- bind_rows(traitsEschweilera, traitsSymphonia) %>%
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>%
  group_by(idTree, Plot, SubPlot, TreeFieldNum, Genus, Species,
           SpeciesLong, Bark, Dawkins)
traits %>% 
  mutate(LMA = (1/SLA)*10^4) %>% 
  group_by(Species) %>% 
  filter(n() > 10) %>% 
  filter(CC > 0) %>% # CC have an issue for lme
  select(Plot, Genus, Species, idTree, Leaf,
         LMA, LDMC, LT, LA, CC) %>% 
  reshape2::melt(id.vars = c("Plot", "Genus", "Species", "idTree", "Leaf"), 
                 variable.name = "Trait") %>% 
  na.omit() %>% 
  group_by(Trait) %>% 
  do(varcomp = as.vector(ape::varcomp(nlme::lme(log(value) ~ Plot,
                            random=~1|Genus/Species/idTree/Leaf, 
                            data = ., na.action = na.omit), 1))) %>% 
  broom::tidy(varcomp) %>% 
  rename(Variance = x) %>% 
  mutate(Component = c("Genus", "Species", "Tree", "Leaf", "Residual")) %>% 
  ggplot(aes(Trait, Variance, label = round(Variance*100), 
             fill = factor(Component, levels = c("Genus", "Species", 
                                                 "Tree", "Leaf", "Residual")))) +
  geom_bar(stat = "identity") +
  scale_fill_brewer("Component", palette = "Accent") +
  geom_text(position = position_stack(vjust = 0.5))
```

```{r bootstrap, fig.cap="Coefficient of variation of mean estimation depending on the number of individuals sampled of DBH > 30 cm.", eval=F}
t <- Individuals0 %>% 
  mutate(LMA = (1/SLA)*10^4) %>% 
  group_by(Species) %>% 
  filter(n() > 10) %>% 
  filter(DBH*sdDBH > 30) %>%
  select(Genus, Species, LMA, LDMC, LT, LA, CC) %>% 
  reshape2::melt(id.vars = c("Genus", "Species"), variable.name = "Trait") %>% 
  na.omit() %>% 
  group_by(Genus, Species, Trait, value) %>% 
  expand(n = 2:10) %>% 
  group_by(Genus, Species, Trait, n) %>% 
  do(cv = sd(apply(replicate(1000, sample(.$value, .$n)), 2, mean))/mean(.$value)*100) %>% 
  broom::tidy(cv) %>% 
  rename(cv = x)
ggplot(t, aes(as.factor(n), cv, fill = Trait)) +
  geom_boxplot() +
  stat_summary(fun.y=mean, geom="line", aes(group=1)) +
  facet_grid(~ Trait) +
  scale_fill_discrete(guide = "none") +
  xlab("Number of tree sampled") +
  ylab("Coefficient of variation (%).") +
  scale_y_sqrt()
```
