---
title: Topography consistently drives intra- and interspecific leaf trait variation within Neotropical tree species
output:
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
  bookdown::html_document2:
    number_sections: false
    toc: true
    toc_float: yes
  bookdown::word_document2: default
linestretch: 1.5
csl: /home/sylvain/Documents/Bibliography/csl/joe.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

1. Sylvain Schmitt
    - Corresponding author: sylvain.m.schmitt@gmail.com
    - orcid.org/0000-0001-7759-7106
    - UMR BIOGECO, INRA - Université de Bordeaux, 69 route d’Arcachon, F-33612 Cestas cedex France
1. Bruno Hérault2,3
    - orcid.org/0000-0002-6950-7286
    - Cirad, UR Forests and Societies, Univ Montpellier, Montpellier, France
    - Institut National Polytechnique Félix Houphouët-Boigny (INP-HB), BP 1093, Yamoussoukro, Ivory Coast
1. Émilie Ducouret
    - Cirad, UMR EcoFoG (Agroparistech, CNRS, INRA, Université des Antilles, Université de la Guyane), Campus Agronomique, 97310 Kourou, French Guiana
1. Anne Baranger
    - UMR BIOGECO, INRA - Université de Bordeaux, 69 route d’Arcachon, F-33612 Cestas cedex France
1. Niklas Tysklind
    - INRA, UMR EcoFoG (Agroparistech, CNRS, Cirad, Université des Antilles, Université de la Guyane), Campus Agronomique, 97310 Kourou, French Guiana
1. Myriam Heuertz
    - orcid.org/0000-0002-6322-3645
    - UMR BIOGECO, INRA - Université de Bordeaux, 69 route d’Arcachon, F-33612 Cestas cedex France
1. Éric Marcon
    - orcid.org/0000-0002-5249-321X, 
    - UMR EcoFoG, Agroparistech, CNRS, Cirad, INRA, Université des Antilles, Université de la Guyane, Campus Agronomique, 97310 Kourou, French Guiana
1. Saint Omer Cazal
    - INRA, UMR EcoFoG (Agroparistech, CNRS, Cirad, Université des Antilles, Université de la Guyane), Campus Agronomique, 97310 Kourou, French Guiana
1. Géraldine Derroire
    - orcid.org/0000-0001-7239-2881
    - Cirad, UMR EcoFoG (Agroparistech, CNRS, INRA, Université des Antilles, Université de la Guyane), Campus Agronomique, 97310 Kourou, French Guiana

# Authors’ contributions

SS, GD, BH, ED, and AB conceived the ideas; SS, GD, BH, and AB designed the methodology; SS and GD analysed model outputs; SS, GD and MH led the writing of the manuscript. All authors contributed critically to the drafts and gave final approval for publication.

# Acknowledgements
We thank the University of Bordeaux for a PhD grant to Sylvain Schmitt and acknowledge the support of a grant from Investissement d’Avenir grants of the ANR (CEBA:ANR-10-LABX-25-01) and from the GUYAMAZON program (LECYTOMICS project). We are grateful to Pascal Petronelli and the CIRAD inventory team for their work on tree inventories and botanical identification. Special thanks go to Josselin Cazal, Ilke Gelaldi, Fabien Lehuede, Adeline Adam, Agathe Benfredj Zaleski, Numa Faucherre, and David Zipper for their assistance during sampling in Paracou station.
