```{r setup_capture, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(parallel)
library(tidyverse)
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
path <- "~/Documents/BIOGECO/PhD/data/Symphonia_Paracou/"
```

# Capture

After library preparation, we prepared plates for capture. We proceed as follow :

1. __Dosage__: Obtained libraries were dosed by PicoGreen after range assessment by NanoDrop and/or Qubit
1. __Equimolar pools preparation__: Equimolar pools were built for capture
1. __Pools fragment size evaluation__: Pool fragents sizes were evalutaed by Bioanalyzer
1. __Pools fragment size selection__: Pool fragments size were filtered by Pippin between 400 and 600 bp
1. __Capture__: ...

## Dosage

Obtained libraries were dosed by PicoGreen after range assessment by NanoDrop and/or Qubit

## Equimolar pools preparation

Equimolar pools were built for capture

## Pools fragment size evaluation

Pool fragents sizes were evalutaed by Bioanalyzer

## Pools fragment size selection

Pool fragments size were filtered by Pippin between 400 and 600 bp

## Capture

...
