```{r setupLargescale, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(parallel)
library(tidyverse)
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
path <- "../../../data/Eschweilera_Paracou"
```

```{r dataLargeScale}
largescale <- googlesheets::gs_title("LARGESCALE") %>% 
             googlesheets::gs_read("NanoDrop_20191004")
```

# (APPENDIX) Appendix {-} 

# Appendix 1: LARGESCALE

This an apendix for LARGESCALE lab work in Bordeaux for Niklas. All data are available on a [google sheet](https://docs.google.com/spreadsheets/d/1aEZb5WQOLWm2xLVMCLGJt4RIX_wG18NfqhLo1yUeM10/edit?usp=sharing).

## NanoDrop

There isn't a clear relation between concentration assessed in Bordeaux and concentration in Kourou, moreover the samples are really contaminated around 230 nm (Fig. \@ref(fig:nanodropLargescale)).

```{r nanodropLargescale, fig.cap="NanoDrop concentration."}
g1 <- largescale %>% 
  filter(!is.na(ConcentrationKourou)) %>% 
  ggplot(aes(Concentration, ConcentrationKourou, col = `260/230`)) +
  geom_point()
g2 <- ggplot(largescale, aes(`260/280`)) +
  geom_histogram() +
  geom_vline(xintercept = 1.8, linetype = "dashed", col = "red")
g3 <- ggplot(largescale, aes(`260/230`)) +
  geom_histogram() +
  geom_vline(xintercept = c(2,2.2), linetype = "dashed", col = "red")
cowplot::plot_grid(g1, g2, g3, nrow = 1, rel_widths = c(2,1,1))
```



