# Remerciements

À l’heure où je boucle ces trois années de thèse, je ne peux que me
sentir reconnaissant et chanceux de toutes les personnes qui m’ont
accompagné et dont j’ai croisé la route aussi bien lors de ma thèse que
lors du long du chemin qui m’y a amené. Malgré l’ensemble de la
rédaction que j’ai dû réaliser pour arriver jusque là, il me semble
difficile de remercier exhaustivement les personnes qui ont compté pour
moi, et je m’excuse grandement auprès de celles que j’aurais le malheur
d’oublier. Bien que j’aime à discuter de la biodiversité des arbres
tropicaux, le parcours qui m’a amené jusqu’ici a aussi été l’occasion de
me confronter à une richesse humaine extraordinaire aux quatres coins du
monde !

L’écriture de cette thèse a été un long travail, mais je n’imagine pas
le travail que cela représente de l’évaluer. Je remercie donc les
rapporteurs, **Xavier Vekemans** et **XX XX**, ainsi que les
examinateurs, **Olivier Hardy**, **Céline Teplitsky**, **Caroline
Scotti-Saintagne** et **Marta Benito-Garzón** pour leur intérêt et
l’honneur qu’ils me font de participer à mon jury de thèse.

Je ne pourrais commencer sans citer l’incomparable mais aussi diverse
équipe d’encadrants géniaux qui m’a supervisé et accompagné pendant
trois ans. La richesse de cette thèse commence en effet avec vous qui
venez des quatres coins de l’Europe et du monde. Vous qui vivez chacun
sur votre continent où vous m’avez toujours accueilli au delà de mes
espérances. Vous qui par votre diversité fonctionnelle, autant
académique qu’humaine, créez, à mon humble avis, la richesse et la force
de cet encadrement. Merci à **Myriam Heuertz** pour ton dynamisme et ta
force pour toujours avancer, que tu as su me prêter dans la réalisation
de mon doctorat. Mais aussi merci pour ce cadre humain que tu as pu
donner à mes trois années: merci pour l’accueil à Bordeaux lors de mon
retour de Guyane, merci pour l'incroyable opportunité que tu m’as donné
avec l’Équateur qui fut involontairement un magnifique cadeau
d’anniversaire, et j’espère pouvoir courir un jour le marathon de
Bordeaux avec toi. Merci à **Bruno Hérault** d’avoir accepté de partager
ces réflexions incessantes qui m’ont permis d’aller au delà d’où je
pouvais espérer atterrir. Je pense que ta manière de réfléchir et de
toujours remettre en question ce qui peut être trop facilement admis est
primordiale, et j’espère qu’elle restera avec moi au cours de mes futurs
travaux. Merci pour ton humanité qui valorise une existence hors du
travail, merci pour le vélo, les repas, les rigolades et discussions
chez toi, chez moi, au bureau ou sur le terrain. Merci enfin à **Niklas
Tysklind** d’avoir depuis la première minute et encore aujourd’hui
beaucoup plus cru en moi que moi-même ! À l’heure où nous essayons de
pousser le chapitre 4 vers une revue prestigieuse, je ne peux m'empêcher
de me rappeler que dès le début tu m’a dit le premier, alors que cela me
paraissait totalement inatteignable, que j’arriverais à ce stade. Enfin
en plus du fait que tu es toujours aussi agréablement positif et à te
réjouir de nos travaux, je suis pour ma part admiratif de ta capacité à
rester humble et garder une vie personnelle épanouie, et tu es
réellement un modèle pour moi sur ce point. Vous variez peut être du
point de vue de l’administration, mais vous êtes à mes yeux tous les
trois aussi importants. Je n’ai eu cesse de me rendre compte de la
chance que j’ai eu de vous avoir tous les trois au cours de ces années.
Au delà de l’opportunité que vous m’avez donné de m’épanouir au sein de
cette thèse, je vous remercie pour l’encadrement académique mais surtout
pour votre humanité. Je n’ai qu’une demande à vous faire, s’il vous
plaît ne changez pas sur votre ambivalence académique et humaine !

Bien que ma thèse ait démarré le 1er septembre, ma passion pour les
forêts tropicales a eu lieu dès mon année de césure et s’est poursuivie
au cours de mon master 2. Je tiens donc à remercier toute la
génialissime équipe du laboratoire d’écologie végétale appliquée de
l’Institut Agronomique néo-Calédonien : **Philippe Birnbaum**, **Robin
Pouteau**, **Dimitri Justeau**, **Santiago Trueba Sanchez**, **Florian
de Boissieu**, **Élodie Blanchard**, **Laure Barrabé**, **Vanessa
Hequet**, **Céline Chambrey**, **Hervé Vandrot** et bien entendu
**Tanguy Jaffré** . À vous qui m’avez transmis cette passion pour la
biodiversité des forêts tropicales tout en me berçant déjà de comptes
sur la folie du bassin Amazonien. De la même manière je suis
reconnaissant à tout ce qu’ont pu me procurer botaniquement,
scientifiquement et humainement les différentes personnes que j’ai pu
croiser à l'Institut Français de Pondichéry en Inde : **Maxime Réjou
Méchain**, **François Munoz**, **Valérie Raevel**, **Narayanan
Ayyappan**, **Natesan Balachandran**, et **Natesan Barathan,** mais
aussi **Jules Morel**, **Anaïs Valance**, **Sonia Dinh**, **Grégoire
Bobo**, **Charles Trivandrum**, **Maéva Sinou** et **Élodie da Silva**.
Sans vous et les judicieux conseils de **Bruno Ferry**, je ne serais
sans doute jamais allé rencontrer l’Amazonie lors de mon master 2 en
Guyane.

Je ne compte plus mes passages en Guyane, et il est par conséquent
compliqué de remercier chronologiquement toutes les personnes qui sont
responsable de mon envie incessante de retourner dans le bassin
Amazonien. J’ai une première pensée pour mes camarades de master 2 avec
qui j’ai partagé la découverte de ce territoire magique : **Timothée
Audinot**, **Amandine Confais**, **Solène D’Angelo**, **Oksana Grente**,
**Pauline Guillaumeau**, **Mathieu Jegu**, **Morgan Knoster**, **Laurie
Lefebvre**, et **Hugo Reizine**. Je remercie grandement l’équipe
d’encadrants du master qui ont su patiemment nous transmettre leur
passion et leur savoir des forêts tropicales tout en créant des
conditions d’étude adorables que j’ai rarement pu rencontrer en France :
**Eric Marcon**, **Stéphane Traissac**, **Timothy Chubb**, **Sabrina
Coste**, **Jean-Christophe Roggy**, **Patrick Heuret**, et **Pascal
Petronelli**. Je remercie les stagiaires, doctorants, et amis qui ont
accompagné mon stage de master 2 : **Sébastien Levionnois**, **Camille
Dezécache**, **Camille Piponiot**, **Ariane Mirabel**, **Élodie
Boriau**, **Louise Authier**, **Jean Legay**. Je dois un éternel
remerciement à **Saint-Omer Cazal** avec qui j’ai vécu tous ces mois de
terrain à Paracou et sans qui toute cette thèse ne serait pas ce qu’elle
est. J’en profite pour remercier la très joviale équipe de génétique,
**Valérie Troispoux**, **Éliane Louisanna**, et **Adrien Lalagüe**, avec
qui j’ai adoré me réunir autour d’un café après un petit nettoyage de
laboratoire. Je remercie toutes les personnes qui m’ont accompagné sur
le terrain : **Josselin Cazal**, **Ilke Gelaldi**, et **Fabien
Lehuede.** Mais aussi ma génialissime équipe de module FTH : **Adeline
Adam**, **Agathe Benfredj Zaleski**, **Numa Faucherre**, et **David
Zipper**. Je pense ne jamais oublier nos trajets vers la parcelle 16
accompagné des chants sur “Margot”. Il m’est difficile de remercier tous
les stagiaires, masters, doctorants, et amis croisés sur le campus ou
dans Kourou, mille excuses par avance aux oubliés. Merci à, **Adrien**,
**Alexandre**, **Dimitri**, **Alex**, **Emma**, **Eva**, **Guillaume**,
**Irene**, **Laurent**, **Maelle**, **Margot**, **Maxim**, **Paloma**,
**Tom**, **Warren**, **Xavier** d’avoir rendu ces moments si vivants. Et
pour la fin, je tiens à remercier les stagiaires que j’ai pu encadrer :
**Émilie Ducouret**, **Nino Page**, et **Anne Barranger**. Vous êtes
aussi géniaux que divers, et vous m’avez sans aucun doute appris autant
que ce que j’ai pu vous transmettre.

Bien que la Guyane ait sans doute été le lieu le plus marquant de ma
thèse, mes passages à Bordeaux, en Équateur et en Côte d’Ivoire ont
aussi été marqués par des personnes remarquables. Je remercie entre
autre **Katharina Budde**, **Santiago González Martinez**, **Arthur 
Demené**, **Juliette Archambeau**, *et **Elena Valdés-Correcher** de
leur accueil chaleureux au sein de BIOGECO. Merci à **Gonzalo Francisco
Rivas Torres** et **Pieter van \`t Hof** de m’avoir fait aimer
l’Équateur en si peu de temps, et de m’avoir emmené dans la station de
recherche de Tiputini, sans doute la plus incroyable qu’il m'ait été
donné de connaître. Enfin mon passage en Côte d’Ivoire s’est aussi bien
déroulé malgré la crise sanitaire qui m’a contraint à y rester plus
longtemps que prévu grâce à l’incroyable qualité de l’accueil et la
sympathie des personnes rencontrées à Yamoussoukro. On m’avait vanté la
qualité de l’accueil en Afrique de l’ouest, mais la réalité dépasse une
fois de plus les attentes ! Je remercie de tout mon coeur la **famille
Hérault**, **Amani Bienvenu Hippolyte Konan**, **Irie Casimir Zo-Bi,
Aimé**, **Marie**, **Ibe**, **Kassi**, **Edi**, **Antoine de Troij**,
**Noémie Glapa**, et **Vincyane Badouard** avec qui j’ai passé ces six
mois et à cause de qui je n’avais plus envie de quitter le pays à
l’heure où la frontière à réouverte !

J’aimerais terminer ces remerciements par ma famille d’adoption et ma
vraie famille. En effet mes colocataires qui m’ont innocemment accueilli
à Bordeaux au début de ma thèse, sont désormais pour moi une vraie
famille d’adoption dans cette ville qui m'était jusqu’alors inconnue.
Merci à **Pauline Daniel**, **Mathilde Faisant**, **Thomas Devaux**,
**Lola Vivant**, **Kévin Huonic**, **Tom Allibert**, **Rémy Boudet**,
**Antoine Buquen**, et les nombreux sous-loc qui ont partagé mon toit au
cours de ces trois années, je ne peux imaginer une vie à Bordeaux sans
vous ! Je souhaite profondément remercier mes parents qui m’ont transmis
cet amour du vivant qui m'a poussé à devenir qui je suis aujourd’hui :
**Bernard Schmitt** et **Thérèse Piel**. J’aurais toujours un éternel
respect pour ce que vous avez accompli, qui restera à mes yeux toujours
plus important et concret que n’importe lequel de mes travaux. Merci
aussi à mes frères et soeur qui composent la diversité de cette famille
**Aurore**, **Emmanuel**, et **Mikaël**. Mille mercis plus généralement
à toutes les personnes qui ont gravité autour de moi pendant ces trois
années de thèse aux quatres coins du monde.

Pour finir, je souhaite dédier cette thèse à mon neveu **William** et ma
nièce **Océane** en espérant qu’ils aient l’opportunité de voir une
nature aussi belle que celle que ces magnifiques années ont pu
m’apporter !


