# Introduction

## Plan

1. Tropical forest: tremendous biodiversity and threats
    1. Tropical forests outstanding biodiversity
        * [@Gaston2000]
        * [@connell_diversity_1978]
    1. Lowland Amazonia regional richness
        * [@TerSteege2013]
    1. Lowland Amazonia local richness
        * [@Gentry1988]
    1. Tropical forests threats
1. Biodiveristy structure in tropical forests
    1. three levels of biodiversity
    1. Limits of the species concepts
        * Species definiton by Line
    1. Neglected intraspecific variability
        * [@Messier2010]
        * [@Siefert2015a]
        * genetic, ontogenic, plastic [@BenitoGarzon2019], and random
    1. Species-rich but genus-poor in lowland Amazonia (regional)
        * [@TerSteege2013]
    1. closely-related species grow in sympatry (local)
        * [@Caron2019]
    1. Species complexes and syngameons neglected potential in Bioidiveristy structure of Amazonia
        * [@Pernes1984]
        * [@Suarez-Gonzalez2018]
1. Species local coexistence in ecology
    * Ecological theory
        * Niche theory
            * [@lortie_rethinking_2004-1]
            * [@weiher_assembly_1995]
            * access to light [@Yamasaki2013]
        * Neutral theory
            * [@Hubbell2001]
            * [@chave_neutral_2004]
        * Emergent groups
            * [@Herault2007]
        * Intermediate disturbance hypothesis
            * [@Molino2001]
        * density-dependence
            * [@Volkov2005]
            * [@Comita2010]
    * Functional ecology
        * [@Umana2019]
    * Growth and performance
    * All theory ignored genotypic and phenotypic variation within species despite the limits of the species concept => transition to ecological genomics
1. Beyond the species concept: genetic diversity and structure within and among species
    * Ecological genomics
        * genetic mechanisms that underly the responses of organisms to their natural environments (Ungerer et al. 2008; Morgan et al. 2018)
        * bridge ecology and evolution
        * ecology disregard genetic values through individual
        * evolution focused on genes functions outside of their naturl environment
    * Tree evolutionary peculiarites [@Petit2006]
        * genetic diveristy but weak differentiation [@Hamrick1992b; @Nybom2004]
        * low specition [@Petit2006]
        * large effective population sizes (Heuertz et al; 2006)
        * great size and longevity
        * overlapping generations and high reproductive outputs
        * outcrossing mating systems and high level of gene flow (hybridization)
        * high fecundity and strong seleciton in early life stages (Fallour-Rubio et al. 2009; Kremer et al. 2012)
    * phylogenetic constraints 
        * [@Wiens2010]
    * ecoevolution
        * [@Dobzhansky1973]
        * [@Pelletier2009]
        * [@Tutt1896]
        * [@Bailey2009]
    * Adaptive radiations 
        * [@Seehausen2004]
        * sympatric ecological speciation to seconday contacts of species ecologically specialised in allopatry or parapatry [@rundell_adaptive_2009]
        * topography or other abiotic radiations for tropical trees [@Paun2016; @Pillon2014]
    * local adaptation 
        * [@Lascoux2016]
        * [@Savolainen2013]
    * Microgeographic adpatations
        * [@Richardson2014]
        *  under gene-flow [@Tigano2016]
        * with topography [@Brousseau2015; @Team2013]
    * genomic processes and methodology
        * mutation, standing genetic varaition, adaptive introgression
        * selective sweep
        * QTL
        * association mapping
        * genomic scans 
        * beware of population structure
        * major effect allele
        * polygenic modelling (Zeng et al. 2018)
1. Context: Amazon Basin to Paracou
    1. Amazon Basin
        1. Environmental drivers
            * Globally geology, topography, stability, Amazon river, Andean lift...
        1. Past occupations
            * Precolumbian occupations
                * [@Odonne2019]
        1. Forest dynamics
            * hyperdominants
                * [@TerSteege2013]
            * niche and topography
                * ?
            * successional dynamics
                * [@Craven2015]
                * [@VanBreugel2012]
        1. Forest threats
    1. Guiana Plateau
        1. Environmental specificity
            * Poorer...
        1. Forest dynamics specificity
            * Slow rates, etc...
        1. Forest threats specificity
            * Gold ?
    1. Paracou
        1. Local environmental drivers
            * topography is spatially driving water and nutrient distribution in tropical forest [@Ferry2010]
            * forest gap dynamics
                * [@Hubbell1999]
                * [@Molino2001]
                * should be better and more local litterature
        1. Forest dynamics
            1. Distribution
                * topography leads pervasive habitat differentiation among species [@Allie2015]
                * [@Wagner2011]
                * [@Aubry-Kientz2015a]
            1. Functional
                * decoupled spectrum [@Baraloto2010]
                * effect on growth [@Herault2011]
            1. Performance
                * Growth [@Herault2010; @Herault2018; @Wagner2012]
                * Death [@Aubry-Kientz2013; @Aubry-Kientz2015]
                * Repdocution and dispersion [@Hardy2006]
            1. Genetic diversity
        1. Logging
1. Models: *Symphonia* and *Eschweilera*
    1. *Symphonia*
        * *Symphonia globulifera* L. f. (Clusiaceae)
        * One widespread species, *S. globulifera* L. f. in Africa and the Neotropics, and some 20 species endemic to Madagascar (Perrier de la Bâthie 1951; Abdul-Salim 2002) local adpatation within and among species
        * pollintation by hummingbirds, perching birds and lepidoptera in the Neotropics
        * pollintation by sunbirds in Africa
        * seed dispersal by bats and tapirs in the Neotropics 
        * seed dispersal by small mammals in Africa 
        * [@Torroba-Balmori2017]
        * widespread hypervariable pantropical tree
        * living fossile with pollen in the Niger delta dated to 45Ma
        * Colonized Americas from Africa ca 18-15 Ma (Dick et al. 2003)
        * [@Budde2013]
        * [@Degen2004]
        * [@Dick2008]
        * Published genome [@Olsson2017]
    1. *Eschweilera*
        1. *Eschweilera* taxonomy
        1. *Eschweilera* morphology
        1. *Eschweilera* ecology
        1. *Eschweilera* biogeography and evolution
1. Questions
    1. General question ? (if I have one)
    1. Species local distribution within and among species complexes
    1. Functional traits within and among species within species complexes along local enviornmental gradients
    1. Genetic adaptation within among
    1. Growth and genetics within among
    1. Environment and genetics interplay in coexistence within and among species within species complexes
1. Hypotheses 
    * _optimally one hypothesis and one counter-hypothesis per question_
1. General scheme
    1. GxE~P scheme
    1. Chapters plan
    
## Vocabulary / concept box *(TEE style)*

* species complex
* syngameon
* adaptive radiation
* local adaptation
* microgeographic adaptation
