# Introduction

## Plan short

1. Biodiversity within tropical forest from the Amazon Basin
    1. Tropical forests outstanding biodiversity
    1. Tropical forests threats
    1. Regional and local richness from the Amazon Basin
    1. Many tree species but few tree genera in the Amazon Basin
    1. The paradoxical coexistence of closely-related species in sympatry
1. Biodiversity structure in tropical forests
    1. The three levels of biodiversity
    1. The limits of the species concept
    1. Beyond species: species complexes and syngameons
    1. The neglected intraspecific variability
1. Species local coexistence in ecology
    1. Niche and neutral theory
    1. Neighbour crowding and competition
        * Janzen-Connell hypothesis
        * Neighbor density-dependence
        * Conspecific neighbor density-dependence
    1. Treefall and succession
        * Intermediate disturbance hypothesis
        * Successional niches
    1. Demography and fundamental tradeoffs
        * Growth, survival and reproduction
        * Fast-slow continuum, staure-recruitment trade-off, and reproductive strategy
    1. Functional traits: from fundamental tradeoffs to ecological niches
    1. Transition: 
        * Ignore genotypic and phenotypic variation within species 
        * Ignore evolutive forces driving past and future of biodiversity
1. Beyond species ecology: individual genetic adaptations within and among tree species
    1. Bridging ecology and evolution: ecological genomics
        * ecology disregard genetic values through individual
        * evolution focused on genes functions outside of their natural environment
        * genetic mechanisms that underlie the responses of organisms to their natural environments
        * eco-evolution litterature (Tutt, Dobzhansky, Pelletier, Bailey...)
    1. Tree evolutionary peculiarities
    1. Adaptation among species: adaptive radiations 
    1. Adaptation within species: local and microgeographic adaptations 
    1. Adaptation within individual: the genomics basis of adaptation
        1. Origin: mutation, standing genetic variation, and introgression
        1. Selection: hard sweep, soft sweep, polygenic adaptation and adaptive introgression
        1. Detection of adaptations: mapping (GWAS), selection scans, polygenic modelling
1. Study context: long-term study site of Paracou in a coastal forest of the Guiana Shield
    1. The Amazon Basin and the Guiana Shield
        1. Geology, climate and pedology
            * poorer soil from Guiana shield
        1. Forest dynamics
            * slower dynamic of the Guiana shield
        1. Past and current occupations
            * Precambrian occupations
            * Coastal populations
            * Selective logging
            * Gold mining
            * Land use change
    1. The long-term study site of Paracou
        1. The experimental design
            * Diameter censuses
            * Logging
            * Biodiversity plots
            * Lidar
            * Hydrology and edaphic properties
            * Climate
        1. Local forest dynamics and species distribution
            * climate
            * water, soil, topography
            * gaps
            * growth-survival tradeoff
            * functional tradeoff and composition
            * reproduction and dispersion
        1. Local genetic variations and adaptations
            * spatial structure and gene dispersal
            * topography
            * gaps
            * logging
1. Study models: *Symphonia globulifera* and *Eschweilera* clade Parvifolia two species complexes of locally abundant trees
    1. *Symphonia*
        * Taxonomy
        * Morphology
        * Ecology
        * Biogeography
    1. *Eschweilera*
        * Taxonomy
        * Morphology
        * Ecology
        * Biogeography
1. Issue and general plan
    1. General
        * Q: Are individual genotypes and phenotype adapted to microgeographic 
            topography and forest gap dynamics within and among species of species complexes?
        * H: Individual genetic and phenotypic variability within and among species 
            promotes local coexistence within species complexes through microgeographic adaptations to topography and forest gap dynamics.
        * include PhD scheme here
    1. Species distribution within and among species complexes
        1. Q: How are species distributed within and among species complexes along biotic and abiotic gradients in Paracou?
        1. H: Species complexes are widely spread across biotic and abiotic environments; whereas biotic and abiotic environments favor 
            niche differentiation among species within species complexes.
    1. Leaf functional traits within and among species
        1. Q: How does the abiotic environment influence individual leaf trait values among and within 
            closely-related species within species complexes?
        1. H: The abiotic environment shaped trait variation both among and within species in interaction with 
            tree diameter and access to light within species complexes.
    1. Individual and species adaptation to topography
        1. Q: Are tree species and individuals adapted to the fine-scale topographic gradient?
        1. H: Species are delineated along topography with fixed neutral and adaptive variants within species complexes.
    1. Individual and species adaptation to forest gap dynamics
        1. Q: Are tree species and individuals adapted to a trade-off between growth and competition to answer forest gap dynamics?
        1. H: Individual genotypes are adapted to a trade-off between growth and competition to answer forest gap dynamics.
    1. **Chapter 5?** Environment, adaptations, and coexistence within and among species
        1.  Q: How tree species and individuals adaptations to microgeographic topography and forest gap 
            dynamics drive coexistence within and among species of the *Symphonia* species complexe ?
        1. H: Genotypic adaptations within species of *Symphonia* decrease the risk of a stochastic local extinction 
            due to wide successional niches to respond to fine spatio-temporal dynamics of forest gaps; 
            while species adaptations stabilize local coexistence with differentiated species’s 
            topographic niches within the *Symphonia* species complexe .

## Plan long

1. Tropical forest: tremendous biodiversity and threats
    1. Tropical forests outstanding biodiversity
        * [@Gaston2000]
        * [@connell_diversity_1978]
    1. Lowland Amazonia regional richness
        * [@TerSteege2013]
    1. Lowland Amazonia local richness
        * [@Gentry1988]
    1. Tropical forests threats
1. Biodiveristy structure in tropical forests
    1. three levels of biodiversity
    1. Limits of the species concepts
        * Species definiton by Line
    1. Neglected intraspecific variability
        * [@Messier2010]
        * [@Siefert2015a]
        * genetic, ontogenic, plastic [@BenitoGarzon2019], and random
    1. Species-rich but genus-poor in lowland Amazonia (regional)
        * [@TerSteege2013]
    1. closely-related species grow in sympatry (local)
        * [@Caron2019]
    1. Species complexes and syngameons neglected potential in Bioidiveristy structure of Amazonia
        * [@Pernes1984]
        * [@Suarez-Gonzalez2018]
1. Species local coexistence in ecology
    * Ecological theory
        * Niche theory
            * [@lortie_rethinking_2004-1]
            * [@weiher_assembly_1995]
            * access to light [@Yamasaki2013]
        * Neutral theory
            * [@Hubbell2001]
            * [@chave_neutral_2004]
        * Emergent groups
            * [@Herault2007]
        * Intermediate disturbance hypothesis
            * [@Molino2001]
        * density-dependence
            * [@Volkov2005]
            * [@Comita2010]
    * Functional ecology
        * [@Umana2019]
    * Growth and performance
    * All theory ignored genotypic and phenotypic variation within species despite the limits of the species concept => transition to ecological genomics
1. Beyond the species concept: genetic diversity and structure within and among species
    * Ecological genomics
        * genetic mechanisms that underly the responses of organisms to their natural environments (Ungerer et al. 2008; Morgan et al. 2018)
        * bridge ecology and evolution
        * ecology disregard genetic values through individual
        * evolution focused on genes functions outside of their naturl environment
    * Tree evolutionary peculiarites [@Petit2006]
        * genetic diveristy but weak differentiation [@Hamrick1992b; @Nybom2004]
        * low specition [@Petit2006]
        * large effective population sizes (Heuertz et al; 2006)
        * great size and longevity
        * overlapping generations and high reproductive outputs
        * outcrossing mating systems and high level of gene flow (hybridization)
        * high fecundity and strong seleciton in early life stages (Fallour-Rubio et al. 2009; Kremer et al. 2012)
    * phylogenetic constraints 
        * [@Wiens2010]
    * ecoevolution
        * [@Dobzhansky1973]
        * [@Pelletier2009]
        * [@Tutt1896]
        * [@Bailey2009]
    * Adaptive radiations 
        * [@Seehausen2004]
        * sympatric ecological speciation to seconday contacts of species ecologically specialised in allopatry or parapatry [@rundell_adaptive_2009]
        * topography or other abiotic radiations for tropical trees [@Paun2016; @Pillon2014]
    * local adaptation 
        * [@Lascoux2016]
        * [@Savolainen2013]
    * Microgeographic adpatations
        * [@Richardson2014]
        *  under gene-flow [@Tigano2016]
        * with topography [@Brousseau2015; @Team2013]
        * with fores dynamics (Jones Hubbel 2006)
    * genomic processes and methodology
        * mutation, standing genetic varaition, adaptive introgression
        * selective sweep
        * QTL
        * association mapping
        * genomic scans 
        * beware of population structure
        * major effect allele
        * polygenic modelling (Zeng et al. 2018)
1. Context: Amazon Basin to Paracou
    1. Amazon Basin
        1. Environmental drivers
            * Globally geology, topography, stability, Amazon river, Andean lift...
        1. Past occupations
            * Precolumbian occupations
                * [@Odonne2019]
        1. Forest dynamics
            * hyperdominants
                * [@TerSteege2013]
            * niche and topography
                * ?
            * successional dynamics
                * [@Craven2015]
                * [@VanBreugel2012]
        1. Forest threats
    1. Guiana Plateau
        1. Environmental specificity
            * Poorer...
        1. Forest dynamics specificity
            * Slow rates, etc...
        1. Forest threats specificity
            * Gold ?
    1. Paracou
        1. Local environmental drivers
            * topography is spatially driving water and nutrient distribution in tropical forest [@Ferry2010]
            * forest gap dynamics
                * [@Hubbell1999]
                * [@Molino2001]
                * should be better and more local litterature
        1. Forest dynamics
            1. Distribution
                * topography leads pervasive habitat differentiation among species [@Allie2015]
                * [@Wagner2011]
                * [@Aubry-Kientz2015a]
            1. Functional
                * decoupled spectrum [@Baraloto2010]
                * effect on growth [@Herault2011]
            1. Performance
                * Growth [@Herault2010; @Herault2018; @Wagner2012]
                * Death [@Aubry-Kientz2013; @Aubry-Kientz2015] (Pillet et al., 2018)
                * Repdocution and dispersion [@Hardy2006]
            1. Genetic diversity
                * Degen 2011, 2013
                * Scotti
                * William Montaigne
                * Brousseau
                * Audigeos
                * Leclerc
        1. Logging
1. Models: *Symphonia* and *Eschweilera*
    1. *Symphonia*
        * *Symphonia globulifera* L. f. (Clusiaceae)
        * One widespread species, *S. globulifera* L. f. in Africa and the Neotropics, and some 20 species endemic to Madagascar (Perrier de la Bâthie 1951; Abdul-Salim 2002) local adpatation within and among species
        * pollintation by hummingbirds, perching birds and lepidoptera in the Neotropics
        * pollintation by sunbirds in Africa
        * seed dispersal by bats and tapirs in the Neotropics 
        * seed dispersal by small mammals in Africa 
        * [@Torroba-Balmori2017]
        * widespread hypervariable pantropical tree
        * living fossile with pollen in the Niger delta dated to 45Ma
        * Colonized Americas from Africa ca 18-15 Ma (Dick et al. 2003)
        * [@Budde2013]
        * [@Degen2004]
        * [@Dick2008]
        * Published genome [@Olsson2017]
    1. *Eschweilera*
        1. *Eschweilera* taxonomy
        1. *Eschweilera* morphology
        1. *Eschweilera* ecology
        1. *Eschweilera* biogeography and evolution
1. Questions
    1. General question ? (if I have one)
    1. Species local distribution within and among species complexes
    1. Functional traits within and among species within species complexes along local enviornmental gradients
    1. Genetic adaptation within among
    1. Growth and genetics within among
    1. Environment and genetics interplay in coexistence within and among species within species complexes
1. Hypotheses 
    * _optimally one hypothesis and one counter-hypothesis per question_
1. General scheme
    1. GxE~P scheme
    1. Chapters plan
    
## Vocabulary / concept box *(TEE style)*

* species complex
* syngameon
* adaptive radiation
* local adaptation
* microgeographic adaptation
