# Résumé substantiel

## Introduction

### La biodiversité dans les espèces étroitement liées des forêts tropicales du bassin de l'Amazone

Les forêts tropicales abritent la plus grande diversité d'espèces au monde, un fait qui reste en partie inexpliqué et dont l'origine est sujette à débat. Même à l'échelle de l'hectare, les forêts tropicales abritent des genres riches en espèces, avec des espèces d’arbres étroitement apparentées qui coexistent en sympatrie. En raison de contraintes phylogénétiques, on s'attend à ce que les espèces étroitement apparentées possèdent des niches et des stratégies fonctionnelles similaires, ce qui questionne les mécanismes de leur coexistence locale. Les espèces étroitement apparentées peuvent former un complexe d'espèces, composé d’espèces morphologiquement similaires ou qui partagent une importante proportion de leur variabilité génétique en raison d'une ascendance commune récente ou d'hybridation, et qui peut résulter d'une radiation écologique adaptative des espèces selon des gradients environnementaux. Malgré le rôle clé des complexes d'espèces dans l'écologie, la diversification et l'évolution des forêts néotropicales, les forces éco-évolutives qui créent et maintiennent la diversité au sein des complexes d'espèces néotropicales restent peu connues. 

Les individus présentent eux mêmes des variations de performance, de phénotypes et de gènes au sein des espèces. La variation phénotypique, représentant *in fine* la variabilité intraspécifique, est façonnée par (i) le patrimoine génétique, au travers des génotypes, (ii) l'environnement (abiotique et biotique) avec une hétérogénéité spatiale et temporelle, et (iii) des facteurs stochastiques aléatoires. La variabilité intraspécifique est un sujet central en écologie et pourtant relativement inexplorée. Par conséquent, les complexes d'espèces et la variabilité intraspécifique pourraient être les clés pour démêler les forces éco-évolutives qui entraînent la coexistence locale d'espèces étroitement liées.

###  Coexistence locale des espèces : considérations écologiques et évolutives

La coexistence locale d'espèces proches, similaires sur le plan écologique et phénotypique, est régie par des processus écologiques et évolutifs, qui dépendent de l'histoire de la spéciation et de la différenciation des niches. Une fois en contact, les écologistes considèrent avant tout la compétition pour les ressources et la différenciation de niche qui en résulte, alors que les biologistes évolutionnistes s'intéressent davantage au niveau d'isolement reproductif. Pour une coexistence stable, la théorie des niches évoque que les espèces maximisent les différences de niches écologiques, tandis que la "théorie des similarités émergentes" réconcilie la théorie des niches et la théorie neutre en suggérant la coexistence de groupes distincts d'espèces qui sont fonctionnellement similaires au sein d'un groupe. Les espèces fonctionnellement similaires doivent avoir une fitness similaire comme condition supplémentaire pour une coexistence stable, et les espèces récemment divergentes doivent avoir développé un isolement reproductif suffisant pour éviter la désagrégation des différences et leur homogénéisation génétique lors d'un contact secondaire.

### Contexte de l'étude : le site d'étude à long terme de Paracou dans une forêt côtière du Bouclier guyanais

Toute l'étude de doctorat a été menée dans la station de terrain de Paracou (latitude 5°18'N et longitude 52°53'W), riche en biodiversité et en sciences, située dans la région côtière de la Guyane française. La topographie est caractérisée par des microconditions hétérogènes dues à de nombreuses petites collines ne dépassant généralement pas 45 m d'altitude. Une vieille forêt tropicale d'une richesse exceptionnelle pousse dans ce paysage à dominance de Fabaceae, Chrysobalanaceae, Lecythidaceae et Sapotaceae. Une expérimentation d'exploitation forestière a été lancée en 1984 avec douze parcelles de 9 hectares, puis trois parcelles de 6,25 hectares et une parcelle de 25 hectares non perturbée. Le diamètre des arbres à hauteur de poitrine a été recensé tous les 1 à 2 ans depuis 1984. Les arbres ont été cartographiés au mètre près et identifiés botaniquement, souvent au niveau de l'espèce. Le temps et le climat sont enregistrés en permanence grâce à une tour à flux. La pédologie et l'hydrologie ont été finement caractérisées pour plusieurs parcelles. Enfin, des campagnes LiDAR aéroportées ont été menées pendant plusieurs années à Paracou, ce qui a permis de caractériser avec précision la topographie et la structure des forêts. Cette accumulation de données environnementales de haute qualité dans un écosystème aussi riche sur le plan biologique a conduit à de nombreuses découvertes liées à la dynamique éco-évolutive de la biodiversité néotropicale. Par conséquent, la caractérisation fine de la diversité des forêts tropicales, des variations spatio-temporelles abiotiques et biotiques et de leurs relations éco-évolutives fait de Paracou un endroit parfait pour étudier la dynamique éco-évolutive d'espèces d'arbres tropicaux étroitement liées.

### Modèles d'étude : *Symphonia globulifera* et *Eschweilera* clade *Parvifolia*, deux complexes d'arbres localement abondants

*Symphonia globulifera* L. f. est une espèce d'arbre hypervariable pantropicale appartenant à la famille des Clusiacées. *S. globulifera* est répandu de la Guinée Bissau à la Tanzanie dans les paléotropiques africains et du Mexique au Brésil dans les néotropiques américains. *S. globulifera* présente une différenciation écotypique avec la topographie, avec deux morphotypes actuellement reconnus en Guyane française : *S. globulifera sensu stricto* qui pousse dans les bas-fonds inondés de façon saisonnière et *S. sp1* qui pousse sur les pentes et plateaux plus secs. 

*Eschweilera* est un genre hyper abondant appartenant à la famille des Lécythidacées. Les genres *Lecythis* et *Eschweilera* sont paraphylétiques et se composent de huit clades, dont le clade *Eschweilera* *Parvifolia.* Les espèces abondantes d’*Eschweilera* clade *Parvifolia* à Paracou sont *E. coriacea* (DC.) S.A.Mori, *E. sagotiana* Miers, et *E. decolorans* Sandwith. Comme les morphotypes de *Symphonia*, *E. sagotiana* et *E. coriacea* présentent une différenciation de niche en fonction de la topographie.

### Objectifs et plan général

Nous avons exploré la variabilité génétique intraspécifique comme un continuum au sein de populations structurées d'espèces étroitement apparentées, et mesuré son rôle sur la performance individuelle des arbres à travers la croissance dans le temps, tout en tenant compte des effets d'un environnement finement caractérisé au niveau abiotique et biotique. En combinant des inventaires forestiers, des données topographiques, des traits fonctionnels foliaires et des données de capture de gènes dans la station de recherche de Paracou, en Guyane française, nous avons utilisé la génomique des populations, les analyses d'associations environnementales et génomiques, et la modélisation bayésienne sur les complexes d'espèces *Symphonia* et *Eschweilera* clade *Parvifolia* pour répondre à la question générale suivante :

*Les génotypes et phénotypes individuels sont-ils adaptés aux environnements abiotiques et biotiques microgéographiques au sein et entre les espèces des complexes d'espèces ?*

Nous avons émis l'hypothèse que la variabilité génétique et phénotypique individuelle au sein des espèces et entre elles promeut la coexistence locale au sein des complexes d'espèces par le biais d'adaptations microgéographiques et d'un cloisonnement des niches à travers la topographie et la dynamique des trouées forestières.

## Chapitre 1 : La topographie façonne la coexistence locale des espèces d'arbres au sein des complexes d'espèces des forêts néotropicales

Dans cette étude, nous avons exploré la distribution à petite échelle de cinq complexes d'espèces et de 22 espèces au sein des complexes d'espèces. En combinant des inventaires forestiers, une détermination botanique de haute qualité et des données topographiques dérivées du LiDAR sur 120 ha de parcelles permanentes, nous avons utilisé un cadre de modélisation bayésien pour tester le rôle de la topographie à échelle fine et du voisinage des arbres sur la présence de complexes d'espèces et la distribution relative des espèces au sein des complexes.

Les complexes d'espèces d'arbres néotropicaux étaient largement répartis le long de la topographie à l'échelle locale. Les espèces au sein des complexes d'espèces ont montré une différenciation de niche marquée le long des gradients de position topographique, d’accumulation d'eau et de compétition. En outre, les préférences en matière d'habitat étaient coordonnées entre les espèces au sein de plusieurs complexes d'espèces : les espèces plus tolérantes à la compétition pour les ressources poussent sur des plateaux et des pentes plus secs et moins fertiles. S'ils sont soutenus par un isolement reproductif partiel des espèces et une introgression adaptative au niveau des complexes, nos résultats suggèrent que la spécialisation des habitats des espèces au sein des complexes d'espèces et la large distribution écologique des complexes d'espèces pourraient expliquer le succès de ces complexes d'espèces néotropicales à l'échelle régionale.

##  Chapitre 2 : La topographie entraîne systématiquement une variation intra- et inter-spécifique des traits foliaires au sein des complexes d'espèces d'arbres dans une forêt néotropicale

Nous avons examiné la variation des traits fonctionnels des feuilles en fonction de la topographie dans une forêt tropicale hyperdiversifiée du Bouclier guyanais. Nous avons collecté les traits fonctionnels des feuilles de 766 arbres appartenant à cinq espèces dans deux complexes d'espèces sur des parcelles permanentes englobant une diversité de positions topographiques. Nous avons testé le rôle de la topographie sur la variation des traits fonctionnels des feuilles à l'aide d'un modèle bayésien hiérarchique, en contrôlant l'effet du diamètre de chaque arbre.

Nous montrons que, à l'image de ce qui a été observé précédemment parmi les espèces et les communautés, les traits foliaires individuels varient d'une stratégie d'acquisition à une stratégie de conservation au sein des espèces. De plus, la diminution de l'humidité des bas-fonds aux plateaux a été associée à un changement des traits foliaires d'une stratégie d'acquisition à une stratégie conservatrice, à la fois au sein des espèces apparentées et entre elles. Nos résultats suggèrent que la variabilité des traits intraspécifiques élargit les niches des espèces et converge aux marges des espèces où les niches se chevauchent, impliquant potentiellement des processus locaux neutres. La variabilité des caractères intraspécifiques favorise l'adaptation locale et la divergence des espèces étroitement apparentées au sein des complexes d'espèces. Elle est potentiellement maintenue grâce au partage interspécifique de la variation génétique par hybridation.

## Chapitre 3 : La topographie est le moteur des adaptations microgéographiques des espèces proches dans deux complexes d'espèces d'arbres tropicaux

En combinant les données topographiques dérivées du LiDAR, les inventaires forestiers et les polymorphismes nucléotidiques simples (SNP) provenant d’expériences de capture de gènes, nous avons exploré la structure génétique des populations à l'échelle du génome, la covariation des variables environnementales et l'association génotype-environnement pour évaluer les adaptations microgéographiques à la topographie au sein des complexes d'espèces *Symphonia* et *Eschweilera*, avec trois espèces par complexe et respectivement 385 et 257 individus génotypés.

Au sein des complexes d'espèces, les espèces d'arbres étroitement apparentées ont des optima réalisés différents pour les niches topographiques définies par l'indice d'humidité topographique ou l'altitude relative, et les espèces présentaient des signatures génétiques d'adaptations. Les espèces de *Symphonia* sont différemment adaptées à la distribution de l'eau et des nutriments, tandis que les espèces d'*Eschweilera* évitent les sols hydromorphes et sont différemment adaptées à la chimie du sol.

Nos résultats suggèrent que la topographie représente un puissant moteur de la biodiversité des forêts tropicales, en favorisant des adaptations différentielles et en stabilisant la coexistence locale d'espèces d'arbres étroitement liées au sein de complexes d'espèces d'arbres.

## Chapitre 4 : La dynamique des trouées forestières : un facteur sous-exploré qui entraîne des stratégies de croissance adaptative divergentes au sein des espèces d'arbres tropicaux

La dynamique des trouées naturelles dues aux chutes d'arbres est l'un des principaux moteurs du fonctionnement des écosystèmes dans les forêts tropicales. Les arbres réagissent à la dynamique des trouées forestières par une grande variété de stratégies écologiques, mais ces stratégies ont longtemps été étudiées entre les espèces, négligeant la variabilité génétique au sein des espèces. Nous fournissons ici des preuves génétiques de diverses stratégies de croissance adaptative des individus au sein d'espèces d'arbres de forêts matures qui leur permettent de croître dans une diversité d'environnements de lumière et de compétition qui varient avec le temps depuis la dernière chute d'arbre. Nous montrons que la fine dynamique spatio-temporelle des trouées forestières est un facteur précédemment négligé qui, avec d'autres, contribue à maintenir au sein des espèces d’arbres tropicaux la diversité génétique, la matière première de l'évolution.

## Discussion

Malgré le rôle clé des complexes d'espèces dans l'écologie, la diversification et l'évolution des forêts néotropicales, on sait peu de choses sur les forces éco-évolutives qui créent et maintiennent la diversité au sein des complexes d'espèces néotropicales. Ici, nous avons montré que la topographie et la dynamique des trouées forestières entraînent des adaptations spatio-temporelles à échelle fine des individus au sein et entre des espèces distinctes mais génétiquement liées au sein des complexes d'espèces *Symphonia* et *Eschweilera* clade *Parvifolia.* Je suggère que les adaptations à la topographie et à la dynamique des trouées forestières favorisent la coexistence des individus au sein et entre les espèces des complexes d'espèces, et peut-être plus généralement entre les espèces d'arbres de forêts matures. Dans l'ensemble, je soutiens le rôle primordial des individus au sein des espèces dans la diversité des forêts tropicales, et suggère que nous devrions élaborer une théorie de l'écologie des communautés en commençant par les individus, car les interactions avec les environnements se produisent après tout au niveau de l’individu.
