# List of manuscripts

> [Chapter 1](#Ch1): **Sylvain Schmitt, Niklas Tysklind, Géraldine Derroire & Myriam Heuertz.** 
Topography shapes the local coexistence of tree species within species complexes of Neotropical forests.
Submitted to *Oecologia*.

> [Chapter 2](#Ch2). **Sylvain Schmitt, Bruno Hérault, Émilie Ducouret, Anne Baranger, Niklas Tysklind, Myriam Heuertz, Éric Marcon, 
Saint Omer Cazal, Géraldine Derroire. 2020.** 
Topography consistently drives intra- and inter-specific leaf trait variation within tree species complexes in a Neotropical forest.
*Oikos* **129**:1521-1530. doi 10.1111/oik.07488

> [Chapter 3](#Ch3). **Sylvain Schmitt, Niklas Tysklind, Géraldine Derroire & Myriam Heuertz.**
Topography drives microgeographic adaptations of closely-related species in two tropical tree species complexes.
Submitted to *New Phytologist*.

> [Chapter 4](#Ch4). **Sylvain Schmitt, Niklas Tysklind, Myriam Heuertz, Bruno Hérault.** 
Forest gap dynamics: an underexplored factor that drives divergent adaptive growth strategies within tropical tree species.
In preparation for *Proceedings of the National Academy of Sciences*.
