---
output:
  pdf_document: default
  html_document: default
---
# Discussion {#Discussion}

**Take home message.**

*We hypothesised individual genetic and phenotypic variability within and among species to promote local coexistence within species complexes through microgeographic adaptations to topography and forest gap dynamics.*

\newpage

## Topography and forest gap dynamics drive fine-scale spatio-temporal adaptations of individuals within and among species from two Neotropical species complexes.

### *Symphonia globulifera* and *Eschweilera* clade *Parvifolia* include distinct but connected species

We identified six distinct species in the two species complexes based on differences in morphologies, functional traits (chapter [2](#Ch2)), gene pools (chapter [3](#Ch3)), topographic niches (chapter [1](#Ch1)), and growth trajectories (A1); which were maintained despite the existence of an interspecific gene flow with hybridization (chapter [3](#Ch3)). 
Genetic analyses of population structure revealed the existence of three species growing in sympatry within the *Symphonia globulifera* species *sensu lato* (Fig. \@ref(fig:Ch3symphospecies)a),
previously recognized as structured in two morphotypes, *S. globulifera sensu stricto* and *S. sp.1* [@Ferry2007; @Molino2001; @Sabatier1997].
Similarly, genetic analyses of population structure revealed the existence of at least three abundant species of *Eschweilera* clade *Parvifolia* (Fig. \@ref(fig:Ch3parvispecies)), 
corresponding to the botanical species *Eschweilera coriacea*, *E. sagotiana*, and *E. decolorans*.
A lack of power in genomics data prevented us to detect less abundant species of *Eschweilera* clade *Parvifolia*. 
Species from the two species complexes showed distinct morphotypes (Fig. \@ref(fig:Ch3symphospecies)b), 
despite blur limits due to intermediate morphologies and ontegnetic effect on morphology.
Species showed pervasive niche differentiation along topography but to a lesser extent with competition (Fig. \@ref(fig:Ch1SpeciesDistribution) and Fig. \@ref(fig:Ch3SpDistVar)),
notably along a variation in the distribution of water and nutrients with topographic wetness index and relative elevation (Fig. \@ref(fig:Ch3soilpca)).
Niche differentiation between species is associated with a differentiation of functional traits (A1) and growth trajectories (A1).
Nevertheless, the overlap between species niches, functional traits and growth trajectories emphasizes the importance of individual variation within closely-related species within the two species complexes.
Finally, genetic analyses of population structure revealed interspecific gene flow with high level of hybridization in *Symphonia* species (around 5%, Fig. \@ref(fig:A4introgress)).
A lack of power in genomics data prevented us to explore gene flow in *Eschweilera* clade *Parvifolia*,
but previous studies already revealed interspecific hybridization [@Caron2019; @Heuertz2020].

### The history of Symphonia species in the Neotropics might be more complex than previously thought

*Symphonia globulifera* colonized the Americas from Africa ca 18-16 Ma [@Dick2015].
Despite, morphological variations and genetic differentiatin from 13 populations from Costa Rica, Panama, Ecuador, and French Guiana,
*S. globulifera* was never split in more than one Neotropical species [@Dick2008].
Our results are mainly limited to the local scale (chapter [3](#Ch3)), 
and further studies are needed on a broader regional scale, 
but they do support the definition of three distinct Neotropical taxonomic species of *Symphonia*.
Site frequency spectrum (SFS, A1) revealed population in expansion with an excess of rare alleles in each population,
congruent with previous studies[@Dick2008].

Moreover, genotyped outgroups of *Symphonia globulifera* were used to build a pantropical phylogeny of *Symphonia* populations using `treemix` [@Pickrell2012].
The phylogeny revealed a high likelihood of at least one migration event between *S. sp.1* and the two *S. globulifera* populations in Paracou (A1).
The phylogeny confirmed previous topology (S.C. González-Martínez pers. com.) with an ancestral population in Madagascar, 
and Sao Tome population as the intermediate population between African and American populations. 
Interestingly *S. sp1* was closer to the population of Brazil and the two *S. globulifera* populations were closer to the population of Costa Rica.
Our results suggest a possible more complex biogeographic history of *Symphonia globulifera*  in the Neotropics, 
but they call for further analyses before extrapolating.


### New insights in intraspecific trait variability advocate for their role in local adaptation and divergence of closely-related species

We found leaf functional strategy observed among species and communities to be conserved within species (Fig. \@ref(fig:Ch2PCA)).
Moreover, intraspecific leaf trait variability was consistently responding to topography between intra- and inter-specific level (Fig.  \@ref(fig:Ch2TWInNCI)).
Intraspecific trait variability thus widens species’ niches, 
with individual functionning better matching their environment along the niche [@Umana2019].
Intraspecific trait variability converges at species’ margins where niches overlap, 
potentially implying local neutral processes [@Hubbell2001] with a decrease in fitness differences [@Turcotte2016]. 
Interspecific gene flow with hybridization may maintain intraspecific trait variability through adaptive introgressions [@Tigano2016], thus favouring the whole syngameon.
But interspecific gene flow can also lead to transgressive rather than intermediate phenotypes [@Rieseberg2003], 
which can either hinder intraspecific variability at the shared margins of species or improve intraspecific variability at the extreme margins of species where species do not overlap.
Interspecific gene flow can also result in reproductive interference, discussed after,
with a risk for species to become an evolutionary melting pot.

### Ontogeny and plasticity can strongly impede the use of leaf functional traits 

I used genetic species, individual kinship, individual diameter at breast height, and plot to estimate genetic variance associated to functional traits (A1). 
Most of the variation was residual, associated to tree size, or to weather (illustrated by plot effect, see chapter 2 material and methods).
Species had a strong effect only on leaf area, obviously used to determine species.
Genotype effect was always null or non significant.
Measured leaf functional traits were thus mainly plastic and lacked adaptive signature.
Consequently, ontogeny, light access, topography and weather (A1, Schmitt et al. in prep) were the main drivers of functional traits variation from sampled leaves.
A strong trait intra-individual variation has already been highlighted on leaf thickness, transfusion tissue, and mass per area with leaf height within the tree [@Koch2004; @Oldham2010],
and on leaves vein density, stomatal pore index and hydraulic conductance with shoot length [@Leigh2011].
Moreover, functional traits had no or non-significant effect on individual growth potential (A1),
as already evidenced in the litterature [@Umana2019].

Functional traits have been defined as traits which impact fitness indirectly through their effect on performance [@violle_let_2007].
But my results do not suggest an adaptive signal, questioning the effect of measured functional traits on fitness, 
nor an effect on individual growth, questioning the effect of measured functional traits on individual performance.
This observation underline the need to control variation in leaf traits, 
including time, position, and ontogeny variation to represent the typical leaf functional strategy of an individual.
But is there a typical leaf functional strategy at the individual level?
Leaf functional traits may be mainly plastic and wide-proxies, not representative of individual functions and associated eco-evolutionary strategy, but may only represent one leaf functioning within individuals.

Nevertheless, my sampling within species can guide further sampling among species.
Resampling 5 mature individuals with a DBH > 30 cm, as advised in standard protocol [@Perez-Harguindeguy2013], 
I was able to show that estimation of the species mean trait value can vary from 5 to 15% percent (A1);
whereas increasing sampled individuals to 10 almost reduced of two folds the coefficient of variation from species mean trait value. 
In addition, improving ontogeny and habitat control in the sampling help better estimate species mean trait value.
I also advocate for an accurate sampling of individual leaf within the tree in future trait-based study of intraspecific variation,
controlling for instance architectural development stage and position of the sampled branch and leaf,
despite we recognize the tremendous work it represents.

### Topography drives species niche divergence

Pervasive niche differentiation along topography (Fig. \@ref(fig:Ch1SpeciesDistribution)) 
was driven by tree divergence and adaptation (Fig. \@ref(fig:Ch3SpDistVar)) 
within and among closely-related species within species complexes. 
*Symphonia* species specifically displayed genomic signatures of adaptations to water gradients along topography (chapter [3](#Ch3)).
In detail, species are adapted to the distribution of water and nutrients captured through the topographic wetness index and the relative elevation.
These results comfort the numerous examples of niche differentiation among closely-related species growing in sympatry, 
along fine-scale topography [@gunatilleke_specieshabitat_2006; @Engelbrecht2007; @kraft_functional_2008; @Allie2015],
and reveal possible adaptive forces at play behind these examples.
Adaptive radiations demonstrated along steep gradients [@Fine2004; @Paun2016] could thus occur at a fine spatial scale with gradual habitat variation.

### Forest gap dynamics maintain individual genetic diversity within species

*Symphonia* species can grow in a diversity of successional niches with genotypic adaptive growth strategies to fine spatio-temporal dynamics of forest gaps (Fig. \@ref(fig:Ch4gCor)).
Fast-growing genotypes grow in forest gaps, with high light access and low competition,
and slow-growing genotypes in shaded closed-canopy, with low light access and high competition.
Fine spatio-temporal dynamics of forest gaps contributes thus to maintaining tropical tree within-species genetic diversity (chapter [4](#Ch4)).

*Eschweilera* clade *Parvifolia* species showed also genotypic adaptations to individual neighbourhood crowding, 
an indirect measure of competition for light during the last three decades, and individual growth potential (A1).
But, I did not find the significant negative correlation observed between genotypic values for neighbourhood crowding and those for individual growth potential in *Symphonia*.
This lack of evidence could be due to methodolgical issues or *Eschweilera* ecology.
The few remaining sampled individuals after filtering out the missing genomic data showed a particular spatial structuring with neighbourhood crowding (absence of positive autocorrelation on a short scale), 
which the repeated random sampling of the same number of *Eschweilera* individuals did not reproduce.
In addition, the lack of individuals and the poor resolution of genomic data may have added noise and brought a lack of statistical power.
But, the ecology of *Eschweilera* is particular compared to that of *Symphonia* with a very slow growth varying little from one individual to another (A1).
Thus, *Eschweilera* could follow a different strategy to answer forest gap dynamics, 
as specialization for a specific succesional niche.
Or individual age is less related to diameter in *Eschweilera* than *Symphonia* due to slow growth, 
and may result in a greater decoupling of the current successional niche from the succesional niche at the time of recruitment of the individual.

## Do adaptations of tree species and individuals to topography and forest gap dynamics promote coexistence within and among species within species complexes ?

### Significance of species complexes and syngameons in Neotropical forests

We tried to delineate species complexes in the Paracou community based on evidence for low (phylo)-genetic resolution or plastid DNA sharing (chapter [1](#Ch1)).
We identified five species complexes belonging to Lecythidaceae, Chrysobalanaceae, Myristicaceae, Clusiaceae, and Sapindaceae 
[@baraloto_using_2012-1; @Caron2019; @Gonzalez2009; @Heuertz2020; @Huang2015; @Torroba-Balmori2017],
that illustrates the spread of species complexes in Angiosperms phylogeny.
But, all tropical tree species, genera, and families do not beneficiate of numerous genetic ressources and detailed phylogeny **[ref?]**.
Detailed genetic studies often detect cryptic species in widespread and abundant, supposedly well-known, tropical tree species, 
e.g. with *Symphonia* in chapter [3](#Ch3) or with the African flora [@Ewedje2020].
Consequently, knowledge of species complexes frequency and abundance in the Neotropics is thus limited.
However, the identified species complexes include locally abundant and hyperdominant regional species [@TerSteege2013], 
illustrating their significant role in the Neotropics.

Species complexes and syngameons role in the tropics is subject to debate [@Levi2019a; @Cannon2019; @Levi2019],
despite their recognized importance in South America [@Pinheiro2018].
@Levi2019 suggested that conspecifc density dependent processes were sufficient to explain the maintenance of tropical biodiversty.
@Cannon2019 responded by underlining the possible neglected role of syngameons to answer processes left out by @Levi2019.
Interestingly, @Levi2019a points to the lack of literature on syngaemons in tropical forests while recognizing their potential importance in maintaining biodiversity:
"virtually the entire literature on hybridization between tree species is based on temperate models, often at range boundaries or on steep environmental gradients".
Indeed, knowledge on syngameons is mainly concentrated on temperate forests, and even historically on oaks [@Cannon2019a].
However, chapter [1](#Ch1) to [3](#Ch3), together with previous litterature [@Pinheiro2018],
confirm the presence of syngameons in the Neotropics along subtle gradients, 
and a few studies in Paleotropics show or suggest syngaemons in plants [@Caujape-Castells2017],
fishes [@Seehausen2006] and even the *Homo* genus [@Holliday2006].
Lack of proof is not a proof of lack, this results challenges @Levi2019a claim.

### Species complexes widely spread across habitats include species with pervasive niche differentiation

Fine-scale topography variations drive differential adaptations of closely-related species within tree species complexes.
Topography promotes thus closely-related species coexistence through niche differentiation within tree species complexes.
Our genomic analyses were limited to *Symphonia* and *Eschweilera* clade *Parvifolia*, 
but we found similar niche partitioning in other species complexes from Paracou,
that suggests similar processes in other clades.
Indeed, chapter [1](#Ch1) and [3](#Ch3) suggest that the evolutive response is environmentally controlled, 
and should therefore be consistent outside of studied species complexes.
Pervasive effects of topography observed pantropically [@Allie2015; @Crystal2003; @Ferry2010; @kraft_functional_2008; @Lan2016], 
and related nutrients and water distribution [@Baldeck2013; @Baltzer2005a],
could drive differential adaptations between observed closely-related species, that promote their coexistence.
The evolutionary divergence could happen both in species complexes or more differentiated sister species.
Nevertheless, the evolutionary divergence seems more primordial in less differentiated species complexes [@Tobias2014],
with an increased risk of hybridization and consequent breakdown of inter-specific divergence;
while more differentiated sister species could also coexist through emerging neutrality [@Scheffer2006].

Forest gap dynamics, also identified as a driver of closely-related species niche differentiation [@Yamasaki2013], 
could drive differential adaptations among species in addition to its role in within-species variation.
The chapter [4](#Ch4) suggested a limited role of the successinoal niche in *Symphonia* species divergence (6%, Fig. \@ref(fig:Ch4VarPart).
But we found *Symphonia* to grow in a wide variety of successional niches (Fig. \@ref(fig:Ch4ncibreadth));
whereas species exploiting a specific niche in the succession, such as pioneers, could show more adaptive divergences among species.
Similarly, abundant species with a topographic wide niche should include within-species genotypic adaptations.
Indeed, the chapter [3](#Ch3) showed important genotypic varaition related to topography within species of *Eschweilera* clade *Parvifolia* (Fig. \@ref(fig:Ch3SpDistVar)). 
Consequently, abiotic environment with topography and biotic environment with forest gap dynamics are both driving within and amnog species tree adaptation and genetic diversity.

### Does the eco-evolutionary structure of Neotropical synagameons explain their local and regional success?

The local coexistence of closely-related species is governed by ecological and evolutionary processes, 
contingent on the history of speciation and niche differentiation [@Weber2016].
We focused on the competition for resources and the resulting niche differentiation in previous paragraphs [@Chesson2000; @Turcotte2016],
but reproductive isolation is primordial to explain closely-related species coexistence in sympatry [@Weber2016]. 
Species must have evolved sufficient reproductive isolation to avoid the break-down of differences and their genetic homogenization through reproductive interference [@Abbott2013; @Levin1996; @Taylor2006].
Phenology, e.g. flowering [@Gentry1974], or pollen dispersal, e.g. pollinators [@Kay2006], can increase reproductive isolation.

The way we perceive the role of genetic connectivity among species is changing, 
where species-specific adaptations may be maintained or even maximised despite high levels of gene flow, 
especially if selective pressures are spatially and/or temporally variable [@Tigano2016]. 
Species adaptations and partial reproductive isolation can be maintained despite gene flow through:
(i) linkage with an already diverged locus, 
(ii) increased resistance to gene flow following secondary contact, 
(iii) competition among genetic architectures and 
(iv) competition among genomic architectures, e.g. reducing recombination [@Tigano2016].
Consequently, adaptive introgression using gene flow among species diverging along environment may imply species coevolution, 
or evolutionary mutualism, at the syngameon level [@Cannon2019a].
Gene flow among species can insure reproductive assurance by hybridization, lowering the risk of local extinction,
and allow species to share innovation that benefits the whole syngameon [@Cannon2015b].
This subtle and maybe fragile equilibrium between species adaptations and gene flow may be a powerful eco-evolutionary strategy leading to local and regional success of tropical tree syngameons (*Symphponia* and *Eschweilera* include Amazonian hyperdominant tree species (Steege et al. 2013) and some of the most abundant species in Paracou).

### Do syngameons shape the exceptional diversity of Neotropical forests?

We found topography and forest gap dynamics to drive diversity within and among species within species complexes promoting their coexistence. 
I hypothesized syngameon to be a subtle and fragile but evolutionary successful stage, 
which raises the question of the temporal dynamics of syngameons.
Syngameons may not be restricted to transitions toward complete speciation of the species composing it,
but syngameons may represent a temporally stable stage [@Cannon2019a].
Reproductive isolation, although partial, can evolve very slowly to complete isolation with little selection against hybridization,
or hybridization could be favored during critical environmental disturbances.
If it represents a temporally stable stage, 
the *Symphonia* syngameon shows considerable gene flow (chapter [3](#Ch3)) despite a stable environment, 
which argues for the hypothesis of a slow evolution towards complete isolation.
Anyway, as a temporally stable stage or as a transitional stage toward complete speciation,
syngameons seems a successful evolutionary strategy promoting the coexistence of sympatric closely-related species.
Consequently, syngameons, and more generally species complexes, 
could play a key role in creating and maintaining the tremendous diversity of tropical forests 
by promoting the coexistence of phylogenetically and functionally similar species [@Cannon2019].
Syngameons could participate in the 'cradle' [@Eiserhardt2017] of the tropical forest with their speciation through complete reproductive isolation 
or in the tropical forest 'museum' [@Eiserhardt2017] with a temporal stability that reduces the risk of local extinction.

## Beyond species complexes: do adaptations to topography and forest gap dynamics promote coexistence within and among species from mature forests ?

### Intraspecific trait variation importance in the forest community

The chapter [2](#Ch2) revealed consistent functional response to topography within and between species, 
that suggest an environmental control of the response.
Topography similarly affects species complexes and fully differentiated species, 
so the functional response to topography within and between species should be consistent outside species complexes.
The only limit would be a specific role of shared genetic variation through gene flow or the recent ancestor conserving the signal in species complexes but not in fully differentiated species.
Indeed, once isolated species may lose genetic diversity and individual plasticity.
But the absence of effect of genotype on functional traits (A1) 
strongly questions the role of shared genetic variation in the consistent functional response,
unless observed trait plasticity is is genetically promoted [@Ghalambor2007] through recent divergence or inter-specific gene flow.
Therefore, I hypothesize that environmental gradients, 
such as topography and associated nutrient and water distributions (Chapter [3](#Ch3)), 
have a consistent effect on the variability of functional traits within and between species,
widening their niches and leading to an emerging neutrality in their overlap (Chapter [2](#Ch2)) 
for many species in the forest community.

### Fine-scale topography is a powerful driver of species diversity in tropical forests that promotes species coexistence

Chapter [1](#Ch1) to [3](#Ch3) revealed the effect of gradual habitat variation through fine-scale topography on ecological divergence of species through differentiation of niches and phenotypes.
But evolutive history behind adaptive radiations fall within a continuum from sympatric ecological speciation to secondary contacts of species ecologically specialised in allopatry or parapatry [@rundell_adaptive_2009].
Pairwise site frequency spectrum of *Symphonia* species (A1) did not helped decipher between sympatric speciation or character displacement after a secondary contact.
Demographic history modelling is still needed to establish the history of the evolution of *Symphonia* [@Hoban2012], 
but broader regional sampling may be necessary for a better understanding.
In both cases, it can be assumed that the extreme competition between species in hyperdiverse communities pushes species towards fine-scale habitat specialization along stable spatio-temporal environmental gradients.
Topography have been highlighted to drive early differences in plant's life, 
which contribute to the maintenance of ftropical forest diversity [@Metz2012].
Oppositely, spatio-temporally unstable forest gap dynamics contribute only a little to species differences (Chapter [4](#Ch4)).
Hence, fine-scale topography can locally represent a "species pump" in tropical forests, 
i.e. a cradle for the vicariance of species, such as the Andes on a regional scale [@Mutke2014].
Nevertheless, the species showed large topographic niches with overlaps in the Paracou community (chapter [2](#Ch2)),
which implies that neutral processes by decreasing differences in fitness also favour the coexistence of species via a jack-of-all-trade strategy [@Turcotte2016].
Topography could thus also give rise to "superspecies", i.e. allopatric taxa that are known or thought to have evolved to the species level [@Kleinschmidt1963].

### Forest gap dynamics are a powerful driver of individual diversity in tropical forests that promotes species coexistence

Chapter [4](#Ch4) showed for the first time that forest gap dynamics drive individual diversity and growth adaptations within *Symphonia* species.
Genetic adequacy with forest gap dynamics determines successful individuals reaching the canopy through divergent growth strategies, with *hares* in forest gaps and *turtles* in more shaded closed-canopy patches.
Because of the similar broad successional niches observed in many other species of the Paracou community, 
we hypothesized the process underlying genotypic adaptations not to be specific to *Symphonia* or species complexes, 
but to be conserved in many tropical forest tree species, 
probably thanks to physiological or adaptive constraints [@Ellner1994].
Nevertheless, phenotypic plasticity remains a major process that may explain large succesional niches of species [@Goulet1986; @Chevin2010; @Gao2018]
that we cannot exclude until further research is carried out.
In both cases, large successive niches can promote species coexistence through emergent neutrality [@Scheffer2006], 
although forest gap dynamics also select species with narrow successive niches such as pioneer species [@Dalling2002].
Interestingly, @Bazzaz1982 found late-successional species to be less plastic to light access than pioneer species,
and @Zangerl1983 revealed more adaptation among genotypes for late-successional than pioneer species.
Indeed, late-successional species showed the widest breadth of traits and grow in more heterogeneous environments than pioneers in Venezuela forests [@Kammesheidt2000].
Together with the results of chapter [4](#Ch4), these studies argue in favour of forest gap dynamics driving genotypic adaptations with divergent growth strategies in species previously called "late-successional", which in fact encounter a diversity of light environments and competition as seedlings.

In order to study treefall conditions, I examined the local basal area distribution prior to basal area loss,
i.e. the successional stage of the forest patch before a treefall occurs.
Unfortunately, studying treefalls necessitate both large spatial and temporal coverage du to the episodic nature of treefalls [@Chambers2013].
Despite the huge amount of work behind the monitoring of dynamics of the forest gaps at Paracou [@Herault2018],
I was not able to obtain a clear pattern.
Although most treefalls seem to occur when the local basal area is high, e.g. at the end of forest succession, also called climax, 
my results could not rule out the existence of treefalls occurring at a low local basal area during the early stages of succession (A1).
These early-succesion treefalls could be due to stochasticity,
but a bold hypothesis would be the existence of niche-hiking species that create these early-succesion treefalls.
Niche-hiking results from genotypes favoring local niche construction [@Schwilk2002],
such as flammability favouring open spaces after a fire for the offspring of fire-adapted trees.
In the case of treefall, one could imagine the existence of an adaptation to falls for genotypes or species that grow in forest gaps.
Indeed, one could imagine fast-growing genotypes or species in forest gaps are mechanically more prone to fall once in the canopy.
But, niche-hiking in forest gaps remain a bold hypothesis that needs to be tested further.

### Topography and forest gap dynamics joint effect on tropical diversity

We identified two orthogonal factors promoting diversity and coexistence among closely-related species with different characteristics and affecting different diversity levels.
Topography, spatio-temporally stable, mainly affect trees among species and promote coexistence with niche partitioning (Chapter [3](#Ch3)).
Forest gap dynamics, varying in space and time, mainly affect trees within species and promote coexistence with emergent neutrality (Chapter [4](#Ch4)).
Anticipating their joint effect on species coexistence and tropical diversity is therefore not straightforward,
while simulation approaches, discussed in the next section,
can help test hypotheses on a spatial and temporal scale that experimental studies on tropical forests cannot achieve.

* Why their joint effect should promote species coexistence and enhance the diversity of tropical forests?
* Why their joint effect should not promote species coexistence and enhance the diversity of tropical forests?
* Does scale matters [@Estes2018]

## Limits and future directions to address eco-evolutionary dynamics of tropical tree coexistence

### Stochasticity and neutrality are of paramount importance in merging ecology and evolution in a multidisciplinary approach

* From an ecological point of view, the partitioning of niches without the emergence of a neutral process prevents the full exploration of species coexistence.
* From an evolutive point of view, considering adaptations without drift and gene flow prevents the full exploration of species coexistence.
* At the crossroads of ecology and evolution, considering niche and emerging neutrality without reproductive isolation prevents the full exploration of species coexistence.
* Overall, the lack of appreciation or understanding of stochastic and neutral processes in ecology and/or evolution is an obstacle to the development of a good multidisciplinary approach, but may result from a deterministic teaching of both disciplines when simplifying the discourse.

### Limits of local low-cost capture to study the evolution of non-model species complexes in the wild

* Introduce “lococap“ project
* Brief technical issues (pre existing genomic resources, probes design, extraction, pool equilibrium, representativity, sequencing quality, SNP call, annotation)
* Genome duplications issues
* Study limits for population evolutionary history due to local sampling of widespread species without phylogeny and range-wide niche characterization 
* Limits in detecting adaptive introgression due to sampling and methodological development for sympatric study
* Limits in detecting GWAS, major effect SNPs and polygenic signal, due to sampling, population structure, and statistical power

### Promising directions in evolutionary studies of forest tree coexistence

* Microgeographic adaptations
* Genomics of forest gap dynamics
* Overlapping generations
* Eco-evolutionary spatio-temporal scales

### Simulation approaches to address the joint effect of topography and forest gap dynamics on the conditions for species coexistence and emergence

* Why simulations (M2 article)
* Develop what have been done in modelling chapter
* Further directions

### The primordial role of individuals within species in tropical forest diversity

* Clark’s works
* Individual variation, but not species, drives growth trajectories 
* Truc et al. on how considering species without individuals can blur processes
* Individual role in species adaptive and plastic response to topography and forest gap dynamics
* Advocate for merging population genomics and dynamics at the individual level
* Build a theory of community ecology starting with individuals, because interactions with environments are after all at the individual level (Violle et al.).
