```{r setupintro, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(tidyverse)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
# path <- "../../data/Paracou/"
```

# Introduction {-}

## Hypotheses to be tested

* **H0** Are species and/or genotypes structuring with topography and/or forest gap dynamics through time without evolution ?
    * One species with continuous genotypes with NCI only
    * Several species without genotypes with TWI only
    * The mix of the two
    * Test if a random starting distribution stucture with time
    * Test if an equelibirum is reached or if one species takes control
    * Test environmental parameters (spatial and time resolution)
* **H1** Can a forest gap dynamics genotype establish in a population through time with evolution ?
    * introduce new genotype or genotypic differentiation at time t with low frequency and observe under which parameters the genotypic adaptations gain weight in the population
* **H2** Can topography lead to ecological speciation ?
    * introduce new genotype or genotypic differentiation at time t with low frequency and observe under which parameters the genotypic adaptations get fixed between differgin populations
    
## Brainstormings

Here are the summary of inital brainstormings with Bruno.

### 20202/07/21

* For gaps dynamics article have a lokk to the dsitribution of $\Delta NCI$ for 10-20cm DBH individuals in 2017 of numerous abondant species in comparison with *Symphonia* species. Are they general or a cryptic case ?
* Why should we use growth ? For ligh acess, not modelled, and maturity, can be avoided. So migh be not useful..
* Explore links between treefalls growth and NCI/BA. Distribution of $\Delta NCI/BA < -XX \sim NCI_{init}$ wit BA on a 30x30m grid to see if it's bimodal. Is there mature forest treefalls and young forest treefalls pertained by nichhiking species/individuals creating treefalls ?
* Start from @Schwilk2002 model (but have a look to @Vincenzi2014), and define simple hypotheses to be tested with increasing complexity to define models need. For instance, H0 random genotypes strutur with environment without evolution before Hn with genotypic adaptations appearing or speciation events.

<!-- ## Outcomes -->

<!-- * Stability conditions -->
<!-- * Key factors (sensitivity analysis) -->
<!--     * topography vs forest gap dynamics on genotypic vs species structure -->
<!-- * System natural evolution under stable environment -->
<!-- * System answer to disturbances (CC) -->

