```{r setup_pca, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(tidyverse)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
# path <- "../../data/Paracou/"
```

# Introduction {-}

## Quick ideas

* TROLL for gaps only [@Chave1999; @Marechaux2017]
* SELVA to model growth directly
* Lotka-Voltera and spatial models of @Vellend2006a
* Overlapping generations of @Ellner1994
* Ordinary differential equations (ODE, possible in `stan` [see for instance](https://juliettearchambeau.github.io/BiogecoBayes/workshop6_ODE_SIR.html))

## Review

* Individual-based modeling of eco-evolutionary dynamics: state of the art and future directions [@Romero-Mujalli2019]
    * Individual based models simulate emerging processes from individual entities > what we need for individual genotypic evolution
    * few models with phenotypic plasticity
    * Plasticity as noise or reaction norm
    * Response to CC and lande use change > genetic adaptation, plasticity, shift of distribution or extinction
    * modelling for complex dynamics, complex experiments, endangered speices, or long generation times
    * Fussman et al. 2003 rotifers highly cited as an example of eco-evolutionary dynamics
    * Two categories: distribution models and procee-based models
    * Plasticity: epigenetics, maternal effects, environmental induction, acclimation, developmental plasticity, random noise
    * Plasticity: ontogenic & flexible
    * explicit or implicit genetics
    * three responses: dispersal, plasticity & adaptation
    * Local adaptation models often non-spatial
    * most of the time random mating but assortative mating for speciation
    * Implicit genetics based on the infiniesimal model has the advantage to simplify genetics while olding robust assumptions
    * Table 2 is perfect to select key-features of an eco-evolutionary individual based model:
        * Ecology:
            * Species nuber and interactions: closely-related species within a species complex with inter- and intra-specific competition
            * Time scale: year because of overlapping and long generations
            * Space: 2D explicit or non-spatial (more 2D for gaps dynamics)
            * Environmental feedback: yes for gaps dynamics
            * Reproduction: random mating with sexual species but hybridization ?
            * fitness: indirect through growth, survival and reproduction
        * Genetics: Implicit or explicit ?
        * Plasticity: 
            * Implementation: random noise or reaction norm ?
            * Costs: not explicit
            * Evolution: not included
* The consequences of genetic diversity in competitive communities [@Vellend2006a]
    * modified Lotka-Voltera model with competing species $m$ and genotyypes $i$ within species
    * genotypic richness and range determine the probability for a species to possess genetic variants to survive in an environment in face of multispecies competition
* genotypic richness decrease variation in community composition while increasing species diversity (sampling effect ?)

* RangeShifter: a platform for modelling spatial eco-evolutionary dynamics and species’ responses to environmental changes [@Bocedi2014]
* Individual heterogeneity in life histories and eco-evolutionary dynamics [@Vindenes2015]
* A road map for integrating eco-evolutionary processes into biodiversity models [@Thuiller2013]

## Questions

* stability
* key factors (sensitivity)
* evolution
* answer to disturbance (CC)

