---
title: Topography drives microgeographic adaptations among closely-related species of two tropical tree species complexes
author: Sylvain Schmitt, Niklas Tysklind, Bruno Herault, Myriam Heuertz
date: '`r Sys.Date()`'
output:
  bookdown::word_document2: default
  bookdown::html_document2:
    number_sections: false
linestretch: 1.5
csl: /home/sylvain/Documents/Bibliography/csl/molecol.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
always_allow_html: yes
---

* @Aarssen1983
* @Aguilos2018
* @Alexander2011
* @Allie2015
* @Anacker2014
* @Auwera2013
* @Balakrishnan2005
* @Baraloto2007
* @Bateman2019
* @Bolger2014
* @BroadInstitute2018
* @Brousseau2015
* @Budde2013
* @Cannon2015
* @Cannon2019
* @Cantet2004
* @Caron2019
* @Carpenter2017
* @Chakraborty2016
* @Chen2019
* @Connell1978
* @Conrad2015
* @Degen2004
* @DeLaCruz2014
* @Doran2013
* @Doyle1987
* @DeQueiroz2007
* @Eaton2020
* @Eckert2010
* @El-Gebali2019
* @Engelbrecht2007
* @Ewels2016
* @Ewedje2020
* @Ferry2010
* @Fine2004
* @Fine2014
* @Foll2008
* @Gaston2000
* @Gentry1988
* @Gerhold2015
* @Gompert2010
* @Gonzalez2009
* @Grant2019
* @Gourlet-Fleury2004
* @Gunatilleke2006
* @Haas2013
* @Heuertz2020
* @Herault2018
* @Hoffman2014
* @Huang2015
* @Itoh2003
* @John2007
* @Johnson2010
* @Kent2002
* @Kraft2008
* @Kursar2009
* @Leroy2019
* @Li2009
* @Li2009a
* @Lortie2004
* @Manichaikul2010
* @Molino2001
* @Mori1987
* @Mori1990
* @Mori2016
* @Mutke2014
* @Nakagawa2013
* @Nishio2019
* @Olsson2017
* @Paun2016
* @Pernes1984
* @Petit2002
* @Pillon2014
* @Pinheiro2018
* @Quinlan2010
* @RCoreTeam2020
* @Rellstab2015
* @Roelens2007
* @Ruger2009
* @Rundell2009
* @Runemark2019
* @Sabatier1997
* @Scheffer2006
* @Schmitt2020a
* @Schmitt2020
* @Seehausen2004
* @Smit2015
* @Soucemarianadin2004
* @StanDevelopmentTeam2018
* @States1994
* @terSteege2013
* @terSteege2019
* @Suarez-Gonzalez2018
* @Tigano2016
* @Tobias2014
* @Torroba-Balmori2017
* @Turcotte2016
* @Vargas2019
* @Weiher1995
* @Whitney2010
* @Wiens2010
* @Wilson2010
* @Yamasaki2013
