---
output:
  bookdown::html_document2:
    number_sections: false
    toc: no
    toc_float: no
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
  bookdown::word_document2:
    reference_docx: ./template/template.docx
linestretch: 1.5
---

# Intructions

## Molecular Ecology

**Your cover letter should contain a clear statement of how your manuscript fits the scope of the journal.**

Molecular Ecology publishes papers that utilize molecular genetic techniques to address consequential questions in ecology, evolution, behaviour and conservation.

Studies may employ neutral markers for inference about ecological and evolutionary processes or examine ecologically important genes and their products.

Papers that are primarily descriptive and relevant only to the taxon being studied without addressing a question of broader interest to the fields of ecology, evolution, or conservation are not appropriate for Molecular Ecology and should instead be submitted to a more specialized journal or to Ecology & Evolution / MicrobiologyOpen.

Research areas of interest to Molecular Ecology include:

* ecological, evolutionary, and population genomics 
* population structure and phylogeography
* landscape genomics
* community ecology and coevolution
* reproductive strategies
* relatedness and kin selection
* sex allocation
* population genetic theory
* analytical methods development
* conservation genetics
* speciation and hybridization
* microbial biodiversity
* evolutionary dynamics of ecologically important genes or QTLs
* ecological interactions
* molecular adaptation and environmental genomics
* impact of genetically modified organisms

## New Phytologist

Authors should include answers to the following questions (max. 50 words per question) in a covering letter, to help the Editors decide whether to send the manuscript for peer review:

* What hypotheses or questions does this work address?
* How does this work advance our current understanding of plant science?
* Why is this work important and timely?


# Cover letter

Sylvain Schmitt
69, route d’Arcachon
33610 Cestas, France

Jully XX, 2020

**Object**: Submission of a manuscript to Molecular Ecology

Dear Editor,

<!-- We would like to submit an original research article entitled “Topography shapes the local coexistence of tree species within species complexes of Neotropical forests” for consideration to publish in Oecologia. In this manuscript, we present an original research addressing the effect of topography on the distribution of species complexes and the local coexistence of species within species complexes based on a large inventories of 22 species within 5 species complexes associated to fine-scale topographic and neighbor crowding data.  -->

<!-- Lowland Amazonia includes numerous species-rich tree genera sharing a large amount of genetic variation either because of recent common ancestry and/or recurrent hybridization, forming species complexes. Despite the key role that species complexes play  in understanding Neotropical diversification, and the need for exploiting a diversity of niches for species complexes to thrive, little is known about local coexistence of Neotropical species complexes in sympatry. Combining full forest inventories, high-quality botanical determination, and LiDAR-derived topographic data over 120ha of permanent plots, we used a Bayesian modelling framework to test the role of fine-scale topography and tree neighbourhood on the presence of species complexes and the relative distribution of species within complexes. Species complexes of Neotropical trees were widely spread across topography at the local-scale, while species within species complexes showed pervasive niche differentiation along topographic position, water accumulation, and competition gradients. Our results suggest that both habitat specialisation of species within species complexes and the broad ecological distribution of species complexes might explain the success of these Neotropical species complexes at the regional scale -->

<!-- We believe that this manuscript would be a valuable contribution to Oecologia and attract a large readership as our results contribute to shed some light on species coexistence within the understudied Neotropical species complexes. -->

We have no conflicts of interest to disclose. 

Thank you for your consideration.

Sincerely,

Sylvain Schmitt,
on behalf of the co-authors

