---
output:
  bookdown::html_document2:
    number_sections: false
    toc: no
    toc_float: no
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
  bookdown::word_document2:
    reference_docx: ./template/template.docx
linestretch: 1.5
---

<!-- Authors should include answers to the following questions (max. 50 words per question) in a covering letter, to help the Editors decide whether to send the manuscript for peer review: -->

<!-- * What hypotheses or questions does this work address? -->
<!-- * How does this work advance our current understanding of plant science? -->
<!-- * Why is this work important and timely? -->

Sylvain Schmitt
69, route d’Arcachon
33610 Cestas, France

Jully XX, 2020

**Object**: Submission of a manuscript to Molecular Ecology

Dear Editor,

We would like to submit an original research article entitled “Topography drives microgeographic adaptations among closely-related species of two tropical tree species complexes” for consideration to publish in *New Phytologist*.

In this manuscript, we present original research on the effect of topography on genetic adaptations and niche differentiation among closely related species, based on a large sample of 663 trees belonging to six species and two species complexes associated with fine-scale topographic data and genomic markers from a gene capture experiment.

Our study suggests that species adaptations to different characteristics of topography stabilize local coexistence between closely-related species within tree species complexes. Combined with the literature, our results question the possible role of topography in the genetic adaptation and diversification of tropical tree species complexes, and more broadly in the origin and maintenance of Neotropical forest diversity.

*New Phytologist* has recently published a special issue on the oak tree, perhaps the best known syngameon, but little is known about syngameons in tropical forests. Therefore, we believe that this manuscript would be timely and attract a wide audience, as our results help to shed light on the adaptive basis of species coexistence within tropical species complexes.

We have no conflicts of interest to disclose. 

Thank you for your consideration.

Sincerely,

Sylvain Schmitt,
on behalf of the co-authors

