---
title: "FTH project"
date: '`r Sys.Date()`'
output:
  bookdown::html_document2:
    number_sections: false
    toc: true
    toc_float: yes
---

```{r setup, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(tidyverse)
library(knitr)
library(kableExtra)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = T, message = F, warning = F, fig.height = 6, fig.width = 6,
  cache = T, cache.lazy = F)
```


```{r data}
individual <- googlesheets::gs_title("Measures Eschweilera FTH") %>%
  googlesheets::gs_read("Individual") %>% 
  filter(!is.na(IdGenetic))
traits <- googlesheets::gs_title("Measures Eschweilera FTH") %>%
  googlesheets::gs_read("Measures")
LA <- googlesheets::gs_title("Measures Eschweilera FTH") %>%
  googlesheets::gs_read("Surface folliaire")
data <- individual %>% 
  left_join(traits) %>% 
  mutate(Fresh_Weight = as.numeric(Fresh_Weight))
```

# Data cleaning

```{r all}
data <- googlesheets::gs_title("data_complete") %>%
  googlesheets::gs_read("data_complete")
```

## Individuals

```{r ind}
data %>% 
  dplyr::select(Date, Time, Plot, SubPlot, FieldTreeNum,
         Dawkins, Position, `Trunk form`)
summary(as.factor(data$Position))
names(data)
```

# Adding missing individuals

```{r setup}
path <- "~/Documents/BIOGECO/PhD/data/Eschweilera_Paracou/Measures/"
```


```{r FTH}
read_delim(file.path("~/Documents/BIOGECO/PhD/data/Eschweilera_Paracou/Measures/",
                     "data_FTH.csv"), delim = ",") %>% 
  mutate(CodeParacou = paste0("P", Plot, "-", SubPlot, "-", FieldTreeNum)) %>% 
  select(CodeParacou) %>% 
  unique() %>% 
  bind_rows(read_delim(file.path("~/Documents/BIOGECO/PhD/data/Eschweilera_Paracou/Measures/",
                                 "Indviduals.csv"), delim = ",") %>% 
              mutate(CodeParacou = paste0("P", Plot, "-", SubPlot, "-", FieldTreeNum)) %>% 
              select(CodeParacou)) %>% 
  arrange(CodeParacou)
```

We already collected 294 individuals. We still have to collect :

* 28 ind in P11
* 93 ind in P6

Consequently we have 25 individuals to replace.

# Data preparation

## Leaf attribution in LA

```{r LAsummary}
LA %>% 
  select(commentaire) %>% 
  group_by(commentaire) %>% 
  summarise(n = n()) %>% 
  kable()
```

```{r LA}
LA <- LA %>% 
  separate(Label, c("Plot", "SubPlot", "FieldTreeNum"), 
           "-", convert = T) %>% 
  mutate(Plot = as.numeric(gsub("P", "", Plot))) %>% 
  mutate(FieldTreeNum0 = FieldTreeNum) %>% 
  mutate(FieldTreeNum = as.numeric(gsub('([[:alpha:]])', "", FieldTreeNum0))) %>% 
  mutate(Scan = gsub('[0-9]+', "", FieldTreeNum0)) %>% 
  select(-FieldTreeNum0) %>% 
  arrange(Plot, SubPlot, FieldTreeNum, Area_exclude) %>% 
  group_by(Plot, SubPlot, FieldTreeNum) %>% 
  mutate(Leaf_order = (1:6)[1:n()])
data <- data %>% 
  arrange(Plot, SubPlot, FieldTreeNum, Fresh_Weight) %>% 
  group_by(Plot, SubPlot, FieldTreeNum) %>% 
  mutate(Leaf_order = (1:6)[1:n()])
data <- data %>% 
  left_join(LA)
data %>% 
  write_csv("./data.csv")
```

## Environmental data

```{r}
# # General
# library(raster)
# library(parallel)
# path <- "~/Documents/BIOGECO/PhD/data/Paracou/"
# crs <- '+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0' # global crs definition
# # Trees
# individual <- googlesheets::gs_title("data_complete") %>%
#   googlesheets::gs_read("data_complete") %>% 
#   mutate(TreeFieldNum = FieldTreeNum) %>% 
#   dplyr::select(IdGenetic, Plot, SubPlot, TreeFieldNum) %>% 
#   unique()
# trees <- src_sqlite(file.path(path, "trees/Paracou.sqlite")) %>% 
#   tbl("Paracou") %>% 
#   filter(Genus == "Eschweilera") %>% 
#   filter(Plot %in% 15:16) %>% 
#   filter((Plot == 16 & CensusYear == 2015) | (Plot == 15 & CensusYear == 2017)) %>% 
#   collect() %>% 
#   mutate(DBH = CircCorr*pi)
# data <- individual %>% 
#   left_join(trees, by = c("Plot", "SubPlot", "TreeFieldNum"))
# coordinates(data) <- ~Xutm + Yutm
# proj4string(data) <- '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0'
# # BA
# cl <- makeCluster(4)
# clusterExport(cl, list("data", "path"))
# Competition <- clusterMap(cl,
#   function(id, plot, year, x, y){
#   library(dplyr)
#   src_sqlite(file.path(path, "trees/Paracou.sqlite")) %>%
#     tbl("Paracou") %>%
#     filter(CensusYear == year) %>%
#     filter(Plot == plot) %>%
#     filter(idTree != id) %>%
#     mutate(DBH = CircCorr*pi) %>%
#     mutate(dij = sqrt((x - Xutm)^2+(y - Yutm)^2)) %>%
#     filter(dij < 20) %>%
#     mutate(idTree = id) %>% 
#     dplyr::select(idTree, DBH) %>%
#     collect()},
#   id = data$idTree,
#   plot = data$Plot,
#   year = data$CensusYear,
#   x = data$Xutm,
#   y = data$Yutm,
#   SIMPLIFY = F)
# stopCluster(cl)
# rm(cl)
# Competition <- bind_rows(Competition)
# # Gaps
# gaps <- shapefile(file.path(path, "topography", "Gaps", "gaps4.shp"))
# crs(gaps) <- crs(raster(file.path(path, "biotic", "MNC_ParacouAvril2009_1m.tif")))
# gaps <- spTransform(gaps, '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0')
# cl <- makeCluster(4)
# clusterExport(cl, list("data", "gaps"))
# Gaps <- clusterMap(cl,
#   function(id,  x, y){
#     d <- 50
#     gaps_sel <- raster::crop(rgeos::gBuffer(gaps, byid=TRUE, width=0),
#                              raster::extent(matrix(c(x-d, y-d, x+d, y+d), nrow=2)))
#     tree <- data.frame(x = x, y = y)
#     sp::coordinates(tree) <- ~x+y
#     raster::crs(tree) <-  '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0'
#     if(!is.null(gaps_sel))
#       data.frame(idTree = id,
#                  idGap = gaps_sel$fid,
#                  Area = raster::area(gaps_sel),
#                  Distance = rgeos::gDistance(tree, gaps_sel, byid = T)[,1])
#     },
#   id = data$idTree,
#   x = data$Xutm,
#   y = data$Yutm,
#   SIMPLIFY = F)
# stopCluster(cl)
# rm(cl)
# Gaps <- bind_rows(Gaps)
# # TWI
# data <- spTransform(data, CRSobj = crs)
# TWI <- raster(file.path(path, "topography", "TWI_1m.tif"))
# # Env
# data <- data@data %>% 
#   left_join(data.frame(
#   IdGenetic = data$IdGenetic,
#   DBH = data$DBH,
#   TWI = extract(TWI, data),
#   BA = Competition %>% 
#     group_by(idTree) %>% 
#     summarise(BA = sum(DBH)) %>% 
#     dplyr::select(BA) %>% 
#     unlist(),
#   Gaps = Gaps %>% 
#     full_join(data@data) %>% 
#     mutate(Distance = ifelse(is.na(Distance), 100, Distance)) %>% 
#     group_by(idTree) %>% 
#     summarise(Distance = min(Distance)) %>% 
#     dplyr::select(Distance) %>% 
#     unlist()))
# write_csv(data, "./data_environment.csv")
data <- read_csv("./data_environment.csv")
```

```{r graph}
data %>% 
  left_join(googlesheets::gs_title("data_complete") %>%
  googlesheets::gs_read("data_complete"), by = "IdGenetic") %>% 
  mutate(Gaps = log(Gaps)) %>% 
  dplyr::select(Species, 
                SLA, LT, LDMC, CC, Area_exclude,
                DBH, BA, Gaps, TWI) %>% 
  reshape2::melt(id.vars = c("Species", "SLA", "LT", "LDMC", "CC", "Area_exclude")) %>% 
  reshape2::melt(id.vars = c("Species", "variable", "value"),
                 variable.name = "Trait", value.name = "Trait.value") %>% 
  mutate(Trait.value = as.numeric(Trait.value)) %>% 
  na.omit() %>% 
  ggplot(aes(value, Trait.value, col = Species, group = NA)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(Trait~variable, scales = "free")
```

```{r table}
traits <-  googlesheets::gs_title("data_complete") %>%
  googlesheets::gs_read("data_complete") %>% 
  dplyr::select(Espece, IdGenetic,
                SLA, LT, LDMC, CC, Area_exclude) %>% 
  group_by(Espece, IdGenetic) %>% 
  mutate(CC = as.numeric(CC)) %>% 
  summarise_all(mean)
data %>% 
  left_join(traits) %>% 
  dplyr::select(Species, 
                SLA, LT, LDMC, CC, Area_exclude,
                DBH, BA, Gaps, TWI) %>% 
  reshape2::melt(id.vars = c("Species", "DBH", "BA", "Gaps", "TWI"),
                 variable.name = "Trait") %>% 
  mutate(value = as.numeric(value)) %>% 
  na.omit() %>% 
  group_by(Trait) %>% 
  do(lm = lm(value ~ DBH + BA + Gaps + TWI, data = .)) %>% 
  broom::tidy(lm) %>% 
  mutate(pval = ifelse(p.value < 0.001, "***", 
                       ifelse(p.value < 0.01, "**", 
                              ifelse(p.value < 0.05, "*",
                                     ifelse(p.value < 0.1, ".", "n.s."))))) %>% 
  mutate(estimate = round(estimate, 2)) %>% 
  mutate(value = paste(estimate, pval)) %>% 
  mutate(value = cell_spec(value, bold = ifelse(p.value < 0.1, T, F))) %>% 
  reshape2::dcast(Trait~term, fill = "value") %>% 
  rename(Intercept = `(Intercept)`) %>% 
  dplyr::select(Trait, Intercept, DBH, TWI, BA, Gaps) %>% 
  kable()
```


