#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
if (length(args)==0)
  stop("At least one argument must be supplied (simulation number).n", call.=FALSE)
chain <- as.numeric(args[1])
trait <- as.character(args[2])
print(paste("Chain number is", chain))
print(paste("Trait is", trait))
load("../symcapture_save/dataFT.Rdata")
library(rstan)
options(mc.cores = 1)
rstan_options(auto_write = T)
model <- stan_model("../symcapture_models/FTGeno.stan")
fit <- sampling(model, chains = 1, data = mdata[[trait]], save_warmup = F,
                     control = list(adapt_delta = 0.99, max_treedepth = 12))
save(fit, file = paste0("../symcapture_save/FTGeno/", trait, ".chain", chain, ".Rdata"))
