#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
if (length(args)==0)
  stop("At least one argument must be supplied (simulation number).n", call.=FALSE)
sim <- as.numeric(args[1])
print(paste("Simulation number is", sim))
load("../symcapture_save/growthgenoData.Rdata")
print(paste("Simulation is", names(mdata)[sim]))
library(rstan)
options(mc.cores = 2)
rstan_options(auto_write = T)
growthgeno <- stan_model("../symcapture_models/GrowthGeno.stan")
fit <- sampling(growthgeno, chains = 2, data = mdata[[sim]]$mdata, save_warmup = F, init = "0",
                     control = list(adapt_delta = 0.99, max_treedepth = 12))
save(fit, file = paste0("../symcapture_save/growthgeno/growthgeno", sim, ".Rdata"))
