```{r setup_NCI, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(kableExtra)
library(parallel)
library(tidyverse)
library(ggfortify)
library(raster)
library(leaflet)
library(rstan)
library(bayesplot)
library(factoextra)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 6,
  cache = T, cache.lazy = F)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
path <- "~/Documents/BIOGECO/PhD/data/Paracou/"
crs <- '+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0' # global crs definition
```

```{r trees_NCI}
complexes <- bind_rows(
  data.frame(Complex = "Chartacea", Genus = "Eschweilera",
             Species = c("simiorum", "congestiflora")),
  data.frame(Complex = "Parvifolia", Genus = "Eschweilera",
             Species = c("pedicellata", "coriacea", "decolorans", "sagotiana",
                         "wachenheimii", "grandiflora_form2")),
  data.frame(Complex = "Licania", Genus = "Licania",
             Species = c("alba", "membranacea", "canescens", "micrantha",
                         "ovalifolia", "sprucei", "densiflora",
                         "laxiflora", "parvifructa")),
  data.frame(Complex = "Iryanthera", Genus = "Iryanthera",
             Species = c("hostmannii", "sagotiana")),
  data.frame(Complex = "Talisia", Genus = "Talisia",
             Species = c("hexaphylla", "praealta", "simaboides")),
  data.frame(Complex = "Symphonia", Genus = "Symphonia",
             Species = c("globulifera", "sp.1")))
d <- 20
individuals <- src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>% 
  tbl("Paracou") %>% 
  filter(Plot == 1) %>% # for test purposes
  filter(CensusYear == 2015) %>%
  filter(Genus %in% local(complexes$Genus)) %>% 
  collect() %>% 
  left_join(complexes) %>% 
  filter(!is.na(Complex)) %>% 
  filter(Xfield > d, Xfield < 250-d, Yfield > d, Yfield < 250-d) %>% 
  mutate(DBH = CircCorr/pi)
```

```{r competitionNCI, eval=F}
cl <- parallel::makeCluster(getOption("cl.cores", 4))
parallel::clusterExport(cl, list("path", "individuals"))
NCIt <- parallel::parLapply(cl, 1:nrow(individuals), function(ind){
  library(tidyverse)
  src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>% 
    tbl("Paracou") %>% 
    filter(Plot == local(individuals[ind,]$Plot)) %>% 
    filter(idTree != local(individuals[ind,]$idTree)) %>% 
    mutate(dij = sqrt((local(individuals[ind,]$Xutm) - Xutm)^2+(local(individuals[ind,]$Yutm) - Yutm)^2)) %>% 
    filter(dij < 20) %>% 
    mutate(con = ifelse(Genus == local(individuals[ind,]$Genus) && Species == local(individuals[ind,]$Species), 1, 0)) %>% 
    mutate(DBH = CircCorr/pi) %>% 
    collect() %>% 
    arrange(CensusYear) %>% 
    summarise(idTree = local(individuals[ind,]$idTree),
              NCIcon = sum(DBH*DBH*exp(-0.25*dij)*con)/(last(CensusYear) - first(CensusYear)),
              NCIhetero = sum(DBH*DBH*exp(-0.25*dij)*(1-con))/(last(CensusYear) - first(CensusYear)))})
dNCIt <- parallel::parLapply(cl, 1:nrow(individuals), function(ind){
  library(tidyverse)
  src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>% 
  tbl("Paracou") %>% 
  filter(Plot == local(individuals[ind,]$Plot)) %>% 
  filter(idTree != local(individuals[ind,]$idTree)) %>% 
  mutate(dij = sqrt((local(individuals[ind,]$Xutm) - Xutm)^2+(local(individuals[ind,]$Yutm) - Yutm)^2)) %>% 
  filter(dij < 20) %>% 
  mutate(con = ifelse(Genus == local(individuals[ind,]$Genus) && Species == local(individuals[ind,]$Species), 1, 0)) %>% 
  mutate(DBH = CircCorr/pi) %>% 
  group_by(CensusYear) %>% 
  summarise(idTree = local(individuals[ind,]$idTree),
            NCIcon = sum(DBH*DBH*exp(-0.25*dij)*con),
            NCIhetero = sum(DBH*DBH*exp(-0.25*dij)*(1-con))) %>% 
  arrange(CensusYear) %>% 
  collect() %>% 
  mutate(dNCIcon = NCIcon - lag(NCIcon), 
         dNCIhetero = NCIhetero - lag(NCIhetero), 
         dt = CensusYear - lag(CensusYear)) %>% 
  na.omit() %>% 
  ungroup() %>% 
  summarise(dNCIRcon = sum(dNCIcon)/sum(dt),
            dNCIRhetero = sum(dNCIhetero)/sum(dt))})
NCI <- parallel::parLapply(cl, 1:nrow(individuals), function(ind){
  library(tidyverse)
  src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>% 
    tbl("Paracou") %>% 
    filter(CensusYear == 2015) %>%
    filter(Plot == local(individuals[ind,]$Plot)) %>% 
    filter(idTree != local(individuals[ind,]$idTree)) %>% 
    mutate(dij = sqrt((local(individuals[ind,]$Xutm) - Xutm)^2+(local(individuals[ind,]$Yutm) - Yutm)^2)) %>% 
    filter(dij < 20) %>% 
    mutate(con = ifelse(Genus == local(individuals[ind,]$Genus) && Species == local(individuals[ind,]$Species), 1, 0)) %>% 
    mutate(DBH = CircCorr/pi) %>% 
    collect() %>% 
    summarise(idTree = local(individuals[ind,]$idTree),
              NCIcon = sum(DBH*DBH*exp(-0.25*dij)*con),
              NCIhetero = sum(DBH*DBH*exp(-0.25*dij)*(1-con)))})
parallel::stopCluster(cl) ; rm(cl)
NCIt <- bind_rows(NCIt)
dNCIt <- bind_rows(dNCIt)
NCI <- bind_rows(NCI)
save(NCIt, dNCIt, NCI, file = "./distribution_save/NCIt.Rdata")
```

# NCI in time

$$NCI_{2015} = \sum _{j|\delta_{i,j}<20m} ^{J_i} DBH_j ^2 . e^{-\frac{1}{4}\delta_{i,j}}$$
$$NCI_t = (\int_{t_0} ^{2015} \sum _{j|\delta_{i,j}<20m} ^{J_{i,t}} DBH_{j,t} ^2 . e^{-\frac{1}{4}\delta_{i,j}}.dt). \frac{1}{\Delta t}$$
$$ANCIR_t = (\int_{t_0+1} ^{2015} \frac{\sum _{j|\delta_{i,j}<20m} ^{J_{i,t}} DBH_{j,t} ^2 . e^{-\frac{1}{4}\delta_{i,j}}t}{\sum _{j|\delta_{i,j}<20m} ^{J_{i,t}} DBH_{j,t-1} ^2 . e^{-\frac{1}{4}\delta_{i,j}}}.dt). \frac{1}{\Delta t}$$


```{r}
load(file = "./distribution_save/NCIt.Rdata")
NCIt %>% 
  reshape2::melt(id.vars = c("idTree"), value.name = "NCIt") %>% 
  left_join(NCI %>% 
              reshape2::melt(id.vars = c("idTree"), value.name = "NCI2015")) %>% 
  left_join(individuals) %>% 
  ggplot(aes(NCI2015, NCIt)) +
  geom_abline(slope = 1, intercept = 1, linetype = "dashed") +
  geom_smooth(method = "lm") +
  geom_point(aes(col = Species)) +
  facet_wrap(~ variable, scales = "free") +
  scale_color_discrete(guide = "none")
NCIt %>% 
  dplyr::rename(NCIcont = NCIcon, NCIheterot = NCIhetero) %>% 
  left_join(dplyr::rename(NCI, NCIcon2015 = NCIcon, NCIhetero2015 = NCIhetero)) %>% 
  dplyr::select(-idTree) %>% 
  cor() %>% 
  corrplot::corrplot.mixed()
```

```{r}
load(file = "./distribution_save/NCIt.Rdata")
dNCIt %>% 
  mutate(idTree = NCI$idTree) %>% 
  dplyr::rename(NCIcon = dNCIRcon, NCIhetero = dNCIRhetero) %>% 
  reshape2::melt(id.vars = c("idTree"), value.name = "dNCIt") %>% 
  left_join(NCI %>% 
              reshape2::melt(id.vars = c("idTree"), value.name = "NCI2015")) %>% 
  left_join(individuals) %>% 
  ggplot(aes(NCI2015, dNCIt)) +
  geom_smooth(method = "lm") +
  geom_point(aes(col = Species)) +
  facet_wrap(~ variable, scales = "free") +
  scale_color_discrete(guide = "none")
dNCIt %>% 
  mutate(idTree = NCI$idTree) %>% 
  left_join(dplyr::rename(NCI, NCIcon2015 = NCIcon, NCIhetero2015 = NCIhetero)) %>% 
  dplyr::select(-idTree) %>% 
  cor() %>% 
  corrplot::corrplot.mixed()
dNCIt %>% 
  mutate(idTree = NCI$idTree) %>% 
  left_join(individuals) %>% 
  ggplot(aes(dNCIRhetero, fill = Species)) +
  geom_histogram(position = "dodge") +
  facet_wrap(~ Complex, scales = "free") +
  scale_fill_discrete(guide = "none")
dNCIt %>% 
  mutate(idTree = NCI$idTree) %>% 
  left_join(individuals) %>% 
  ggplot(aes(dNCIRcon, fill = Species)) +
  geom_histogram(position = "dodge") +
  facet_wrap(~ Complex, scales = "free") +
  scale_fill_discrete(guide = "none")
```

