---
output:
  html_document: default
  pdf_document: default
---
```{r setup_growth, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(rstan)
library(bayesplot)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 8, fig.width = 8,
  cache = T, cache.lazy = F)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
path <- "../../data/Paracou/"
```

```{r data_growth}
d <- 20
trees <- src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>% 
  tbl("Paracou") %>% 
  filter(CensusYear == 2015) %>%
  filter(Xfield > d, Xfield < 250-d, Yfield > d, Yfield < 250-d) %>% 
  filter(Species != "Indet.") %>% 
  mutate(DBH = CircCorr/pi) %>% 
  collect()
load("./distribution_save/env.Rdata")
load("./distribution_save/Competition.Rdata")
Competition <- Competition %>% 
  mutate(dij = ifelse(dij <1, 1, dij)) %>% 
  left_join(dplyr::select(trees, idTree, Genus, Species)) %>% 
  mutate(strata = as.numeric(Genusj == Genus, Speciesj == Species)) %>% 
  group_by(idTree) %>% 
  summarise(NCIhetero = log(sum(DBHj^2*exp(-0.25*dij)*abs(strata-1))+1),
            NCIcon = log(sum(DBHj^2*exp(-0.25*dij)*strata)+1))
Complexes <- bind_rows(
  data.frame(Complex = "Chartacea", Genus = "Eschweilera",
             Species = c("simiorum", "congestiflora")),
  data.frame(Complex = "Parvifolia", Genus = "Eschweilera",
             Species = c("pedicellata", "coriacea", "decolorans", "sagotiana",
                         "wachenheimii", "grandiflora_form2")),
  data.frame(Complex = "Licania", Genus = "Licania",
             Species = c("alba", "membranacea", "canescens", "micrantha",
                         "ovalifolia", "sprucei", "densiflora",
                         "laxiflora", "parvifructa")),
  data.frame(Complex = "Iryanthera", Genus = "Iryanthera",
             Species = c("hostmannii", "sagotiana")),
  data.frame(Complex = "Talisia", Genus = "Talisia",
             Species = c("hexaphylla", "praealta", "simaboides")),
  data.frame(Complex = "Symphonia", Genus = "Symphonia",
             Species = c("globulifera", "sp.1")))
load("./distribution_save/species.Rdata")
parameters <- lapply(fits, function(fit)
  apply(as.matrix(fit, pars = c("alpha", "beta", "gamma")), 2, mean) %>% 
    data.frame(parameter = names(.), value = .) %>% 
    separate(parameter, c("parameter", "type"), "\\[", fixed = T) %>% 
    mutate(type = gsub("]", "", type)) %>% 
    separate(type, c("SpeciesNum", "variableNum"), ",", convert = T)) %>% 
  bind_rows(.id = "Complex") %>% 
  left_join(data.frame(variableNum = 1:3, 
                      variable = c("TWI", "NCIhetero", "NCIcon"))) %>% 
  left_join(lapply(unique(Complexes$Complex), function(complex)
    data.frame(Complex = complex,
               SpeciesNum = 1:length(unique(filter(Complexes, Complex == complex)$Species)),
               Species = levels(as.factor(filter(Complexes, Complex == complex)$Species)))
  ) %>% bind_rows()) %>% 
  dplyr::select(Complex, Species, parameter, variable, value) %>% 
  reshape2::dcast(Complex + Species ~ parameter + variable, value.var = "value")
data <- trees %>% 
  left_join(env) %>% 
  left_join(Complexes) %>% 
  left_join(Competition) %>% 
  filter(!is.na(Plot)) %>% 
  filter(!is.na(Complex)) %>% 
  group_by(Complex, Species) %>% 
  filter(n() > 10) %>%
  ungroup() %>% 
  mutate_at(c("TWI", "NCIhetero", "NCIcon"), funs(scale)) %>% 
  left_join(parameters) %>% 
  mutate(Suitability = tsensembler:::softmax(alpha_NA + beta_TWI*TWI + beta_NCIhetero*NCIhetero +
                                               NCIcon*NCIcon + gamma_TWI*TWI^2 +
                                               gamma_NCIhetero*NCIhetero^2 + gamma_NCIcon*NCIcon^2)) %>% 
  group_by(Complex, Species) %>% 
  mutate(logSuitability = log(Suitability)) %>% 
  ungroup()
```

# Growth

## Individual growth

$$log(AGR+1) \sim \mathcal{N}(AGRmax_{ind}.e^{(-\frac12.\frac{log(\frac{dbh}{Dopt})}{Ks},^2}, sigma) \\ AGRmax_{ind} \sim \mathcal{N}(AGRmax,\sigma_{ind})$$


```{r mdata_growth}
paracou <-  src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>%
  collect() %>% 
  filter(idTree %in% data$idTree) %>%
  mutate(dbh = CircCorr/pi) %>% 
  group_by(idTree) %>% 
  arrange(idTree, CensusYear) %>% 
  mutate(ddbh = dbh - lag(dbh), 
         dt = CensusYear - lag(CensusYear)) %>% 
  filter(ddbh > 0) %>% 
  mutate(agr = ddbh/dt) %>% 
  ungroup(paracou) %>% 
  na.omit()
```

```{r fits_growth}
# Model <- stan_model("./distribution_models/Growth/growthInd.stan")
# fit <- sampling(Model, chains = 2, save_warmup = F,
#                 data = list(N = nrow(paracou),
#                             AGR = paracou$agr,
#                             dbh = paracou$dbh,
#                             S = length(unique(paracou$Species)),
#                             sp = as.numeric(as.factor(paracou$Species)),
#                             I = length(unique(paracou$idTree)),
#                             ind = as.numeric(as.factor(paracou$idTree)),
#                             indsp = paracou %>%
#                               select(Species, idTree) %>%
#                               mutate_all(as.factor) %>%
#                               mutate_all(as.numeric) %>%
#                               arrange(idTree) %>%
#                               unique() %>%
#                               select(Species) %>%
#                               unlist()
#                 ))
# save(fit, file = "./distribution_save/growthInd.Rdata")
load("./distribution_save/growthInd.Rdata")
```

```{r prediciton_growth}
paracou %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  mutate(AGRpred = apply(as.matrix(fit, pars = "AGRpred"), 2, mean)) %>% 
  ggplot(aes(x = dbh, col = SpeciesLong, group = idTree)) + 
  geom_point(aes(y = log(agr+1))) + 
  geom_line(aes(y = AGRpred))
```

$$AGRmax_{ind} \sim \mathcal{N}(\mu+\beta.log(suitability),\sigma)$$

```{r Ind}
data %>% 
  mutate(AGRmaxind = apply(as.matrix(fit, pars = "AGRmaxind"), 2, mean)[as.numeric(as.factor(data$idTree))]) %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  ggplot(aes(logSuitability, AGRmaxind)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~ SpeciesLong, scales = "free")
```

```{r IndLm}
data %>% 
  mutate(AGRmaxind = apply(as.matrix(fit, pars = "AGRmaxind"), 2, mean)[as.numeric(as.factor(data$idTree))]) %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  group_by(SpeciesLong) %>% 
  do(lm = lm(AGRmaxind ~ logSuitability, data = .)) %>% 
  broom::tidy(lm) %>% 
  filter(term == "logSuitability") %>% 
  kable(digits = 3)
```

## Individual vigor

$$log(AGR+1) \sim \mathcal{N}(AGRmax.e^{(-\frac12*\frac{log(\frac{dbh}{Dopt})}{Ks},^2}, sigma)$$

```{r mdataSp}
paracou <-  src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>%
  collect() %>% 
  filter(idTree %in% data$idTree) %>%
  mutate(dbh = CircCorr/pi) %>% 
  group_by(idTree) %>% 
  arrange(idTree, CensusYear) %>% 
  mutate(ddbh = dbh - lag(dbh), 
         dt = CensusYear - lag(CensusYear)) %>% 
  filter(ddbh > 0) %>% 
  mutate(agr = ddbh/dt) %>% 
  ungroup(paracou) %>% 
  na.omit()
```

```{r fitsSp}
# Model <- stan_model("./distribution_models/Growth/growthSp.stan")
# fit <- sampling(Model, chains = 2, save_warmup = F,
#                 data = list(N = nrow(paracou),
#                             AGR = paracou$agr,
#                             dbh = paracou$dbh,
#                             S = length(unique(paracou$Species)),
#                             sp = as.numeric(as.factor(paracou$Species))
#                 ))
# save(fit, file = "./distribution_save/growthSp.Rdata")
load("./distribution_save/growthSp.Rdata")
```

```{r predicitonSp}
left_join(paracou, data) %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  mutate(AGRpred = apply(as.matrix(fit, pars = "AGRpred"), 2, mean)) %>% 
  ggplot(aes(x = dbh, col = Species, group = idTree)) + 
  geom_point(aes(y = log(agr+1)), alpha = 0.1) + 
  geom_line(aes(y = AGRpred))
```

$$Vigor =  \frac{\int AGR - \int \hat{AGR}{n} \sim \mathcal{N} (\alpha+\beta .log(suitability),\sigma)  $$

```{r Sp}
paracou %>% 
  mutate(AGRpred = apply(as.matrix(fit, pars = "AGRpred"), 2, mean)) %>% 
  group_by(idTree) %>% 
  summarise(Vigor = (sum(agr)-sum(AGRpred))/n()) %>% 
  left_join(data) %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  ggplot(aes(logSuitability, Vigor)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~ SpeciesLong, scales = "free")
```

```{r SpLm}
paracou %>% 
  mutate(AGRpred = apply(as.matrix(fit, pars = "AGRpred"), 2, mean)) %>% 
  group_by(idTree) %>% 
  summarise(Vigor = (sum(agr)-sum(AGRpred))/n()) %>% 
  left_join(data) %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  group_by(SpeciesLong) %>% 
  do(lm = lm(Vigor ~ logSuitability, data = .)) %>% 
  broom::tidy(lm) %>% 
  filter(term == "logSuitability") %>% 
  kable(digits = 3)
```

## Suitability in model

```{r mdataDist}
paracou <-  src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>%
  collect() %>% 
  filter(idTree %in% data$idTree) %>%
  mutate(dbh = CircCorr/pi) %>% 
  group_by(idTree) %>% 
  arrange(idTree, CensusYear) %>% 
  mutate(ddbh = dbh - lag(dbh), 
         dt = CensusYear - lag(CensusYear)) %>% 
  filter(ddbh > 0) %>% 
  mutate(agr = ddbh/dt) %>% 
  left_join(dplyr::select(data, idTree, logSuitability))
```

```{r fitDist}
# Model <- stan_model("./distribution_models/Growth/growthDist.stan")
# fit <- sampling(Model, chains = 2, save_warmup = F,
#                 data = list(N = nrow(paracou),
#                             AGR = paracou$agr,
#                             dbh = paracou$dbh,
#                             suitability = paracou$logSuitability,
#                             S = length(unique(paracou$Species)),
#                             sp = as.numeric(as.factor(paracou$Species))
#                 ))
# save(fit, file = "./distribution_save/growthDist.Rdata")
load("./distribution_save/growthDist.Rdata")
```

```{r posteriorDist, eval=F}
bayesplot::mcmc_areas(as.array(fit, pars = c("Niche")))
```

```{r DistSummary, eval=F}
fit
```
