---
title: "A02: Joint taxa model"
date: '`r Sys.Date()`'
author: Sylvain Schmitt
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
vertical_layout: scroll
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

```{r setup, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(kableExtra)
library(rstan)
library(bayesplot)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 6,
  cache = T, cache.lazy = F)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
```

Intro
==================

Issue {data-width=200}
-------------------------------------

The aim of this document is to find the best general form of model to fit a joint distribution model. Especially we are thinking for a model that can deal with three specific cases :

* The environmental variable has no effect
* The niche optimum is in a intermediate value of the environmental variable range
* The niche optimum is at a limit of the environmental variable range

For this we will build three fake data sets distributed along our environmental variable as follow :

#### Models summary

```{r ModelsTable, render="pandoc"}
data.frame(
  Type = c("Dirichlet"),
  Name = c("$D_0$", "$D_{\\alpha}$", "$D_{\\alpha, \\alpha_2}$", "$D_{\\alpha, \\beta}$",
           "$D_{\\alpha, \\beta}2$", "$D_{\\alpha, \\beta}3$"),
  Formula = c("$Presence \\sim \\mathcal{Dirichlet}(logit^{-1}(\\alpha_0))$",
              "$Presence \\sim \\mathcal{Dirichlet}(logit^{-1}(\\alpha_0+\\alpha*Environment))$",
              "$Presence \\sim \\mathcal{Dirichlet}(logit^{-1}(\\alpha_0+\\alpha*Environment+\\alpha_2*Environment^2))$",
              "$Presence \\sim \\mathcal{Dirichlet}(logit^{-1}(\\alpha_0+\\alpha*Environment+Environment^{\\beta}))$",
              "$Presence \\sim \\mathcal{Dirichlet}(logit^{-1}(\\alpha_0+\\alpha*(Environment+Environment^{\\beta})))$",
              "$Presence \\sim \\mathcal{Dirichlet}(logit^{-1}(\\alpha_0+Environment^{\\alpha}+Environment^{\\beta}))$")  
) %>% 
  kable(caption = "Models summary.",
        format = "html", escape = F) %>% 
  kable_styling("striped", full_width = F) %>% 
  collapse_rows(1)
```


Data {data-width=200}
-------------------------------------

#### Fake data

```{r fakeData}
n <- 100
data <- list(
  no = data.frame(Environment = seq(0, 1, length.out = 100),
                  A = c(rep(0:1, 50)),
                  B = c(rep(c(1,0), 50)),
                  C = c(rep(c(1,0), 50))),
  intermediate = data.frame(Environment = seq(0, 1, length.out = n),
                            A = c(rep(0, 20), 
                                  rep(0:1,10),
                                  rep(1,20),
                                  rep(0:1,10),
                                  rep(0,20)),
                            B = c(rep(0, 5), 
                                  rep(0:1,10),
                                  rep(1,20),
                                  rep(0:1,10),
                                  rep(0,35)),
                            C = c(rep(0, 35), 
                                  rep(0:1,10),
                                  rep(1,20),
                                  rep(0:1,10),
                                  rep(0,5))),
  limit = data.frame(Environment = seq(0, 1, length.out = n), 
                     A = c(rep(0,30), rep(0:1,20), rep(1,30)),
                     B = c(rep(0, 20), 
                           rep(0:1,10),
                           rep(1,20),
                           rep(0:1,10),
                           rep(0,20)),
                     C = c(rep(1,30), rep(0:1,20), rep(0,30)))
)
data <- lapply(data, function(x) x %>% 
         reshape2::melt(id.vars = "Environment", 
                        variable.name = "Species", value.name = "Presence") %>% 
         filter(Presence != 0) %>% 
         select(-Presence))
mdata <- lapply(data, function(x) list(N = nrow(x),
                                       S = length(unique(x$Species)),
                                       Species = as.numeric(x$Species),
                                       Environment = x$Environment))
bind_rows(data, .id = "id") %>% 
  ggplot(aes(Environment, fill = Species, col = Species)) + 
  geom_density(alpha = 0.3) +  
  facet_wrap(~id, nrow = 3)
```

$D_0$
==================

Column 1
-------------------------------------

#### Model

...

$$Presence \sim \mathcal{Dirichlet~Process}(\alpha,\mathcal{N}(\mu_0,\sum0))$$

#### Code

```{stan , output.var="Model", echo=T, eval=F}
// from https://ecosang.github.io/blog/study/dirichlet-process-with-stan/
data{
  int<lower=0> S ; // # Species
  int<lower=0> N ; // # Observations
  real Environment[N] ;
}
parameters {
  real mu[S] ; //species mean
  real <lower=0,upper=1> v[S] ;
  real<lower=0> sigma[S] ; // species variance
  //real<lower=0> alpha ; // hyper prior DP(alpha,base)
}
transformed parameters{
  simplex [S] pi ;
  pi[1] = v[1] ;
  // stick-break process based on The BUGS book Chapter 11 (p.294)
  for(s in 2:(S-1))
      pi[s]= v[s]*(1-v[s-1])*pi[s-1]/v[s-1] ; 
  pi[S]=1-sum(pi[1:(S-1)]) ; // to make a simplex.
}
model {
  real alpha = 1 ;
  real a=0.001 ;
  real b=0.001 ;
  real ps[S] ;
  sigma ~ inv_gamma(a,b) ;
  mu ~ normal(0,5) ;
  //alpha~gamma(6,1) ;
  v ~ beta(1,alpha) ;
  for(n in 1:N){
    for(s in 1:S){
      ps[s]=log(pi[s])+normal_lpdf(Environment[n] | mu[s], sigma[s]) ;
    }
    target += log_sum_exp(ps) ;
  }
}
generated quantities {
  // pred
}
```

```{stan , output.var="Model", echo=T, eval=F}
// from https://ecosang.github.io/blog/study/dirichlet-process-with-stan/
data{
  int<lower=0> S ; // # Species
  int<lower=0> N ; // # Observations
  vector<lower=0>[N] Species ;
}
parameters {
  vector<lower=0>[S] alpha ;
}
model {
  target += dirichlet_lpdf(Species | alpha) ;
}
generated quantities {
  // pred
}
```

#### Summary

```{r }
# fits <- lapply(mdata, function(x) sampling(Model, chains = 2, data = x))
# names(fits) <- names(mdata)
# save(fits, file = "./distribution_save/D0.Rdata")
load("./distribution_save/D0.Rdata")
pars <- c("alpha")
lapply(as.list(names(mdata)), function(type)
  broom::tidyMCMC(fits[[type]], pars = c(pars, "lp__"), droppars = NULL, rhat = T) %>%
    mutate(Type = type)) %>%
  bind_rows() %>%
  kable()
```

#### Posteriors

```{r , fig.cap="Model parameters posterior."}
cowplot::plot_grid(plotlist = lapply(names(data), function(type)
  mcmc_intervals(as.array(fits[[type]]), regex_pars = pars)),
  labels = names(data), nrow = 2)
```

Column 2
-------------------------------------

#### Chains

```{r , fig.cap="Markov chains trace plot after warmup for intermediate data."}
mcmc_trace(as.array(fits$intermediate), regex_pars = c(pars, "lp__"),
             facet_args = list(labeller = label_parsed))
```

#### Pairs

```{r , fig.cap="Markov chains pairs plot after warmup  for intermediate data."}
mcmc_pairs(as.array(fits$intermediate), regex_pars = c(pars, "lp__"))
```

#### Predictions

```{r , fig.cap="Predictions."}
lapply(as.list(names(data)), function(type)
  cbind(type = type, data[[type]],
        mu = apply(as.matrix(fits[[type]], pars = "mu_species"), 2, mean),
        t(apply(as.matrix(fits[[type]], pars = "mu"), 2, quantile, probs = c(0.05, 0.95))))) %>%
  bind_rows() %>%
  ggplot(aes(x = Environment)) +
  geom_point(aes(y = Presence, col = as.factor(Presence))) +
  geom_point(aes(y = mu)) +
  geom_ribbon(aes(ymin = `5%`, ymax = `95%`), color = 'red', alpha = 0.2) +
  geom_line(aes(y = `5%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") +
  geom_line(aes(y = `95%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") +
  facet_wrap(~ type, scales = "free", nrow = 3)

cbind(type = type, data[[type]],
        mu = apply(as.matrix(fits[[type]], pars = "mu_species"), 2, mean),
        t(apply(as.matrix(fits[[type]], pars = "mu_species"), 2, quantile, probs = c(0.05, 0.95))))
```

<!-- $B_{\alpha}$ -->
<!-- ================== -->

<!-- Column 1 -->
<!-- ------------------------------------- -->

<!-- #### Model -->

<!-- $B_{\alpha}$ is a Bernoulli logistic regression estimating a sigmoidal incresing or decreasing $\alpha$ along the whole environmental gradient in addition to the intercept $\alpha_0$. $B_{\alpha}$ is responding well to the optimum in the limit of the environmental range and to no effect from the environmental variable. But $B_{\alpha}$ can't detect ecological optimum in the middle of the ecological range besides it's the most commonly used model ! -->

<!-- $$Presence \sim \mathcal{Bernoulli}(logit(\alpha_0+\alpha*Environment))$$ -->

<!-- #### Code -->

<!-- ```{stan , output.var="Model", echo=T, eval=F} -->
<!--   data { -->
<!--     int<lower=1> N ; // # obs -->
<!--     int<lower=0, upper=1> Presence[N] ; -->
<!--     vector[N] Environment ; -->
<!--     vector<lower=0, upper=1>[N] weights ; -->
<!--   } -->
<!--   parameters { -->
<!--     real alpha_0 ; // Intercept -->
<!--     real alpha ; // sigmoidal slope -->
<!--   } -->
<!--   model { -->
<!--     target += weights*bernoulli_logit_lpmf(Presence | alpha_0 + alpha*Environment) ; -->
<!--   } -->
<!--   generated quantities { -->
<!--     vector<lower=0, upper=1>[N] mu ; -->
<!--     mu = inv_logit(alpha_0 + alpha*Environment) ; -->
<!--   } -->
<!-- ``` -->

<!-- #### Summary -->

<!-- ```{r } -->
<!-- # fits <- lapply(mdata, function(x) sampling(Model, chains = 2, data = x)) -->
<!-- # names(fits) <- names(mdata) -->
<!-- # save(fits, file = "./distribution_save/Balpha.Rdata") -->
<!-- load("./distribution_save/Balpha.Rdata") -->
<!-- pars <- c("alpha_0", "alpha") -->
<!-- lapply(as.list(names(mdata)), function(type) -->
<!--   broom::tidyMCMC(fits[[type]], pars = c(pars, "lp__"), droppars = NULL, rhat = T) %>% -->
<!--     mutate(Type = type)) %>% -->
<!--   bind_rows() %>% -->
<!--   kable() -->
<!-- ``` -->

<!-- #### Posteriors -->

<!-- ```{r , fig.cap="Model parameters posterior."} -->
<!-- cowplot::plot_grid(plotlist = lapply(names(data), function(type) -->
<!--   mcmc_intervals(as.array(fits[[type]]), pars = pars)), -->
<!--   labels = names(data), nrow = 2) -->
<!-- ``` -->

<!-- Column 2 -->
<!-- ------------------------------------- -->

<!-- #### Chains -->

<!-- ```{r , fig.cap="Markov chains trace plot after warmup for intermediate data."} -->
<!-- mcmc_trace(as.array(fits$limit), pars = c(pars, "lp__"), -->
<!--              facet_args = list(labeller = label_parsed)) -->
<!-- ``` -->

<!-- #### Pairs -->

<!-- ```{r , fig.cap="Markov chains pairs plot after warmup  for intermediate data."} -->
<!-- mcmc_pairs(as.array(fits$limit), pars = c(pars, "lp__")) -->
<!-- ``` -->

<!-- #### Predictions -->

<!-- ```{r , fig.cap="Predictions."} -->
<!-- lapply(as.list(names(data)), function(type) -->
<!--   cbind(type = type, data[[type]], -->
<!--         mu = apply(as.matrix(fits[[type]], pars = "mu"), 2, mean), -->
<!--         t(apply(as.matrix(fits[[type]], pars = "mu"), 2, quantile, probs = c(0.05, 0.95))))) %>%  -->
<!--   bind_rows() %>%  -->
<!--   ggplot(aes(x = Environment)) + -->
<!--   geom_point(aes(y = Presence, col = as.factor(Presence))) + -->
<!--   geom_point(aes(y = mu)) + -->
<!--   geom_ribbon(aes(ymin = `5%`, ymax = `95%`), color = 'red', alpha = 0.2) + -->
<!--   geom_line(aes(y = `5%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") + -->
<!--   geom_line(aes(y = `95%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") + -->
<!--   facet_wrap(~ type, scales = "free", nrow = 3) -->
<!-- ``` -->

<!-- $B_{\alpha, \alpha_2}$ -->
<!-- ================== -->

<!-- Column 1 -->
<!-- ------------------------------------- -->

<!-- #### Model -->

<!-- $B_{\alpha, \alpha_2}$ is a Bernoulli logistic regression allowing a quadratic form in addition to sigmoids with the $\alpha_2$ parameter. $B_{\alpha, \alpha_2}$ is giving the expected result in every case. -->

<!-- $$Presence \sim \mathcal{Bernoulli}(logit^{-1}(\alpha_0 + \alpha*Environment+\alpha_2*Environment^2))$$ -->

<!-- #### Code -->

<!-- ```{stan , output.var="Model", echo=T, eval=F} -->
<!--   data { -->
<!--     int<lower=1> N ; // # obs -->
<!--     int<lower=0, upper=1> Presence[N] ; -->
<!--     vector[N] Environment ; -->
<!--     vector<lower=0, upper=1>[N] weights ; -->
<!--   } -->
<!--   parameters { -->
<!--     real alpha_0 ; // intercept -->
<!--     real alpha ; // sigmoidal slope -->
<!--     real alpha_2 ; // quadratic form -->
<!--   } -->
<!--   model { -->
<!--     target += weights*bernoulli_logit_lpmf(Presence | alpha_0 + alpha*Environment + alpha_2 * Environment .* Environment) ; -->
<!--   } -->
<!--   generated quantities { -->
<!--     vector<lower=0, upper=1>[N] theta ; -->
<!--     theta = inv_logit(alpha_0 + alpha * Environment  + alpha_2 * Environment .* Environment) ; -->
<!--   } -->
<!-- ``` -->

<!-- #### Summary -->

<!-- ```{r } -->
<!-- # fits <- lapply(mdata, function(x) sampling(Model, chains = 2, data = x)) -->
<!-- # names(fits) <- names(mdata) -->
<!-- # save(fits, file = "./distribution_save/Balpha2.Rdata") -->
<!-- load("./distribution_save/Balpha2.Rdata") -->
<!-- pars <- c("alpha_0", "alpha", "alpha_2") -->
<!-- lapply(as.list(names(mdata)), function(type) -->
<!--   broom::tidyMCMC(fits[[type]], pars = c(pars, "lp__"), droppars = NULL, rhat = T) %>% -->
<!--     mutate(Type = type)) %>% -->
<!--   bind_rows() %>% -->
<!--   kable() -->
<!-- ``` -->

<!-- #### Posteriors -->

<!-- ```{r , fig.cap="Model parameters posterior."} -->
<!-- cowplot::plot_grid(plotlist = lapply(names(data), function(type) -->
<!--   mcmc_intervals(as.array(fits[[type]]), pars = pars)), -->
<!--   labels = names(data), nrow = 2) -->
<!-- ``` -->

<!-- Column 2 -->
<!-- ------------------------------------- -->

<!-- #### Chains -->

<!-- ```{r , fig.cap="Markov chains trace plot after warmup for intermediate data."} -->
<!-- mcmc_trace(as.array(fits$intermediate), pars = c(pars, "lp__"), -->
<!--              facet_args = list(labeller = label_parsed)) -->
<!-- ``` -->

<!-- #### Pairs -->

<!-- ```{r , fig.cap="Markov chains pairs plot after warmup  for intermediate data."} -->
<!-- mcmc_pairs(as.array(fits$intermediate), pars = c(pars, "lp__")) -->
<!-- ``` -->

<!-- #### Predictions -->

<!-- ```{r , fig.cap="Predictions."} -->
<!-- lapply(as.list(names(data)), function(type) -->
<!--   cbind(type = type, data[[type]], -->
<!--         mu = apply(as.matrix(fits[[type]], pars = "theta"), 2, mean), -->
<!--         t(apply(as.matrix(fits[[type]], pars = "theta"), 2, quantile, probs = c(0.05, 0.95))))) %>% -->
<!--   bind_rows() %>% -->
<!--   ggplot(aes(x = Environment)) + -->
<!--   geom_point(aes(y = Presence, col = as.factor(Presence))) + -->
<!--   geom_point(aes(y = mu)) + -->
<!--   geom_ribbon(aes(ymin = `5%`, ymax = `95%`), color = 'red', alpha = 0.2) + -->
<!--   geom_line(aes(y = `5%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") + -->
<!--   geom_line(aes(y = `95%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") + -->
<!--   facet_wrap(~ type, scales = "free", nrow = 3) -->
<!-- ``` -->

<!-- $B_{\alpha, \beta}$ -->
<!-- ================== -->

<!-- Column 1 -->
<!-- ------------------------------------- -->

<!-- #### Model -->

<!-- $B_{\alpha, \beta}$ is a Bernoulli logistic regression allowing a polynomial form in addition to sigmoids with the $\beta$ power parameter on the environmental variable. $B_{\alpha, \beta}$ is not dealing well with the intermediate niche optimum case. -->

<!-- $$Presence \sim \mathcal{Bernoulli}(logit^{-1}(\alpha_0 + \alpha*Environment+Environment^{\beta}))$$ -->

<!-- #### Code -->

<!-- ```{stan , output.var="Model", echo=T, eval=F} -->
<!--   data { -->
<!--     int<lower=1> N ; // # obs -->
<!--     int<lower=0, upper=1> Presence[N] ; -->
<!--     vector[N] Environment ; -->
<!--     vector<lower=0, upper=1>[N] weights ; -->
<!--   } -->
<!--   parameters { -->
<!--     real alpha_0 ; // Intercept -->
<!--     real alpha ; // sigmoidal slope -->
<!--     real<lower=0, upper=4> beta ; // power form -->
<!--   } -->
<!--   model { -->
<!--     for(n in 1:N) -->
<!--       target += weights*bernoulli_logit_lpmf(Presence[n] | alpha_0 + alpha*Environment[n] + pow(Environment[n], beta)) ; -->
<!--   } -->
<!--   generated quantities { -->
<!--     vector<lower=0, upper=1>[N] theta ; -->
<!--     for(n in 1:N) -->
<!--       theta[n] = inv_logit(alpha_0 + alpha * Environment[n]  + pow(Environment[n], beta)) ; -->
<!--   } -->
<!-- ``` -->

<!-- #### Summary -->

<!-- ```{r } -->
<!-- # fits <- lapply(mdata, function(x) sampling(Model, chains = 2, data = x)) -->
<!-- # names(fits) <- names(mdata) -->
<!-- # save(fits, file = "./distribution_save/Bbeta.Rdata") -->
<!-- load("./distribution_save/Bbeta.Rdata") -->
<!-- pars <- c("alpha_0", "alpha", "beta") -->
<!-- lapply(as.list(names(mdata)), function(type) -->
<!--   broom::tidyMCMC(fits[[type]], pars = c(pars, "lp__"), droppars = NULL, rhat = T) %>% -->
<!--     mutate(Type = type)) %>% -->
<!--   bind_rows() %>% -->
<!--   kable() -->
<!-- ``` -->

<!-- #### Posteriors -->

<!-- ```{r , fig.cap="Model parameters posterior."} -->
<!-- cowplot::plot_grid(plotlist = lapply(names(data), function(type) -->
<!--   mcmc_intervals(as.array(fits[[type]]), pars = pars)), -->
<!--   labels = names(data), nrow = 2) -->
<!-- ``` -->

<!-- Column 2 -->
<!-- ------------------------------------- -->

<!-- #### Chains -->

<!-- ```{r , fig.cap="Markov chains trace plot after warmup for limit data."} -->
<!-- mcmc_trace(as.array(fits$limit), pars = c(pars, "lp__"), -->
<!--              facet_args = list(labeller = label_parsed)) -->
<!-- ``` -->

<!-- #### Pairs -->

<!-- ```{r , fig.cap="Markov chains pairs plot after warmup  for limit data."} -->
<!-- mcmc_pairs(as.array(fits$limit), pars = c(pars, "lp__")) -->
<!-- ``` -->

<!-- #### Predictions -->

<!-- ```{r , fig.cap="Predictions."} -->
<!-- lapply(as.list(names(data)), function(type) -->
<!--   cbind(type = type, data[[type]], -->
<!--         mu = apply(as.matrix(fits[[type]], pars = "theta"), 2, mean), -->
<!--         t(apply(as.matrix(fits[[type]], pars = "theta"), 2, quantile, probs = c(0.05, 0.95))))) %>% -->
<!--   bind_rows() %>% -->
<!--   ggplot(aes(x = Environment)) + -->
<!--   geom_point(aes(y = Presence, col = as.factor(Presence))) + -->
<!--   geom_point(aes(y = mu)) + -->
<!--   geom_ribbon(aes(ymin = `5%`, ymax = `95%`), color = 'red', alpha = 0.2) + -->
<!--   geom_line(aes(y = `5%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") + -->
<!--   geom_line(aes(y = `95%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") + -->
<!--   facet_wrap(~ type, scales = "free", nrow = 3) -->
<!-- ``` -->

<!-- $B_{\alpha, \beta}2$ -->
<!-- ================== -->

<!-- Column 1 -->
<!-- ------------------------------------- -->

<!-- #### Model -->

<!-- $B_{\alpha, \beta}2$ is a Bernoulli logistic regression allowing a polynomial form in addition to sigmoids with the $\beta$ power parameter on the environmental variable. $B_{\alpha, \beta}2$ is not dealing well with the intermediate niche optimum case. -->

<!-- $$Presence \sim \mathcal{Bernoulli}(logit^{-1}(\alpha_0 + \alpha*(Environment+Environment^{\beta})))$$ -->

<!-- #### Code -->

<!-- ```{stan , output.var="Model", echo=T, eval=F} -->
<!--   data { -->
<!--     int<lower=1> N ; // # obs -->
<!--     int<lower=0, upper=1> Presence[N] ; -->
<!--     vector[N] Environment ; -->
<!--     vector<lower=0, upper=1>[N] weights ; -->
<!--   } -->
<!--   parameters { -->
<!--     real alpha_0 ; // intercept -->
<!--     real alpha ; // sigmoidal slope -->
<!--     real<lower=0, upper=4> beta ; // power form -->
<!--   } -->
<!--   model { -->
<!--     for(n in 1:N) -->
<!--       target += weights*bernoulli_logit_lpmf(Presence[n] | alpha_0 + alpha*(Environment[n] + pow(Environment[n], beta))) ; -->
<!--   } -->
<!--   generated quantities { -->
<!--     vector<lower=0, upper=1>[N] theta ; -->
<!--     for(n in 1:N) -->
<!--       theta[n] = inv_logit(alpha_0 + alpha*(Environment[n]  + pow(Environment[n], beta))) ; -->
<!--   } -->
<!-- ``` -->

<!-- #### Summary -->

<!-- ```{r } -->
<!-- # fits <- lapply(mdata, function(x) sampling(Model, chains = 2, data = x)) -->
<!-- # names(fits) <- names(mdata) -->
<!-- # save(fits, file = "./distribution_save/Bbeta2.Rdata") -->
<!-- load("./distribution_save/Bbeta2.Rdata") -->
<!-- pars <- c("alpha_0", "alpha", "beta") -->
<!-- lapply(as.list(names(mdata)), function(type) -->
<!--   broom::tidyMCMC(fits[[type]], pars = c(pars, "lp__"), droppars = NULL, rhat = T) %>% -->
<!--     mutate(Type = type)) %>% -->
<!--   bind_rows() %>% -->
<!--   kable() -->
<!-- ``` -->

<!-- #### Posteriors -->

<!-- ```{r , fig.cap="Model parameters posterior."} -->
<!-- cowplot::plot_grid(plotlist = lapply(names(data), function(type) -->
<!--   mcmc_intervals(as.array(fits[[type]]), pars = pars)), -->
<!--   labels = names(data), nrow = 2) -->
<!-- ``` -->

<!-- Column 2 -->
<!-- ------------------------------------- -->

<!-- #### Chains -->

<!-- ```{r , fig.cap="Markov chains trace plot after warmup for limit data."} -->
<!-- mcmc_trace(as.array(fits$limit), pars = c(pars, "lp__"), -->
<!--              facet_args = list(labeller = label_parsed)) -->
<!-- ``` -->

<!-- #### Pairs -->

<!-- ```{r , fig.cap="Markov chains pairs plot after warmup  for limit data."} -->
<!-- mcmc_pairs(as.array(fits$limit), pars = c(pars, "lp__")) -->
<!-- ``` -->

<!-- #### Predictions -->

<!-- ```{r , fig.cap="Predictions."} -->
<!-- lapply(as.list(names(data)), function(type) -->
<!--   cbind(type = type, data[[type]], -->
<!--         mu = apply(as.matrix(fits[[type]], pars = "theta"), 2, mean), -->
<!--         t(apply(as.matrix(fits[[type]], pars = "theta"), 2, quantile, probs = c(0.05, 0.95))))) %>% -->
<!--   bind_rows() %>% -->
<!--   ggplot(aes(x = Environment)) + -->
<!--   geom_point(aes(y = Presence, col = as.factor(Presence))) + -->
<!--   geom_point(aes(y = mu)) + -->
<!--   geom_ribbon(aes(ymin = `5%`, ymax = `95%`), color = 'red', alpha = 0.2) + -->
<!--   geom_line(aes(y = `5%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") + -->
<!--   geom_line(aes(y = `95%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") + -->
<!--   facet_wrap(~ type, scales = "free", nrow = 3) -->
<!-- ``` -->

<!-- $B_{\alpha, \beta}3$ -->
<!-- ================== -->

<!-- Column 1 -->
<!-- ------------------------------------- -->

<!-- #### Model -->

<!-- $B_{\alpha, \beta}3$ is a Bernoulli logistic regression allowing a polynomial form in addition to sigmoids with the $\beta$ power parameter on the environmental variable.$B_{\alpha, \beta}3$ is not dealing well with the intermediate niche optimum case. -->

<!-- $$Presence \sim \mathcal{Bernoulli}(logit^{-1}(\alpha_0+Environment^{\alpha}+Environment^{\beta})))~|~\alpha<\beta$$ -->

<!-- #### Code -->

<!-- ```{stan , output.var="Model", echo=T, eval=F} -->
<!--   data { -->
<!--     int<lower=1> N ; // # obs -->
<!--     int<lower=0, upper=1> Presence[N] ; -->
<!--     vector[N] Environment ; -->
<!--     vector<lower=0, upper=1>[N] weights ; -->
<!--   } -->
<!--   parameters { -->
<!--     real alpha_0 ; // intercept -->
<!--     real<lower=0, upper=4> beta ; // second power form -->
<!--     real<lower=0, upper=beta> alpha ; // first power form -->
<!--   } -->
<!--   model { -->
<!--     for(n in 1:N) -->
<!--       target += weights*bernoulli_logit_lpmf(Presence[n] | alpha_0 + pow(Environment[n], alpha) + pow(Environment[n], beta)) ; -->
<!--   } -->
<!--   generated quantities { -->
<!--     vector<lower=0, upper=1>[N] theta ; -->
<!--     for(n in 1:N) -->
<!--       theta[n] = inv_logit(alpha_0 + pow(Environment[n], alpha) + pow(Environment[n], beta)) ; -->
<!--   } -->
<!-- ``` -->

<!-- #### Summary -->

<!-- ```{r } -->
<!-- # fits <- lapply(mdata, function(x) sampling(Model, chains = 2, data = x)) -->
<!-- # names(fits) <- names(mdata) -->
<!-- # save(fits, file = "./distribution_save/Bbeta3.Rdata") -->
<!-- load("./distribution_save/Bbeta3.Rdata") -->
<!-- pars <- c("alpha_0", "alpha", "beta") -->
<!-- lapply(as.list(names(mdata)), function(type) -->
<!--   broom::tidyMCMC(fits[[type]], pars = c(pars, "lp__"), droppars = NULL, rhat = T) %>% -->
<!--     mutate(Type = type)) %>% -->
<!--   bind_rows() %>% -->
<!--   kable() -->
<!-- ``` -->

<!-- #### Posteriors -->

<!-- ```{r , fig.cap="Model parameters posterior."} -->
<!-- cowplot::plot_grid(plotlist = lapply(names(data), function(type) -->
<!--   mcmc_intervals(as.array(fits[[type]]), pars = pars)), -->
<!--   labels = names(data), nrow = 2) -->
<!-- ``` -->

<!-- Column 2 -->
<!-- ------------------------------------- -->

<!-- #### Chains -->

<!-- ```{r , fig.cap="Markov chains trace plot after warmup for limit data."} -->
<!-- mcmc_trace(as.array(fits$limit), pars = c(pars, "lp__"), -->
<!--              facet_args = list(labeller = label_parsed)) -->
<!-- ``` -->

<!-- #### Pairs -->

<!-- ```{r , fig.cap="Markov chains pairs plot after warmup  for limit data."} -->
<!-- mcmc_pairs(as.array(fits$limit), pars = c(pars, "lp__")) -->
<!-- ``` -->

<!-- #### Predictions -->

<!-- ```{r , fig.cap="Predictions."} -->
<!-- lapply(as.list(names(data)), function(type) -->
<!--   cbind(type = type, data[[type]], -->
<!--         mu = apply(as.matrix(fits[[type]], pars = "theta"), 2, mean), -->
<!--         t(apply(as.matrix(fits[[type]], pars = "theta"), 2, quantile, probs = c(0.05, 0.95))))) %>% -->
<!--   bind_rows() %>% -->
<!--   ggplot(aes(x = Environment)) + -->
<!--   geom_point(aes(y = Presence, col = as.factor(Presence))) + -->
<!--   geom_point(aes(y = mu)) + -->
<!--   geom_ribbon(aes(ymin = `5%`, ymax = `95%`), color = 'red', alpha = 0.2) + -->
<!--   geom_line(aes(y = `5%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") + -->
<!--   geom_line(aes(y = `95%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") + -->
<!--   facet_wrap(~ type, scales = "free", nrow = 3) -->
<!-- ``` -->

# Discussion

