---
title: "A09 : Traits and growth"
date: '`r Sys.Date()`'
author: Sylvain Schmitt
output:
  bookdown::html_document2:
    number_sections: no
    toc: true
    toc_float: yes
    theme: flatly
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
  bookdown::word_document2: default
linestretch: 1.5
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

```{r setup, include=FALSE}
#rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(rstan)
library(bayesplot)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 8, fig.width = 8,
  cache = T, cache.lazy = F)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
path <- "../../data/Paracou/"
```

```{r data}
d <- 20
trees <- src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>% 
  tbl("Paracou") %>% 
  filter(CensusYear == 2015) %>%
  filter(Xfield > d, Xfield < 250-d, Yfield > d, Yfield < 250-d) %>% 
  filter(Species != "Indet.") %>% 
  mutate(DBH = CircCorr/pi) %>% 
  collect()
load("./distribution_save/env.Rdata")
load("./distribution_save/Competition.Rdata")
Competition <- Competition %>% 
  mutate(dij = ifelse(dij <1, 1, dij)) %>% 
  left_join(dplyr::select(trees, idTree, Genus, Species)) %>% 
  mutate(strata = as.numeric(Genusj == Genus, Speciesj == Species)) %>% 
  group_by(idTree) %>% 
  summarise(NCIother = sum(DBHj^2*exp(-0.25*dij)*abs(strata-1)),
            NCIspecies = sum(DBHj^2*exp(-0.25*dij)*strata))
Complexes <- bind_rows(
  data.frame(Complex = "E. Chartacea", Genus = "Eschweilera",
             Species = c("simiorum", "congestiflora")),
  data.frame(Complex = "E. Parvifolia", Genus = "Eschweilera",
             Species = c("pedicellata", "coriacea", "decolorans", "sagotiana",
                         "wachenheimii", "grandiflora_form2")),
  data.frame(Complex = "Licania", Genus = "Licania",
             Species = c("alba", "membranacea", "canescens", "micrantha",
                         "ovalifolia", "sprucei", "densiflora",
                         "laxiflora", "parvifructa")),
  data.frame(Complex = "Iryanthera", Genus = "Iryanthera",
             Species = c("hostmannii", "sagotiana")),
  data.frame(Complex = "Talisia", Genus = "Talisia",
             Species = c("hexaphylla", "praealta", "simaboides")),
  data.frame(Complex = "Symphonia", Genus = "Symphonia",
             Species = c("globulifera", "sp.1")))
load("./distribution_save/species.Rdata")
alpha <- apply(as.matrix(fits$Symphonia, pars = "alpha"), 2, mean)
beta <- apply(as.matrix(fits$Symphonia, pars = "beta"), 2, mean)
gamma <- apply(as.matrix(fits$Symphonia, pars = "gamma"), 2, mean)
data <- trees %>% 
  left_join(env) %>% 
  left_join(Complexes) %>% 
  left_join(Competition) %>% 
  filter(!is.na(Plot)) %>% 
  filter(!is.na(Complex)) %>% 
  group_by(Complex, Species) %>% 
  filter(n() > 10) %>%
  ungroup() %>% 
  filter(Complex == "Symphonia") %>% 
  mutate_at(c("TWI", "NCIother", "NCIspecies"), funs(scale)) %>% 
  mutate(suitability = ifelse(Species == "globulifera",
                              tsensembler:::softmax(alpha[1] + beta[1]*TWI + beta[3]*NCIother +
                                                      beta[5]*NCIspecies + gamma[1]*TWI^2 +
                                                      gamma[3]*NCIother^2 + gamma[5]*NCIspecies^2),
                              tsensembler:::softmax(alpha[2] + beta[2]*TWI + beta[4]*NCIother +
                                                      beta[6]*NCIspecies + gamma[2]*TWI^2 +
                                                      gamma[4]*NCIother^2 + gamma[6]*NCIspecies^2)))
```

## Individual growth

```{stan stanModel, output.var="Model", echo=T, eval=F}
data {
  int<lower=1> N ; // Nb of observations
  vector<lower=0>[N] AGR ; // growth vector
  vector<lower=0>[N] dbh ; // dbh vector
  int<lower=1> S ; // Nb of species
  int<lower=0> sp[N] ; // species vector
  int<lower=1> I ; // Nb of individuals
  int<lower=0> ind[N] ; // individual vector
  int<lower=0> indsp[I] ; // individual in species vector
}
parameters {
  vector<lower=0.1,upper=10>[I] AGRmaxind ; // individual potential growth
  vector<lower=0.1,upper=10>[S] AGRmax ; // species potential growth
  vector<lower=0,upper=10>[S] sigmaInd ; // individual potential growth deviation
  vector<lower=0,upper=200>[S] Dopt ; // optimal diameter
  vector<lower=0.1,upper=10>[S] Ks ; // kurtosis
  real<lower=0,upper=10> sigma ;
}
model {
  AGRmaxind ~ normal(AGRmax[indsp], sigmaInd[indsp]) ;
  for(n in 1:N)
    log(AGR[n]+1) ~ normal(AGRmaxind[ind[n]]*exp(-0.5*pow(log(dbh[n]/Dopt[sp[n]])/Ks[sp[n]], 2)), sigma) ;
}
generated quantities {
  vector<lower=0>[N] AGRpred ;
  for(n in 1:N)
    AGRpred[n] = AGRmaxind[ind[n]]*exp(-0.5*pow(log(dbh[n]/Dopt[sp[n]])/Ks[sp[n]], 2)) ;
}
```

```{r mdata}
paracou <-  src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>%
  filter(idTree %in% data$idTree) %>%
  mutate(dbh = CircCorr/pi) %>% 
  group_by(idTree) %>% 
  arrange(idTree, CensusYear) %>% 
  collect() %>% 
  mutate(ddbh = dbh - lag(dbh), 
         dt = CensusYear - lag(CensusYear)) %>% 
  filter(ddbh > 0) %>% 
  mutate(agr = ddbh/dt) %>% 
  ungroup(paracou) %>% 
  na.omit()
```

```{r fits}
fit <- sampling(Model, chains = 2, save_warmup = F,
                data = list(N = nrow(paracou),
                            AGR = paracou$agr,
                            dbh = paracou$dbh,
                            S = length(unique(paracou$Species)),
                            sp = as.numeric(as.factor(paracou$Species)),
                            I = length(unique(paracou$idTree)),
                            ind = as.numeric(as.factor(paracou$idTree)),
                            indsp = paracou %>%
                              select(Species, idTree) %>%
                              mutate_all(as.factor) %>%
                              mutate_all(as.numeric) %>%
                              arrange(idTree) %>%
                              unique() %>%
                              select(Species) %>%
                              unlist()
                ))
save(fit, file = "./distribution_save/growth.Rdata")
load("./distribution_save/growth.Rdata")
```

```{r mcmc, fig.cap="Markov chains trace plot after warmup for leaf thickness model."}
check_divergences(fit)
# mcmc_trace(as.array(fit), facet_args = list(labeller = label_parsed))
```

```{r prediciton}
data %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  mutate(AGRpred = apply(as.matrix(fit, pars = "AGRpred"), 2, mean)) %>% 
  ggplot(aes(x = dbh, col = SpeciesLong, group = idTree)) + 
  geom_point(aes(y = log(agr+1))) + 
  geom_line(aes(y = AGRpred))
```

```{r trait}
data %>% 
  mutate(AGRmaxind = apply(as.matrix(fit, pars = "AGRmaxind"), 2, mean)[as.numeric(as.factor(data$idTree))]) %>% 
  left_join(Individuals) %>% 
  select(Genus, Species, idTree, AGRmaxind, SLA, LDMC, LT, LA, CC) %>% 
  filter(!is.na(SLA)) %>% 
  unique() %>% 
  reshape2::melt(id.vars = c("Genus", "Species", "idTree", "AGRmaxind"),
                 variable.name = "Trait") %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  ggplot(aes(value, AGRmaxind)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(SpeciesLong ~ Trait, scales = "free")
```

```{r traitLm}
data %>% 
  mutate(AGRmaxind = apply(as.matrix(fit, pars = "AGRmaxind"), 2, mean)[as.numeric(as.factor(data$idTree))]) %>% 
  left_join(Individuals) %>% 
  select(Genus, Species, idTree, AGRmaxind, SLA, LDMC, LT, LA, CC) %>% 
  filter(!is.na(SLA)) %>% 
  unique() %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  group_by(SpeciesLong) %>% 
  do(lm = lm(AGRmaxind ~ SLA + LDMC + LT + LA + CC, data = .)) %>% 
  broom::tidy(lm) %>% 
  filter(p.value < 0.05) %>% 
  kable(digits = 3)
```

## Individual vigor

```{stan stanModelSp, output.var="Model", echo=T, eval=F}
data {
  int<lower=1> N ; // Nb of observations
  vector<lower=0>[N] AGR ; // growth vector
  vector<lower=0>[N] dbh ; // dbh vector
  int<lower=1> S ; // Nb of species
  int<lower=0> sp[N] ; // species vector
}
parameters {
  vector<lower=0.1,upper=10>[S] AGRmax ; // species potential growth
  vector<lower=0,upper=200>[S] Dopt ; // optimal diameter
  vector<lower=0.1,upper=10>[S] Ks ; // kurtosis
  real<lower=0,upper=10> sigma ;
}
model {
  for(n in 1:N)
    log(AGR[n]+1) ~ normal(AGRmax[sp[n]]*exp(-0.5*pow(log(dbh[n]/Dopt[sp[n]])/Ks[sp[n]], 2)), sigma) ;
}
generated quantities {
  vector<lower=0>[N] AGRpred ;
  for(n in 1:N)
    AGRpred[n] = AGRmax[sp[n]]*exp(-0.5*pow(log(dbh[n]/Dopt[sp[n]])/Ks[sp[n]], 2)) ;
}
```

```{r mdataSp}
paracou <-  src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>%
  filter(idTree %in% data$idTree) %>%
  mutate(dbh = CircCorr/pi) %>% 
  group_by(idTree) %>% 
  arrange(idTree, CensusYear) %>% 
  collect() %>% 
  mutate(ddbh = dbh - lag(dbh), 
         dt = CensusYear - lag(CensusYear)) %>% 
  filter(ddbh > 0) %>% 
  mutate(agr = ddbh/dt) %>% 
  ungroup(paracou) %>% 
  na.omit()
```

```{r fitsSp}
fit <- sampling(Model, chains = 2, save_warmup = F,
                data = list(N = nrow(paracou),
                            AGR = paracou$agr,
                            dbh = paracou$dbh,
                            S = length(unique(paracou$Species)),
                            sp = as.numeric(as.factor(paracou$Species))
                ))
save(fit, file = "./distribution_save/growthsp.Rdata")
load("./distribution_save/growthsp.Rdata")
```

```{r predicitonSp}
left_join(paracou, data) %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  mutate(AGRpred = apply(as.matrix(fit, pars = "AGRpred"), 2, mean)) %>% 
  ggplot(aes(x = dbh, col = SpeciesLong, group = idTree)) + 
  geom_point(aes(y = log(agr+1)), alpha = 0.1) + 
  geom_line(aes(y = AGRpred))
```

```{r traitSp}
left_join(paracou, data) %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  mutate(AGRpred = apply(as.matrix(fit, pars = "AGRpred"), 2, mean)) %>% 
  filter(CensusYear == 2015) %>% 
  mutate(Vigor = agr - AGRpred) %>% 
  select(Genus, Species, idTree, Vigor, suitability) %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  ggplot(aes(suitability, Vigor, col = Species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_x_log10()
```

```{r traitSpLm}
data %>% 
  mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>% 
  mutate(AGRpred = apply(as.matrix(fit, pars = "AGRpred"), 2, mean)) %>% 
  filter(CensusYear == 2015) %>% 
  mutate(Vigor = agr - AGRpred) %>% 
  left_join(Individuals) %>% 
  select(Genus, Species, SpeciesLong, idTree, Vigor, SLA, LDMC, LT, LA, CC) %>% 
  filter(!is.na(SLA)) %>% 
  unique() %>% 
  group_by(SpeciesLong) %>% 
  do(lm = lm(Vigor ~ SLA + LDMC + LT + LA + CC, data = .)) %>% 
  broom::tidy(lm) %>% 
  filter(p.value < 0.05) %>% 
  kable(digits = 3)
```

## Traits in model

```{stan stanModelTraits, output.var="Model", echo=T, eval=F}
data {
  int<lower=1> N ; // Nb of observations
  vector<lower=0>[N] AGR ; // growth vector
  vector<lower=0>[N] dbh ; // dbh vector
  vector[N] SLA ; 
  vector[N] LDMC ;
  vector[N] LT ; 
  vector[N] LA ; 
  vector[N] CC ;
  int<lower=1> S ; // Nb of species
  int<lower=0> sp[N] ; // species vector
}
parameters {
  vector<lower=0.1>[S] g0 ; // species potential growth
  vector[S] gSLA ; 
  vector[S] gLDMC ; 
  vector[S] gLT ; 
  vector[S] gLA ; 
  vector[S] gCC ; 
  vector<lower=0,upper=200>[S] Dopt ; // optimal diameter
  vector<lower=0.1,upper=10>[S] Ks ; // kurtosis
  real<lower=0,upper=10> sigma ;
}
model {
  for(n in 1:N)
    log(AGR[n]+1) ~ normal((g0[sp[n]] + gSLA[sp[n]] + gLDMC[sp[n]] + gLT[sp[n]] + gLA[sp[n]] + gCC[sp[n]] )*exp(-0.5*pow(log(dbh[n]/Dopt[sp[n]])/Ks[sp[n]], 2)), sigma) ;
}
```

```{r mdataTraits}
paracou <-  src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>%
  filter(idTree %in% Individuals$idTree) %>%
  mutate(dbh = CircCorr/pi) %>% 
  group_by(idTree) %>% 
  arrange(idTree, CensusYear) %>% 
  collect() %>% 
  mutate(ddbh = dbh - lag(dbh), 
         dt = CensusYear - lag(CensusYear)) %>% 
  filter(ddbh > 0) %>% 
  mutate(agr = ddbh/dt) %>% 
  left_join(Individuals)
```

```{r fitTraits}
data <- paracou %>% 
  ungroup() %>% 
  select(agr, dbh, SLA, LDMC, LT, LA, CC, Species) %>% 
  mutate_at(vars("SLA", "LDMC", "LT", "LA", "CC"), scale) %>% 
  mutate_at(vars("SLA", "LDMC", "LT", "LA", "CC"), as.vector) %>% 
  na.omit() %>% 
  sample_n(1000)
# fit <- sampling(Model, chains = 2, save_warmup = F,
#                 data = list(N = nrow(data),
#                             AGR = data$agr,
#                             dbh = data$dbh,
#                             SLA = data$SLA,
#                             LDMC = data$LDMC,
#                             LT = data$LT,
#                             LA = data$LA,
#                             CC = data$CC,
#                             S = length(unique(data$Species)),
#                             sp = as.numeric(as.factor(data$Species))
#                 ))
# save(fit, file = "./functional_save/growthTraits.Rdata")
load("./functional_save/growthTraits.Rdata")
```

```{r}
bayesplot::mcmc_areas(as.array(fit, pars = c("g0", "gSLA", "gLDMC", "gLT", "gCC", "gLA")))
```



