---
title: "AXX: Morphology"
date: '`r Sys.Date()`'
output:
  bookdown::html_document2:
    number_sections: false
    toc: true
    toc_float: yes
  bookdown::word_document2: default
  github_document: default
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
    keep_tex: true
linestretch: 1.5
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

```{r setup, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(bayesplot)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 6,
  cache = T, cache.lazy = F)
path <- "~/Documents/BIOGECO/PhD/data/Paracou/"
```

```{r trees}
individuals <- googlesheets::gs_title("Measures_Eschweilera") %>% 
  googlesheets::gs_read("Individuals") %>% 
  dplyr::select(-X1) %>% 
  mutate(CodeParacou = paste0("P", Plot, "-", SubPlot, "-", TreeFieldNum)) 
trees <- individuals %>% 
  left_join(src_sqlite(file.path(path, "trees/Paracou.sqlite")) %>% 
              tbl("Paracou") %>% 
              mutate(CodeParacou = paste0("P", Plot, "-", SubPlot, "-", TreeFieldNum)) %>% 
              filter(CodeParacou %in% individuals$CodeParacou) %>% 
              filter(Plot %in% c(1, 6, 11, 13:15) & CensusYear == 2017 |
                       Plot == 16 & CensusYear == 2015) %>% 
              mutate(DBH = CircCorr*pi) %>% 
              mutate(SpeciesLong = paste(Genus, Species)) %>% 
              collect())
rm(individuals)
```

# Introduction

# Material and methods

# Results

## MDS

```{r}
data <- trees %>% 
  dplyr::select(SpeciesLong, TrunkForm, BarkColor, BarkRuggedness, BarkAspect, Lenticels, BladeForm,
                LeafConsistency, LeafBase, LeafMargin, HyperAcuminated, BentPrincipalN) %>% 
  na.omit()
X <- model.matrix(~ TrunkForm + BarkColor + BarkRuggedness + BarkAspect + Lenticels +
               BladeForm + LeafConsistency + LeafBase + LeafMargin + 
               HyperAcuminated + BentPrincipalN, data = data[-1])
pca <- princomp(X[,-1], cor = T)
library(factoextra)
g <- fviz_pca_ind(pca, label="none", habillage=data$SpeciesLong,
             addEllipses=TRUE, ellipse.level=0.95) + 
     theme_minimal()
g <- fviz_pca_var(pca, geom = c("point", "text"), alpha.var="contrib") +
   theme_minimal()
fviz_pca_biplot(pca, habillage=data$SpeciesLong,
             addEllipses=TRUE, ellipse.level=0.95)
```


## Morphology distribution by species

```{r MorphoSpeciesN}
g <- trees %>% 
  dplyr::select(SpeciesLong, TrunkForm, BarkColor, BarkRuggedness, BarkAspect, Lenticels, BladeForm, LeafConsistency,
         LeafSurface, LeafBase, LeafMargin, HyperAcuminated, BentPrincipalN) %>% 
  reshape2::melt(id.vars = "SpeciesLong") %>% 
  filter(!is.na(value)) %>% 
  group_by(variable) %>% 
  do(g = ggplot(data = ., aes(SpeciesLong, fill = value)) +
       geom_bar() +
       coord_flip() +
       scale_colour_brewer(palette = "Accent"))
ggsave(cowplot::plot_grid(plotlist = g$g, labels = g$variable),
       filename = "MorphoSpeciesN.png", path = "./distribution_save/", 
       width = 700, height = 500, units = "mm", dpi = 300)
```

```{r MorphoSpeciesPct}
g <- trees %>% 
  dplyr::select(SpeciesLong, TrunkForm, BarkColor, BarkRuggedness, BarkAspect, Lenticels, BladeForm, LeafConsistency,
         LeafSurface, LeafBase, LeafMargin, HyperAcuminated, BentPrincipalN) %>% 
  reshape2::melt(id.vars = "SpeciesLong") %>% 
  filter(!is.na(value)) %>% 
  group_by(variable, SpeciesLong, value) %>% 
  summarise(n = n()) %>% 
  mutate(percentage = n/sum(n)) %>%  
  group_by(variable) %>% 
  do(g = ggplot(data = ., aes(SpeciesLong, percentage, fill = value)) +
       geom_bar(stat = "identity") +
       coord_flip() +
       scale_colour_brewer(palette = "Accent"))
ggsave(cowplot::plot_grid(plotlist = g$g, labels = g$variable),
       filename = "MorphoSpeciesPct.png", path = "./distribution_save/", 
       width = 700, height = 500, units = "mm", dpi = 300)
```

# Discussion

# References
