---
title: Eschweilera distribution
author: Sylvain SCHMITT
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: journal
    toc: yes
    toc_depth: 5
    toc_float: yes
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

```{r set, message=FALSE, warning=FALSE, echo=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
path <- "~/Documents/BIOGECO/PhD/data/growth_Paracou/"
library(knitr)
library(readr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(raster)
library(leaflet)
library(htmltools)
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
    cache = T, cache.lazy = F)
```

```{r opening}
sp <- read_delim(file.path(path, 'Paracou_species.csv'), ',') %>%
  filter(Genre == "Eschweilera") %>%
  rename(idSp = idTaxon, Family = Famille, Genus = Genre, species = espece) %>%
  dplyr::select(-Family)
data <- rbind(read_delim(file.path(path, 'R_PreExploit_1984-85-86.csv'), ';'),
           read_delim(file.path(path, 'R_PostExploit_1987-88.csv'), ';'),
           read_delim(file.path(path, 'R_Paracou_1988-2016.csv'), ';')) %>%
  filter(code_vivant == 'VRAI') %>%
  filter(idTaxon %in% sp$idSp) %>%
  dplyr::select(n_parcelle, n_carre, n_arbre, idArbre, campagne, Xutm, Yutm, circonf, idTaxon) %>%
  mutate(circonf = circonf*10 / pi) %>%
  rename(plot = n_parcelle, square = n_carre, id = n_arbre, idPR = idArbre,
         census = campagne, X = Xutm, Y = Yutm, dbh = circonf, idSp = idTaxon) %>%
  filter(!is.na(dbh)) %>% 
  left_join(sp) %>% 
  unique()
rm(sp)
```

```{r table}
mnt <- raster('~/Documents/BIOGECO/PhD/data/SIG_Paracou/MNT_5m/MNT_ParacouAvril2009_5m.tif')
mnt <- projectRaster(mnt, crs = '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0')
data <- data %>% 
  filter(plot %in% c(1,6,11,13:16)) %>% 
  dplyr::select(-census, -dbh) %>% 
  unique()
# plot(mnt) ; points(data$X, data$Y)
XY <- data[c('X', 'Y')]
coordinates(XY) <- ~X + Y
data$elevation <- extract(mnt, XY)
write.table(data, "./Eschweilera.txt")
```

```{r map}
crs <- '+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0'
data_m <- data %>% 
  filter(plot == 16)
coordinates(data_m) <- ~X + Y
proj4string(data_m) <- '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0'
data_m <- spTransform(data_m, CRSobj = crs)
mnt <- raster('~/Documents/BIOGECO/PhD/data/SIG_Paracou/MNT_5m/MNT_ParacouAvril2009_5m.tif')
mnt <- projectRaster(mnt, crs = crs)
mnt <- crop(mnt, extent(data_m))
MNTpal <- colorNumeric(c("#f7f7f7", "#cccccc", "#969696", "#525252"),
                    values(mnt), na.color = "transparent")
SPpal <- colorFactor("viridis", as.factor(data_m$species), na.color = "transparent")
l <- leaflet() %>% 
  addRasterImage(mnt, colors = MNTpal, opacity = 0.8) %>%
  addCircles(data = data_m, radius = 0.1, color = ~SPpal(species),
             label = ~htmlEscape(species)) %>% 
  addLegend(pal = SPpal, values = levels(as.factor(data_m$species)), 
            title = 'Eschweilera')
```
```{r plot}
l
```

```{r plot2}
boxplot(extract(mnt, data_m) ~ data_m$species, las = 2, main = 'Eschweilera in plot 16')
```

```{r plot3}
contour(mnt)
plot(mnt, alpha = 0.5, add = T)
plot(data_m[which(data_m$species %in% c("congestiflora", "coriacea")),],
     col = as.factor(data_m[which(data_m$species %in% c("congestiflora", "coriacea")),]$species), pch = 16, add = T)
```


# References
