---
title: "Eschweilera"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

```{r setup, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(flexdashboard)
library(rgdal)
library(raster)
library(leaflet)
library(starmie)
library(rstan)
library(bayesplot)
library(abind)
library(tidyverse)
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
    cache = T, cache.lazy = F)
```

Paracou
==================

Headcount {data-width=200}
-------------------------------------

### Table 1.1 Alive Eschweilera headcounts in Paracou by species and treatment. B stand for Biodiviersity plots, C for control plots, and T1, T2, and T3 for treatment plots.

```{r Par_trees}
path <- "/home/sylvain//Documents/BIOGECO/PhD/data/Paracou/"
trees <- read.csv(file.path(path, 'trees/Eschweilera_Paracou.csv'),
                  dec=".", stringsAsFactors = F)
trees <- trees %>% 
  filter(CensusYear == 2015) %>% 
  filter(CodeAlive == 1) %>% 
  filter(CodeMeas == 0) %>% 
  filter(Plot != 18)
trees %>% 
  mutate(Treatment = c(rep(c('C', 'T1', 'T2', 'T3'), 3), rep('B', 4))[Plot]) %>% 
  mutate(Treatment_simp = ifelse(Treatment == "C", "Control", ifelse(Treatment == "B", "Biodiv", "Treatment"))) %>% 
  dplyr::select(Species, Treatment_simp) %>% 
  reshape2::dcast(Species ~ Treatment_simp) %>% 
  mutate(TotalBC = Biodiv + Control,
         Total = Biodiv + Control + Treatment) %>% 
  mutate(Clade = ifelse(Species %in% c("congestiflora", "simiorum"),
                        "Other", "Parvifolia")) %>% 
  mutate(SpeciesType = ifelse(Clade == "Other", "outgroup", NA)) %>%
  mutate(SpeciesType = ifelse(Species == "sagotiana", "sagotiana", SpeciesType)) %>%
  mutate(SpeciesType = ifelse(Species == "coriacea", "coriacea", SpeciesType)) %>%
  mutate(SpeciesType = ifelse(Species == "decolorans", "decolorans", SpeciesType)) %>%
  mutate(SpeciesType = ifelse(Species %in% c("pedicellata", "Indet.", "wachenheimii",
                                             "grandiflora_form2", "collina", 
                                             "grandiflora"), "other", SpeciesType)) %>%
  mutate(SpeciesType = ifelse(Species %in% c("micrantha", "parviflora", "squamata"), 
                              "rare", SpeciesType)) %>%
  select(Clade, SpeciesType, Species, Biodiv, Control, TotalBC, Treatment, Total) %>% 
  arrange(desc(Clade), desc(TotalBC)) %>% 
  kable()
```

Map {data-width=200}
-------------------------------------

### Figure 1.1 Eschweilera distribution in Paracou.

```{r Par_map}
# global crs definition
crs <- '+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0'
# limits
limits <- readOGR(file.path(path, 'limits'), "OverallPlots", verbose = F)
limits <- spTransform(limits, CRSobj = crs)
# topography
topo <- readOGR(file.path(path, 'topography', "ContourLinesPlots"), "ContourLinePlots", verbose = F)
topo <- spTransform(topo, CRSobj = crs)
# Trees to plot
treesXY <- trees
coordinates(treesXY) <- ~Xutm + Yutm
proj4string(treesXY) <- '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0'
treesXY <- spTransform(treesXY, CRSobj = crs)
treePal <- colorFactor(RColorBrewer::brewer.pal(length(unique(treesXY$Species)), "Accent"),
                        as.factor(treesXY$Species))
# Separate species
sagotiana <- subset(treesXY, Species == "sagotiana")
coriacea <- subset(treesXY, Species == "coriacea")
decolorans <- subset(treesXY, Species == "decolorans")
other <- subset(treesXY, Species  %in% c("pedicellata", "Indet.", "wachenheimii",
                                         "grandiflora_form2", "collina", "grandiflora"))
rare <- subset(treesXY, Species %in% c("micrantha", "parviflora", "squamata"))
# Plot
leaflet() %>%
  addPolylines(data = limits, group = 'Limits', color = 'black') %>%
  addPolylines(data = topo, group = 'Contour',
               color = 'grey') %>%
  addLayersControl(overlayGroups = c('Contour', 'Limits', 
                                     "sagotiana", "coriacea", "decolorans",
                                     "other", "rare"),
                   options = layersControlOptions(collapsed = F)) %>% 
  addCircles(data = sagotiana, radius = ~CircCorr/pi/10, 
             color = treePal("sagotiana"), label = paste("sagotiana"),
             group = "sagotiana") %>% 
  addCircles(data = coriacea, radius = ~CircCorr/pi/10, 
             color = treePal("coriacea"), label = paste("coriacea"),
             group = "coriacea") %>% 
  addCircles(data = decolorans, radius = ~CircCorr/pi/10, 
             color = treePal("decolorans"), label = paste("decolorans"),
             group = "decolorans") %>% 
    addCircles(data = other, radius = ~CircCorr/pi/10, 
             color = treePal(other$Species), label = ~Species,
             group = "other") %>% 
    addCircles(data = rare, radius = ~CircCorr/pi/10, 
             color = treePal(rare$Species), label = ~Species,
             group = "rare") %>% 
  addLegend(pal = treePal, values = levels(as.factor(treesXY$Species)),
            title = 'Eschweilera')
rm(list = ls())
```

Genotypes
==================

Text {data-width=400}
-------------------------------------

### Figure 2.1 Eschweilera population structure in Paracou.

```{r structure, fig.height=6, fig.width=12}
path <- '~/Documents/BIOGECO/PhD/data/Eschweilera/'
data <- list.files(path, recursive = T, pattern = "_f")
# data <- c(data[-1], data[1])
data <- lapply(data, function(d) loadStructure(file.path(path, d)))
data <- do.call('structList', data)
# plotMultiK(data, pop[c('ID', 'Pop')]) +
#   scale_fill_brewer(palette = "Paired")
g <- plotMultiK(data) +
  scale_fill_brewer(palette = "Paired")
g$data$Population <- c("apiculata", "chartaceifolia", "clparvifolia", "colilina",
          "coriacea", "decolorans", "grandiflora", "micrantha",
          "parviflora", "pedicellata", "sagotiana", "wachenheimii")[g$data$Population]
g +  
  scale_fill_brewer(palette = "Paired") +
  theme(strip.text.x = element_text(angle = 90))
```

Functional
==================

Text {data-width=400}
-------------------------------------

### Figure 2.1 Eschweilera functional traits variation per species.

```{r bridge}
path <- '~/Documents/BIOGECO/PhD/data/'
read.csv(file.path(path, "BRIDGE", "bridge.csv"),
                  dec=",", stringsAsFactors = F) %>% 
  filter(Genus == "Eschweilera") %>% 
  mutate(SLA = dry_mass/ind_surf_area) %>% 
  select(species, SLA, thickness, SPAD, toughness, bark_thick, leaf.N) %>% 
  reshape2::melt(id.vars = "species", variable.name = "Trait") %>% 
  ggplot(aes(species, value)) +
  geom_boxplot() +
  coord_flip() +
  facet_wrap(~Trait, scales = "free")
```

