```{r setupAdditive, include=FALSE}
#rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(rstan)
library(bayesplot)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 8, fig.width = 6,
  cache = T, cache.lazy = F)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
path <- "../../data/Paracou/"
```

```{r dataAdditive, eval=T}
# traitsSymphonia <- googlesheets::gs_title("Measures_Symphonia") %>%
#   googlesheets::gs_read("AllTraits") %>%
#   mutate(SLA = as.numeric(SLA), LDMC = as.numeric(LDMC)) %>%
#   mutate(Genus = "Symphonia") %>%
#   rename(Species = Morphotype) %>%
#   mutate(Species = ifelse(Species == "Indet.",
#                           c("globulifera", "sp.1", "sp.1")[fct_recode(Bark, "globulifera" = "G",
#                                      "sp.1" =  "S")], Species))
# traitsEschweilera <- googlesheets::gs_title("Measures_Eschweilera") %>%
#   googlesheets::gs_read("AllTraits") %>%
#   filter(!(Plot == 14 & SubPlot == 1 & TreeFieldNum == 760)) %>%  # outlier
#   filter(!(Species %in% c("congestiflora","simiorum","persistens")))
# bind_rows(traitsEschweilera, traitsSymphonia) %>%
#   mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>%
#   mutate(LMA=1/SLA) %>%
#   group_by(idTree) %>%
#   summarise_at(vars("LMA", "LDMC", "LT", "LA", "CC"), sd, na.rm = T) %>% 
#   ungroup() %>% 
#   summarise_at(vars("LMA", "LDMC", "LT", "LA", "CC"), mean, na.rm = T) # SD
# traits <- bind_rows(traitsEschweilera, traitsSymphonia) %>%
#   mutate(SpeciesLong = paste(substr(Genus, 1, 1), Species)) %>%
#   group_by(idTree, Plot, SubPlot, TreeFieldNum, Genus, Species,
#            SpeciesLong, Bark, Dawkins) %>%
#   summarise_at(vars("SLA", "LDMC", "LT", "LA", "CC",
#                     "brBT", "brBD", "brWD"), mean, na.rm = T) %>%
#   ungroup() %>%
#   mutate(invSLA=1/SLA) %>%
#   mutate(invLA=1/LA)
# load("./functional_save/env.Rdata")
# Individuals <-  left_join(traits, env, by = "idTree", suffix = c("", ".y"))
# rm(traitsEschweilera, traitsSymphonia, traits, paracou, env)
# save(Individuals, file = "./functional_save/Individuals.Rdata")
load("./functional_save/Individuals.Rdata")
sdDBH <- sd(Individuals$DBH)
Individuals <- Individuals %>% 
  rename(LMA = invSLA) %>% 
  group_by(Species) %>% 
  filter(n() > 20) %>% 
  ungroup() %>% 
  group_by(SpeciesLong) %>% 
  mutate(TWIs = mean(TWI, na.rm = T)) %>% 
  mutate(TWIis = TWI - TWIs) %>% 
  ungroup() %>% 
  mutate_at(vars("LMA", "LDMC", "LT", "invLA", "CC", "DBH", "TWIs", "TWIis"),
            funs(./sd(., na.rm = T))) %>% 
  group_by(Genus) %>% 
  mutate(SpeciesNum = as.numeric(as.factor(Species))) %>% 
  ungroup()
```

```{r mdataAdditive}
traits <- c("LMA", "LDMC", "LT", "invLA", "CC")
complexes <- c("Symphonia", "Eschweilera")
models <- sapply(complexes, function(complex) paste0(complex, "-", traits))
mdata <- lapply(models, function(model){
  trait <- strsplit(model, "-")[[1]][2]
  complex <- strsplit(model, "-")[[1]][1]
  data_ind <- Individuals[!is.na(unlist(Individuals[,trait])),] %>% 
    filter(Genus == complex)
  data_sp <- data_ind %>% 
    dplyr::select(SpeciesNum, TWIs) %>% 
    unique() %>% 
    arrange(SpeciesNum) 
  list(N = nrow(data_ind),
       S = nrow(data_sp),
       Trait = unlist(data_ind[trait]),
       DBH = data_ind$DBH,
       TWIs = data_sp$TWIs,
       TWIis = data_ind$TWIis,
       species = data_ind$SpeciesNum)
  })
names(mdata) <- models
```

# Additive Model

```{stan , output.var="Model", echo=T, eval=F, cache=F}
data {
  int<lower=1>  N ; // # of observations
  int<lower=1> S ; // # species
  vector[N] Trait ; // Trait
  vector[N] DBH ; // Diameter at Breast Height
  vector[S] TWIs ; // Topographic Wetness Index of species
  vector[N] TWIis ; // Topographic Wetness Index of individual knowing species TWI_i|s
  int<lower=1, upper=S> species[N] ; // species index
}
parameters {
  real alpha ; // genus intercept
  vector [S] alpha_s ; // species intercepts
  vector<lower=0> [S]  betaDBH ; // DBH half-load
  real betaTWI ; // TWI slope
  vector[S] gammaTWI ; // TWI slopee
  real<lower=0> sigma_a ; // Variance of the species intercepts
  real<lower=0> sigma_t ; // Variance
}
model {
  alpha ~ normal(0, 10^6) ; // Priors
  alpha_s ~ normal(alpha, sigma_a) ;
  betaDBH ~ normal(0,1) ;
  betaTWI ~ normal(0,1) ;
  gammaTWI ~ normal(0,1) ;
  sigma_a ~ normal(0, 1) ;
  sigma_t ~ normal(0, 1) ;
  Trait ~ normal(alpha_s[species] .* (DBH ./ (betaDBH[species] + DBH)) + betaTWI*TWIs[species] +  gammaTWI[species] .* TWIis, sigma_a) ; // Likelihood
}
```

```{r fits}
# fits <- lapply(mdata, function(x)
#   sampling(Model, chains = 2, data = x, save_warmup = F))
# names(fits) <- models
# save(fits, file = "./functional_save/Additive.Rdata")
load("./functional_save/Additive.Rdata")
```

```{r additiveModel}
load("./functional_save/InterIntraTWI.Rdata")
models <- list(Interaction = fits)
load("./functional_save/Additive.Rdata")
models$Additive <- fits
lapply(models, function(model)
  lapply(model, function(trait)
    broom::tidyMCMC(trait, pars = "lp__", droppars = NULL, rhat = T)
  ) %>% bind_rows(.id = "Model")) %>% 
  bind_rows(.id = "Form") %>% 
  separate(Model, c("Genus", "Trait"), "-") %>% 
  mutate(Trait = recode_factor(Trait, 
                               LMA = "$LMA$",
                               LDMC = "$LDMC$", 
                               LT = "$LT$", 
                               invLA = "$\\frac{1}{LA}$",
                               CC = "$CC$")) %>% 
  reshape2::dcast(Genus + Trait ~ Form, value.var = "estimate") %>% 
  mutate(Difference = Additive - Interaction) %>%
  kable(caption = "Log-likelihood for ontogenic model depending on model form (linear vs Michaelis-Menten).", digits = 3, format = "pandoc", escape = F) %>% 
  kable_styling(full_width = F)
```
