```{r setup_BD, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(tidyverse)
library(rstan)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
path <- "~/Documents/BIOGECO/PhD/data/Symphonia_Paracou/"
```


# Genetic database

## Symphonia

```{r symphonia, eval=F, echo=T}
extraction <- googlesheets::gs_title("Symcapture") %>% 
  googlesheets::gs_read("Extraction")
individuals <- googlesheets::gs_title("Measures_Symphonia") %>% 
  googlesheets::gs_read("Individuals")
traits <- googlesheets::gs_title("Measures_Symphonia") %>% 
  googlesheets::gs_read("AllTraits")
symphonia <- extraction %>% 
  left_join(individuals, by = c("Plot", "SubPlot", "TreeFieldNum")) %>% 
  left_join(traits, by = c("Plot", "SubPlot", "TreeFieldNum"))
paracou <- src_sqlite(file.path("../../../data/Paracou/", "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>%
  filter(idTree %in% symphonia$idTree) %>%
  filter(Genus %in% c("Lecythis", "Eschweilera") & 
           Plot %in% c(1, 6, 11, 13:15) & CensusYear == 2017 |
           Genus %in% c("Lecythis", "Eschweilera") & 
           Plot == 16 & CensusYear == 2015 |
           Genus == "Symphonia" & CensusYear == 2015) %>%
  mutate(DBH = CircCorr/pi) %>% 
  collect()
symphonia <- left_join(symphonia, paracou, by = c("Plot", "SubPlot", "TreeFieldNum", "idTree"))

symphonia %>% 
  rename(id = ID_genetic, id2 = idTree, Diametre = DBH, Circ.cm = CircCorr, Parcelle = Plot,
         Carre = SubPlot, Ind = TreeFieldNum, Latitude = Lat, Longitude = Lon, 
         DateRecolte = Date) %>% 
  mutate(Projet = "Symcapture") %>% 
  mutate(EspeceBotanique = paste("Symphonia", Morphotype)) %>% 
  mutate(NomCommun = "Manil marécage") %>% 
  mutate(Etiquette = paste(id, "/", paste0("P", Parcelle, "-", Carre, "-", Ind), "/", Species.x)) %>% 
  mutate(Stade = "Adulte") %>% 
  mutate(Sexe = "", Topographie = "", RmqTopo = "", Ecorce = "", 
         Contrefort = "", RmqId = "", GridCell = "", RmqSite = "", Placeau = "", 
         RmqInd = "", Angle_en_degrés_pr_à_. = "", Distance_pr_à_. = "", 
         Point_Kilometrique = "", altitude = "", RemarqueCoordonées = "",
         RemarqueEchantillon = "", RemarqueRecolte = "", RemarqueProjet = "") %>% 
  mutate(Site = "Paracou") %>% 
  mutate(Tissu = "Feuille") %>% 
  select(id, id2, Projet, EspeceBotanique, NomCommun, Etiquette, Stade,
         Diametre, Circ.cm, Sexe, Topographie, RmqTopo, Ecorce, Contrefort, RmqId,
         Site, GridCell, RmqSite, Parcelle, Placeau, Carre, Ind, RmqInd, Angle_en_degrés_pr_à_.,
         Distance_pr_à_., Point_Kilometrique, Latitude, Longitude, altitude, RemarqueCoordonées,
         RemarqueEchantillon, DateRecolte, RemarqueRecolte, RemarqueProjet, Tissu) %>% 
  unique() %>% 
  write_csv(file.path(path, "BDsymphonia.csv"))
```

## Eschweilera

```{r eschweilera, eval=F, echo=T}

individuals <- googlesheets::gs_title("Measures_Eschweilera") %>% 
  googlesheets::gs_read("Individuals")
traits <- googlesheets::gs_title("Measures_Eschweilera") %>% 
  googlesheets::gs_read("AllTraits")
eschweilera <- individuals %>% 
  left_join(traits, by = c("Plot", "SubPlot", "TreeFieldNum"))
paracou <- src_sqlite(file.path("../../../data/Paracou/", "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>%
  filter(idTree %in% eschweilera$idTree) %>%
  filter(Genus %in% c("Lecythis", "Eschweilera") & 
           Plot %in% c(1, 6, 11, 13:15) & CensusYear == 2017 |
           Genus %in% c("Lecythis", "Eschweilera") & 
           Plot == 16 & CensusYear == 2015 |
           Genus == "Symphonia" & CensusYear == 2015) %>%
  mutate(DBH = CircCorr/pi) %>% 
  collect()
eschweilera <- left_join(eschweilera, paracou, by = c("Plot", "SubPlot", "TreeFieldNum", "idTree"))

eschweilera %>% 
  rename(id = IdGenetic, id2 = idTree, Diametre = DBH, Circ.cm = CircCorr, Parcelle = Plot,
         Carre = SubPlot, Ind = TreeFieldNum, Latitude = Lat, Longitude = Lon, 
         DateRecolte = Date) %>% 
  mutate(Projet = "Parvicapture") %>% 
  mutate(EspeceBotanique = paste(Genus.x, Species.x)) %>% 
  mutate(NomCommun = "Maho") %>% 
  mutate(Etiquette = paste(id, "/", paste0("P", Parcelle, "-", Carre, "-", Ind), "/", EspeceBotanique)) %>% 
  mutate(Stade = "Adulte") %>% 
  mutate(Sexe = "", Topographie = "", RmqTopo = "", Ecorce = "", 
         Contrefort = "", RmqId = "", GridCell = "", RmqSite = "", Placeau = "", 
         RmqInd = "", Angle_en_degrés_pr_à_. = "", Distance_pr_à_. = "", 
         Point_Kilometrique = "", altitude = "", RemarqueCoordonées = "",
         RemarqueEchantillon = "", RemarqueRecolte = "", RemarqueProjet = "") %>% 
  mutate(Site = "Paracou") %>% 
  mutate(Tissu = "Feuille") %>% 
  select(id, id2, Projet, EspeceBotanique, NomCommun, Etiquette, Stade,
         Diametre, Circ.cm, Sexe, Topographie, RmqTopo, Ecorce, Contrefort, RmqId,
         Site, GridCell, RmqSite, Parcelle, Placeau, Carre, Ind, RmqInd, Angle_en_degrés_pr_à_.,
         Distance_pr_à_., Point_Kilometrique, Latitude, Longitude, altitude, RemarqueCoordonées,
         RemarqueEchantillon, DateRecolte, RemarqueRecolte, RemarqueProjet, Tissu) %>% 
  unique() %>% 
  write_csv(file.path(path, "BDeschweilera.csv"))
```

