```{r setuplit, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(tidyverse)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
# path <- "../../data/Paracou/"
```

# Literature

Here is a more extensive but raw review of the literature use throughout the analyses.

## Uncategorized

### @Schulze1972

**Stomatal responses to changes in humidity in plants growing in the desert**

> Stomata closing at low air humidity increase water content of desert apricot leaves with reduced conductance

### @Syvertsen1982a

**Diurnal changes in citrus leaf thickness, leaf water potential and leaf to air temperature difference**

> leaf water potential ($\psi$) and leaf thickness (LT) are highly correlated, reduced water potential results in thinner leaves

### @Maroco1997

**Stomatal responses to leaf-to-air vapour pressure deficit in Sahelian species**

> stomatal conductance ($g_s$) showed a negative response to increasing leaf-to-air vapour pressure deficit ($LAVPD$) in drought resistant species, revealing resistance to drought associated with stomatal closure

### @Fisher2006

**Evidence from Amazonian forests is consistent with isohydric control of leaf water potential**

> Amazonian forests are isohydric: when water is scarce, the stomata act to prevent leaf water potential from dropping. In the dry season, stomatal conductance ($g_s$) was 35 and 39% lower than in the wet season.

### @Nautiyal1994

**Plant responses to water stress: changes in growth, dry matter production, stomatal frequency and leaf anatomy**

> The leaf thickness decreased, but the thickness of palisade parenchyma increased with increasing water stress in *Eucalyptus* hybrid and *Casuarina*. Moreover, the thickness of leaf at both mid-rib and laminar portions was increased at the 4-d watering interval (low water stress compared to control).

### @Ennajeh2010

**Comparative impacts of water stress on the leaf anatomy of a drought-resistant and a drought-sensitive olive cultivar**

> When subjected to water stress, the leaves of drought-resistant olive trees increased the thickness of their upper palisade and spongy parenchyma by 17% and 22%, respectively, compared with only 9% and 13% in the case of drought-sensitive olive trees. A thicker palisade parenchyma could contain larger numbers of CO2 -fixation sites, while a thicker spongy parenchyma could result in easier diffusion of CO2 to these sites.

### @Guerfel2009

**Impacts of water stress on gas exchange, water relations, chlorophyll content and leaf structure in the two main Tunisian olive (Olea europaea L.) cultivars**

> Palissade and spongy parenchyma significantly increased with water stress in two olive cultivars.
