---
title: Litterature
author: Sylvain SCHMITT
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: journal
    toc: yes
    toc_depth: 5
    toc_float: yes
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
---

All the litterature theme are under the scope of the PhD and around the question of intraspecific variability.

# Biodiversity theory

## Individuals and the variation needed for high species diversity [@Clark2010]

The biodiversity paradox of many coexisting competitors in which the number of limiting resources seems low can be resolved at the individual level.

# Dynamic (forest)

## Tree growth is related to light interception and wood density in two mix dipterocarp forest of Malaysia [@King2005]

# Functional ecology

## The return of the variance: intraspecific variability in community ecology [@Violle2012a]

We need to develop tools and methodologies to connect functional trait- based approaches to community genetics.

# Genomic (environmental)

## Identification of amazonian trees with DNA barcode [@Gonzalez2009]

Species rich genera (and so maybe our studied complex) show little to no variation in the plastid markers.

## To what extent is altitudinal variation of functional traits driven by genetic adaptation in European oak and beech [@Bresson2011]

They observed a weak effect of genetic on phenotypic variation but still genetic effect of LMA for beech and Nmass for both oak and beech.

# References