---
title: Rapport pour le comité de suivi de thèse
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
output:
  bookdown::html_document2:
    theme: readable
    toc: true
    toc_float: yes
    number_sections: yes
  bookdown::pdf_document2:
    toc: false
    number_sections: yes
# rmarkdown::render("./documents/general/subject_new.Rmd", output_format = gdoc::gdoc())
link-citations: yes
bibliography: /home/sylvain/Documents/Bibliography/library.bib
---

<!-- https://ed-environnements.u-bordeaux.fr/var/ezdemo_site/storage/images/media/ecole-doctorale-sciences-et-environnements/sources/ed-304-footer-1280x280/70041-3-fre-FR/ED-304-Footer-1280x280_FooterLogoTiers.png -->

# Fiche d'identité de la thèse

Thèse réalisée par SCHMITT Sylvain, intitulée "Génomique écologique de l'exploitation de niche et la performance individuelle chez les arbres forestiers tropicaux", spécialisée en écologie et évolution et ayant démarrée au 1er Septembre 2017 au sein de l'UMR Biodiveristé Gènes et Communautés (BIOGECO) sous l'encadrement de Bruno Hérault et Myriam Heuertz dans le cadre d'un contrat doctoral financé par un bourse du ministère de l'enseignement supérieur et de la recherche (MESR).

# Problématique de la thèse

200 mots maximum.

# Résumé des travaux réalisés depuis le début de la thèse

500 mots maximum

Dans le cas d’un CST de 1 ère année ce sont effectivement des perspectives et un calendrier
prévisionnel des travaux à entreprendre qui sont attendus ici !

# Publication et participations à des colloques

Pour mémoire : la soutenance de la thèse est conditionnée à l'obtention d'au moins une
publication acceptée en premier auteur dans une revue indexée. Voir les critères de votre
section CNU ou CNRS ou contacter le responsable de thématique. Les listes des revues
HCERES pour les spécialités Anthropologie biologique, Préhistoire et Épistémologie histoire
des sciences sont en ligne sur le site web de l'ED : https://ed-environnements.u-bordeaux.fr
La mention « sans objet » est autorisée pour cette rubrique dans le cas d’un CST de 1 ère
année ! Il est toutefois possible d’indiquer les réalisations antérieures mais aussi les projets
et perspectives s’il y a lieu.

# Formations, stages, mobilités

Lister en préciser le lieu et la durée ce qui a été effectué depuis le début de la thèse ou ce
qui est à prévoir
Dans le cas d’un CST de 1 ère année il est indispensable d’indiquer les projets et perspectives
en la matière.

# Animation scientifique

Lister participations aux séminaires de l’équipe, du laboratoire, de la structure fédérative
de rattachement et de l’ED. Indiquer le titre des présentations réalisées s’il y a lieu.
Dans le cas d’un CST de 1 ère année il est nécessaire d’indiquer les projets et perspectives en
la matière.

# Activités d'enseignement

Lister les différentes heures effectuées. Préciser s’il s’agit de vacations ou d’une mission
complémentaire d’enseignement. Indiquer la composante d’enseignement concernée.
Dans le cas d’un CST de 1 ère année il est possible d’indiquer les projets et perspectives en la
matière, s’il y a lieu.

# Autres activités

Pour missions complémentaires d’expertise indiquer le nombre d’heures ou de jours,
l’organisme ou l’entreprise qui vous emploie. Pour les mandats électifs, préciser le nombre
de réunions par an.

Dans le cas d’un CST de 1 ère année il est nécessaire d’indiquer les projets et perspectives en
la matière, s’il y en a.

# Perspectives d'insertion professionnelle

Indiquer les perspectives de poursuite de carrière post-thèse auxquelles doit faire écho le
plan de formation durant la thèse. Indiquer les perspectives de candidature pour un post
doc en France ou à l’étranger, de candidature à la qualification aux fonctions de Maitres de
conférences, de chercheur CNRS, INRA, IRSTEA, INRAP, etc...

# Avis du doctorant

*Fréquence des contacts avec le directeur de thèse (en dehors des courriers électroniques) :*

Hebdomadaires à Mensuelles.

*Fréquence des contacts avec le codirecteur de thèse (le cas échéant) :*

Tous les jours à Bordeaux et Plusieurs fois par semaine à Kourou.

*Relations avec d'autres scientifiques que l'encadrement :*

* Locales : OUI (Géraldine Derroire, Éric Marcon, Sabrina Coste, Stéphane Traissac, Katarina Budde, Sébastien Levionnois...)
* Nationales : OUI (Fabian Fischer, Isabelle Maréchaux, Maxime Réjou-Méchain, Jérôme Chave, François Munoz)
* Internationales : OUI (Personnes rencontrées lors de la conférence européenne d'écologie tropicale)

*Avis général sur votre thèse en précisant les éventuelles difficultés rencontrées :*

Avis positif pas de difficultés à faire remarquer à part les éventuels problèmes inhérents à la distance (Bordeaux, Kourou, Yamoussoukro) facilement levés par les nouvelles technologies.

*Nom, prénom du signataire, date et signature*

# Avis des directeurs de thèse

L’avis synthétique (< 100 mots) doit évoquer l’organisation et l’autonomie du doctorant
dans son travail justifiant ainsi la progression du projet de recherche.

*Nom, prénom du(des) signataire(s), date et signature(s)*

# Avis du comité de suivi de thèse

L’avis synthétique (< 200 mots) doit aborder spécifiquement les orientations et la
progression du projet de recherche, le plan de formation du doctorant son insertion dans le
cadre professionnel (équipe, laboratoire, ED, établissement,...).

*Nom, prénom du signataire, date et signature*

# References
