---
title: 'The return of the individual: Functional trait variability in the Symphonia
  globulifera L.f. species complex in French Guiana'
author: Sylvain Schmitt, Géraldine Derroire, Éric Marcon
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
output:
  bookdown::pdf_document2:
    toc: no
    highlight: tango
  gdoc::gdoc: default
link-citations: yes
citecolor: red
urlcolor: blue
gdoc_id: 1XONqpCqbL3ak55W6RaivNQSnzyjRPPpNLgVsbY1HXF8
bibliography: /home/sylvain/Documents/Bibliography/library.bib
---
 
Characterizing biological diversity, or so-called biodiversity, and understanding its causes and consequences have been central to the development of ecology and evolution [@Messier2010]. Biodiversity can be divided in three fundamental categories: genetic, species and ecosystem diversity. Ecosystem diversity encompasses the range of terrestrial and aquatic environments found on earth classified into ecosystems. Ecosystems encompass both the biological community of interacting organisms and their physical environment. Moreover, ecosystems harbour groups of interacting organisms, defined as species, which together represent the species diversity component of biodiversity. Species have been defined as groups of organisms which are reproducing isolated from other such groups, protecting the integrity of their genotypes [@Mayr1996]. This reflects the biological species concept, based on reproductive isolation. But species concepts and definitions have been largely debated, especially concerning plants, and many species concepts can be defined (phylogenetic, biological, ecological, morphological or genetic, see @DeQueiroz2007). Individuals within species present variation in performance, phenotypes, and genes, which represents genetic diversity. 

Tropical rainforests are one constituent of the ecosystem diversity. The outstanding biodiversity of tropical rainforests has always fascinated ecologists [@connell_diversity_1978]. Different theories have been developed to explain the persistence of different species in sympatry. Niche theory explains species coexistence by niche differences limiting competitive exclusion [@lortie_rethinking_2004-1; @Weiher], while neutral theory shows that maintenance of high diversity is possible even for functionally equivalent species, because of stochastic life, death, reproduction and dispersal dynamics [@Hubbell2001]. But forest trees are competing for a small number of resources (water, light and several nutrients). Consequently depending on the level of competition between species, competition should lead to a low number of species. Some studies argue that intraspecific variability play a role in answering this paradox and should thus be responsible for the maintenance of high species diversity [@Chesson2000a; @Clark2010]: variations among individuals within species allow species to differ in the distribution of their responses to the environment, and thus to adapt to finely structured habitats. Consequently, we are interested in the effect of environment on the structure of intraspecific variability within population.

More and more scholars advocate for the use of functional ecology, and especially trait-based studies to unravel the processes of niche exploitation among and within species [@ackerly_trait-based_2007; @Escudero2016; @Levine2015; @Messier2010]. Functional traits are defined as morpho-physio-phenological traits impacting fitness indirectly through their effect on individual performance, which comprises growth, reproduction, and survival [@violle_let_2007]. Consequently, functional traits appear to be a perfect approach to study the effect of environment on the structure of intraspecific variability within population. Moreover, literature recently highlighted the lack of importance given to intraspecific variance in functional and community ecology, and advocated to integrate it in further studies taking into account trait variation across ecological scales [@Albert2011a; @Albert2015; @Messier2010; @Siefert2015a; @Violle2012]. Consequently we propose to study variations among individuals with a trait-based approach focusing on intraspecific trait variability (ITV).

The study will aim to answer the following questions:

* How does intraspecific trait variability structure across ecological scales (plot, morphotype, individual, leaves, see @Messier2010)?
* Do correlations of traits observed at the interspecific scale (within global spectrum/strategies) hold at the intraspecific scale [@messier_trait_2016]?
* What is the filtering effect of environment on intraspecific trait distribution? 

The study will focus on the abundant and widespread species *Symphonia globulifera* L.f (Clusiaceae). In French Guiana this species presents two morphotypes, *S. globulifera* and *S. sp.1*, living in sympatry but apparently in differentiated habitats, with *S. globulifera* preferentially growing in valley bottoms and *S. sp1* preferentially exploiting a variety of drier habitats. Specific leaf area (SLA), leaf dry matter content (LDMC), leaf area (LA), leaf thickness (LT), chlorophyll content, and branch wood density (brWD) will be the measured traits. Intraspecific relation to the environment could be explored with different environmental variables representing both water (water table depth and digital elevation model) and light (map of post-logging gaps and lidar campaign associated to anthropic and natural disturbances). The results will be important for the understanding of the functional structuration of the *Symphonia* complex with its environment, and more generally for insights on the role of intraspecific trait variability (ITV). 

Tissue materials (leaf and wood) will be collected before the internship on both morphotypes on 400 individuals monitored in the Paracou research station for over 20 years. Fresh measurements will be done directly in the field during the dry season before the beginning of the internship. The first task will be to perform leaf and wood dry measurements and image analysis on collected tissue materials to assess individual trait values using standard protocols [@perez-harguindeguy_new_2013]. Then the student will conduct detailed data analysis and modelling, possibly using bayesian inference, to study intraspecific trait variability structuration in the species complex in relation to the environment. We seek for a highly motivated master candidate who is eager to acquire experience in trait measurements, data analysis, functional and trait-based ecology.

If you are interested please e-mail sylvain.schmitt@agroparistech.fr and geraldine.derroire@cirad.fr with vitae and motivation letter.

## References