---
title: Ecological genomics of niche exploitation and individual performance in tropical
  forest trees
author: Sylvain Schmitt, Myriam Heuertz, Bruno Hérault, Niklas Tysklind
output:
  html_document:
    theme: journal
    toc: yes
    toc_depth: 5
    toc_float: yes
link-citations: yes
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
gdoc_id: 1bglxMPSWPHcIHBNVFhoZAm1bkivbAa0_p7i8EptMNhc
---
  
Characterizing biological diversity, or so-called biodiversity, and understanding its causes and consequences have been central to the development of ecology and evolution [@Messier2010].

_**What is biodiversity ?**_

Biodiversity, or biological diversity, can be divided in three fundamental categories: genetic, species and ecosystem diversity. Ecosystem diversity encompass the range of terrestrial and aquatic environements found on earth classified into ecosystems. Ecosystems encompass both the biological community of interacting organisms and their physical environment. Moreover, species diversity represents species in which are categorized the interacting organisms of the ecosystem. Species has been defined as group of organims which are reproducing isolated from each other, protecting the integrity of their genotypes [@Mayr1996]. But species concept and defintion has been largely debated, and many species concepts can be defined (phylogenetic, biological, ecological, morphological or genetic, see @DeQueiroz2007). However, indivduals presents variations in performance, phenotypes, and genes within species itself representing genetic diversity.

Tropical rainforests are one constituent of the ecosystem diversity. The outstanding biodiversity of tropical rainforests has always fascinated ecologists [@connell_diversity_1978].

_**How species diversity is maintained ?**_

Different theories have been developed to explain the persistence of different species in sympatry. Niche theory explains species coexistence depending on niche differences to limit competitive exclusion [@Weiher; @lortie_rethinking_2004-1], while neutral theory shows that maintenance of high diversity is possible even for functionally equivalent species, because of stochastic life, death, reproduction and dispersal dynamics [@Hubbell2001]. But forest trees are competiting for a small number of ressources (water, light and several nutrients). Consequently depending on the level of competition between species, competition should be responsible of a low number of species. Some studies argue that intraspecific variability is one mechanism answering this paradox and thus responsible for the maintenance of high species diversity [@Chesson2000a; @Clark2010]: variations among individuals within species allow species to differ in their distribution responses to the environement.

_**How are individuals organized into species ?**_

Majority of tropical forests biomass is represented by tree organsims. Tropical tree have great size, long life time, numerous seeds, large effective population size [@Brown2004], outcrossing mating system and and maintain a strong gene flow [@Hamrick1992; @Nybom2004]. Thus, neutral processes maintain tree diversity over time by connecting populations with high gene flow and large effective population, while adaptive processes lead to local adaptation on short times with an expected genetic differentiation at the loci underlying heritable traits [@Howe2003; @LeCorre2003]. Tropical tree genetic diversity [@Scotti2016] in combination to the environement results in phenotypic variability [@Albert2015] and ultimately to *in situ* performance differences [@Bec2015]. Consequently, tropical trees will adapt to their environement through phenotypic plasticity at short term and with genetic local adaptations at long term. Genetic local adaptation arise from new mutations, standing genetic variation and adaptive introgression [@Tigano2016]. During coalescent divergence of population [@Fujita2012], speciation will happen when a reproductive barrier appears. But local adptation and gene flow are continuous processes for population living in sympatry. Before true phylogenetic species can be defined, populations can differ in ecotypes due to local adaptation. At this stage of ecotypes, gene flow maintain adaptive polymporhisms inside the metapopulation [@Tigano2016]. Then, populations will face a reproductive barrier but will still largely share genetic variation due to the common ancestor and hibridization and can be qualified as species complex. At this stage of species complexe, gene flow increase standing genetic variation improving divergent selection in differential niche adaptation [@Tigano2016]. Finally true phylogenetic species  will exists where gene flow can still be responsible of adaptive introgression through hybrids in secondary contact, allowing species to share genetic evolutions.

_**What is the interpaly between genetic structure, local environment, phenotype and individual performance ?**_

_**And thus, does the interaction between genetic structure and local environment on individual performance participate to species maintenance ?**_

*Too fast. We have genetic structure (G), local environement (E), phenotype (P which can be diverse), and individual performance (W). We introduced GxE link, but not much GE effect on P and W. And also the link between P and W.*

## References