---
title: Ecological genomics of niche exploitation and individual performance in tropical forest trees
author: "Sylvain Schmitt, Myriam Heuertz, Bruno Hérault, Niklas Tysklind"
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
output:
  bookdown::html_document2:
    theme: readable
    toc: true
    toc_float: yes
    number_sections: yes
  bookdown::pdf_document2:
    toc: false
    number_sections: false
# rmarkdown::render("./documents/general/subject_new.Rmd", output_format = gdoc::gdoc())
link-citations: yes
bibliography: /home/sylvain/Documents/Bibliography/library.bib
---

# Introduction

## *Why studying biodiversity ?*

Characterizing biological diversity, or so-called biodiversity, and understanding its causes and consequences have been central to the development of ecology and evolution [@Messier2010]. Three simple questions arise from this statement: (1) what is biodiversity, (2) what is the cause of its existence, (3) and what are the consequences of its existence. Characterizing biodiversity is a *sine qua non* condition to embrace the two following questions. Once the biodiversity is characterized we can study its causes. But biodiversity is dynamic, so we can study its origin, maintenance, and future, or more generally how it evolves. Once biodiversity is characterized, we can also study consequences of its existence.

## *What is biodiviersity ?*

Biodiversity presents three nested levels, from individuals, over species, to ecosystems. Ecosystem diversity encompasses the range of terrestrial and aquatic environments found on Earth classified into ecosystems. Ecosystems hold the biological community of interacting organisms. Moreover, species diversity represents species in which are categorized the interacting organisms of the ecosystem. Species have been defined as groups of organisms which are reproducing isolated from other such groups, protecting the integrity of their genotypes [@Mayr1996]. This reflects the biological species concept based on reproductive isolation. But species concepts and definitions have been largely debated [@Mayden1997], especially concerning plants, and many species concepts can be defined (phylogenetic, biological, ecological, morphological or genetic, see @DeQueiroz2007). However, individuals present variation in performance, phenotypes, and genes within the species. To avoid any further confusions we will use intraspecific variability to qualify the biodiversity at the individual level, comprising both intraspecific genetic variability and intraspecific trait variability, also referred as intraspecific phenotypic variability.

## *What are the causes of biodiversity existence ?*

Earth presents a large amount of terrestrial and marine ecosystems. Among them, the outstanding biodiversity of coral reefs and tropical rainforests has always fascinated ecologists [@connell_diversity_1978]. At the species level, different theories have been developed to explain the persistence of biodiversity. Niche theory explains species coexistence depending on niche differences to limit competitive exclusion [@Weiher; @lortie_rethinking_2004-1], while neutral theory shows that maintenance of high diversity is possible even for functionally equivalent species, because of stochastic life, death, reproduction and dispersal dynamics [@Hubbell2001]. But numerous theories exists [@wright2002plant]. Still, theories often ignore intraspecific variability arising from individual diversity inside populations and communities. Yet, numerous studies have shown that intraspecific variation, besides being often ignored, is large and might play an important role at the population and community levels, as well as being one of the causes of biodiversity origin and maintenance.

We thus want to explore biodiversity causes in tropical rainforests, highlighting the role of intraspecific variability. We need to focus on species with most wide-ranging effect on the ecosystem [@Hughes2008] that we assumed to be abundant tree species. We first need to unravel drivers of intraspecific variability origin and maintenance, to finally explore its role within species and community.

# Origin and maintenance of intraspecific variability

Intraspecific variability is ultimately represented by phenotypic variation among communities and ecosystems. Phenotypic variation will be shaped by (i) genetic heritage, through genotypes, (ii) environment (both abiotic and biotic) with spatial and temporal heterogeneity, and (iii) random through stochastic factors [@Whitlock2007].

If we imagine a metapopulation $M$ with several populations $N_i$ with $i \in [1;n_p]$. Each population will contain several individuals $I_{i,j}$ with $j \in [1;n_{i,j}]$. Each individual $I_{i,j}$ will have a genome $G_{i,j}$ and will be located in a local environment $E_{i,j,t}$ in space (plants being static $(x,y)=(i,j$))  and time ($t$). The resulting phenotype of the individual $I_{i,j}$ is thus predicted to depend on both its genotype and environment $P_{i,j,t} \sim G_{i,j}*E_{i,j,t}+\epsilon_{i,j}$. Consequently at both population $N_i$ and metapopulation $M$ levels we will have phenotypic variation $V_{N_i}(P_{i,t})$ and $V_{M}(P_t)$, environmental heterogeneity  $V_{N_i}(E_{i,t})$ and $V_{M}(E_t)$, and genetic variability $V_{N_i}(G_{i,t})$ and $V_{M}(G_t)$.

## Genetic variability

Genetic variability is the genetic differences find within and among genomes of individuals within the population. Thus genetic variability is ultimately formed of polymorphisms. And a loci can contain one or several polymorphisms resulting in several alleles of the given loci.

### Origins

Genetic variability always arise from new mutations inside individuals genome $G_{i,j}$. If they directly promote individual fitness through its phenotype $P_{i,j,t}$ in its local environment $E_{i,j,t}$, they became a source of local adaptation. But they can also contribute beneficial alleles to the pool of standing genetic variation into the population $V_{N_i}(G_{i,t})$, conducting eventually for further local adaptation of other individuals from the population $I_{i,j'}$. Finally, both new mutations and standing genetic variation can be transferred and be beneficial in other populations $N_{i'}$ through adaptive introgression [@Tigano2016]. In addition, beneficial new mutations establishment and standing genetic variation fixation will depend on the strength of selection $s$ over gene flow $m$, besides gene flow will be responsible for adaptive introgressions. 

More especially, tree species have great size, long life time, numerous seeds, large effective population sizes [@Brown2004], outcrossing mating system and maintain a strong gene flow [@Hamrick1992b; @Nybom2004]. Thus, forest trees present a large degree of local adaptation [@Savolainen2013]. Consequently we can suspect tree populations to show high levels of genetic variability $V_{N_i}(G_{i,t})$. In fact, woody species have been shown to share more genetic variation within populations but less among populations than non woody species [@Hamrick1992b].

### Structure

Local adaptations are not random inside populations and results in a structured genetic variability within populations, among populations within metapopulations, and *in fine* among metapopulations within the community. Alleles of each loci will be more or less fixed between populations. Alleles more shared than expected under random expectation illustrates directional selection due to specific adaptations that will benefit one population. On the contrary, alleles less shared than expected under random expectation illustrates balanced selection of shared adaptation useful to the whole metapopulation.

### Link with environment

**To be move in environment section ?**

Local adaptations reflects the fact that local populations tend to have a higher fitness $\omega$ in their native environment than in other environment [@Lascoux2016]. Thus, local adaptations are the result of the interaction between genetic variability, local environment, and individuals performance. Moreover, if genetic variability is structured by local adaptations, thus genetic variability in the metapopulation will be related to the environmental heterogeneity of the metapopulation area.

Ecological genomics field aims to understand gene and genome functioning into their natural environment. For instance, @Torroba-Balmori2017 have related spatial genetic structure of a pantropical tree species to altitudinal gradients and microhabitat adaptation. 

**To be included:** We should not forget that $F_{st}$ outliers are only candidate loci of local adaptation, and should be further investigated to highlight their role. In addition, another way to detect local adaptation is to explore associations between SNPs frequencies and environmental variables [@Savolainen2013].

### Link with phenotype

**To be move in phenotype section ?**

Higher fitness $\omega$ of locally adapted individuals oper through adapted phenotypes. Phenotypic adptations selected in local adaptations, thus have a genetic basis and can be related to genetic variability within and among populations. 

Association genetics field aims to relate a given phenotype to its genetic origin. For instance, @Budde2014 have been able to relate serotiny presence, a fire-related molecule, to a set of genetic polymorphisms within a Mediterranean maritime pine population.

## Environmental heterogeneity

Ultimately individual trees interaction with environment go through resources acquisition and predation, with herbivory and pathogens. We will not explore tree interactions with their environment trough herbivory and pathogens, besides their huge impact on tree life history [but see @VanderPutten2001]. Individual trees harvest light, water and nutrients. Consequently, all environmental variables should be related to the use of those resources. 

Light interception can be directly measured on trees [@Canham1990] or approximated with spatial data such as Lidar [@Goulamoussene2017]. Water access can also be directly related to hydrologic and pedologic variables. For instance, water table depth, water logging, and hydromorphy will indicate direct access of individuals to water [@ferry2010higher]. But on the other hand, water is not only a needed resource for individual trees, but can also be a limiting factor for tree access to oxygen due to anoxy. Finally, nutrients can be directly surveyed in soil.

But we lack direct measurements of light, water and nutrient availability. On the other hand, numerous additional environmental variables will influence one or several resources availability for trees. Those environmental variables will affect individual trees at large and local scales and will be both biotic and abiotic. At large scale, geology and climate will drive individuals ecology through their global access to resources [@Guisan2005]. Because we wish to study intraspecific variability, we will focus on population level, consequently ignoring here large scale environmental drivers. At local scale with population level, biotic interactions, hydrology, pedology and topography will modulate individual trees access to ressources [e.g. @gunatilleke_specieshabitat_2006]. In addition, we might integrate anthropic factors if we consider disturbed forests [@Herault2010]. 

Biotic interactions affect all resources availabilty through facilitation and competition among living organisms. We will focus on other tree individuals as interacting organisms, besides the large amount of living organisms also interacting with trees. Biotic interactions affect (i) light interception through shading between individual trees, responsible for the asymetric competition [e.g. @Ruger2011], (ii) water availability with water table movements [including both competition and facilitation, e.g. @Pretzsch2014], (iii) and nutrients availability and access, with both nutrients competition and facilitation (e.g. nitrogen with *Fabaceae* family). Biotic interactions are uneasy to approach but can be approximated through neighbouring indices [@Canham]. In addition shading is partly included in direct light measurement with spatial measurement such as Lidar.

Hydrology, by definition, affect individuals access to water. Hydrology includes previously introduced direct measurement of water availability [water table depth and water logging , e.g. @ferry2010higher]. But hydrology also include indirect factors, such as river and other hydrographic networks. Finally, hydrology is intimately related to topography, and thus can be derived from topographic variables (see below). Pedology affect both individuals access to water and nutrients [@Levins1971]. Pedology variables can be direct measurement of nutrients or soil property, which will affect trees access to nutrient and water. Consequently, soil properties will be proxies for both water and nutrient access. Topography affect both individuals access to water and nutrients [e.g. @gunatilleke_specieshabitat_2006]. Topography first encompass the elevation of the studied area and lot of topographic variables and indices can be derived from elevation (slope, aspect, curvature, roughness, ruggedness, position, water flow direction, water accumulation). Derived information will be proxies for water and nutrient access depending on the indice.

In a nutshell, biotic interactions, hydrology, pedology and topography are locally driving tree resources access. They are all spatially structured and heterogeneous at the population level. But they do not vary similarly in time. Whereas hydrology, pedology and topography are relatively stable over an individual life time, biotic factors will vary at the individual timescale. In addition, tropical tree long life span incrrease individual probability to cope with catastropchic events [@Gutschick2003]. The temporal component of environment has been little exploited to our knowledge [but see @Kardol2006; @Soininen2010] and might play an important role in population genetic and phenotypic variability, by challenging local adaptation.

We hypothesize environmental heterogeneity to be a major factor of intraspecific variability. Hence, we believe that long lived woody species such as tropical trees present a certain degree of local adaptation to the fine heterogeneity of the environment. Consequently, we postulate that environmental variation should explain a higher proportion of phenotypic variation given the genotype than what is currently demonstrated and should be highlighted when studying genotype-phenotype interactions. Effectively, phenotypic plasticity of plants to abiotic environment and biotic interactions through neighbors can result in genetically identical individuals with very different phenotypes [@Callaway2003].

## Phenotypic variability

Phenotypic variability is the observed difference of traits between individuals of the same population. Several studies recently investigated phenotypic varibility through intraspecific trait variability, hereby refering to functional traits variability inside a population forming a species.

### Phenotypic variability is large

Intraspecific variability is a central topic in ecology and yet relatively unknown [@Hallgrimsson2005]. For instance with trees, individual variability regarding crown size and light interception is often relegated to an error term and ignored when interpreting ecological processes [@Vieilledent2010]. Nevertheless several authors advocates for a better understanding of intraspecific variability role in ecology [@Albert2010; @Albert2011a; @chave_neutral_2004; @Violle2012].

Despite being often ignored, literature has recently shown that intraspecific trait variation was relatively large. @Vieilledent2010 found individual variability to account for a large amount of the variation in tree allometric relations. Several authors particularly assessed intraspecific variation of functional traits called intraspecific trait variability. @Hulshof2010, partitioning variation of leaf traits in costa rican dry forest, found that intraspecific trait variability ranged from 36 to 83% of total variance whereas @Messier2010 found 12 to 30% of variation. At the community level, @Siefert2015a meta-analysis found on average an overall intraspecific trait variation (ITV) of 25% within communities and 32% among communities. Finally, @LeBagousse-Pinguet2014 assessed directly functional diversity within-species between 13.5 and 33.6% of total functional diversity.

Beyond intraspecific trait variation assessment, some studies investigated the role of intraspecific variability in community assembly. @Messier2010 found a lack of variance at the plot level interpreted as a trait-based environmental filtering and an important role of intraspecific trait variability in plant community assembly.  Intraspecific trait variability role was highlighted in community assembly shift due to environmental gradient in space or time. @Siefert2016 found intraspecific trait variability to drive shifts of mean height, leaf area and specific leaf area (SLA) following grassland fertilization. In addition, @Jung2010 found community mean specific leaf area (SLA) and height significantly varying along a flooding gradient, where intraspecific trait variability accounted for 44 and 32%, respectively of the trait-gradient relationships. Moreover, patterns of niche differentiation were revealed only when intraspecific trait variability was taken into account [@Jung2010]. Similarly, @Paine2011 found intraspecific trait data to be more sensitive and a better indicator of both niche differentiation and environmental filtering than interspecific trait data. Finally, complementary studies used simulations to investigate long term possible impact of intraspecific variability on communities. @Barabas2016 models highlighted a better resilience and stability of community assembly for heritable traits. @Vellend2006a models highlighted the role of intraspecific genetic variability through genetic diversity on both community species diversity and composition.

### Phenotypic variability is structured 

Local adaptations reflects the fact that local populations tend to have a higher fitness $\omega$ in their native environment than in other environment [@Lascoux2016]. Thus, locally adpated indivdual $I_{i,j}$ should present higher performance within their local environment $E_{i,j}$. Tree species performance have been related to their ability to survive, grow and reproduce resulting in their fitness $\omega$ [@Baraloto2005; @Poorter2006; @Roman-Danobeytia2012; @violle_let_2007]. 

Traits directly measuring performance can thus be used to explore local adaptations. Trees ability to grow can be measured through growth rates [@Baraloto2005; @Herault2010; @Osazuwa-Peters2017]. Trees ability to survive can be measured through mortality rates [@Aubry-Kientz2015; @Osazuwa-Peters2017]. Finally tree ability to reproduce can be assessed through cohort and allelles frequencies monitoring [@Unger2016]. Anyway, trade-off exists between performance component. Indeed, tropical trees has been shown to present a trade-off between growth and survival through the so-called growth-mortality trade-off [@Wright2010; @Aubry-Kientz2015; @Buchman1983]. Consequently, tropcail tree individual performance might be explored through few performance components relating them to other with known trade-offs.

Anyway, performance can also be indirectly measured. Functional traits have been specifically defined as traits which impact fitness indirectly through their effect on performance [@violle_let_2007]. Several studies have related tree performance to functional traits. @Herault2011 related tree growth to functional traits with stem economics [sensu @chave_towards_2009] and adult statures. @Aubry-Kientz2013 related tree mortality to functional traits with wood density, maximum height, laminar toughness, and stem and branch orientation, highlighting the trade-off between so called fast- and slow-growing species [@reich_world-wide_2014]. @Philipson2014 found that wood density was shaping the growth-mortality trade-off. On the opposite, @Poorter2006 found that leaf traits underlay growth-survival trade-off, with short-lived physiologically active leaves resulting in higher growth capacity but lower survival chance. Finally, less is known about functional drivers of reproduction performance with tropical trees, but @Niklas2003 were able to scale annual reproductive biomass with the two-thirds power of the standing shoot biomass.

Functional traits can be be numerous as biochemistry, physiology, anatomy, morphology, phenology. Previously introduced studies encompass a variety of theim: leaf biochemistry (e.g. foliar nitrogen and carbon), leaf and wood physiology (e.g. laminar thoughness), leaf and wood anatomy (leaf tissue density, wood density), tree morphology (e.g. maximum height, stem and branch orientation). Similarly to functional traits driving individual tree performance, functional traits are related theimselves. Functional strategies have been identified among tropical tree species such as conservative-acquisitive strategie trade-off and competitive-stress tolerance-resitance trade-off [@Baraloto2010; @chave_towards_2009; @wright_worldwide_2004; but see @reich_world-wide_2014]. And some traits have been directly explained by others [e.g. @kitajima_tissue-level_2010].

Ultimately functional traits arise from expressed genes through transcripts, with a more or less distant and simple linked depending on the type of trait (e.g. secondary metabolites might be more esasily related to genetic information with fewer genes than physiology traits). Moreover, trait trade-offs at he phenotypic level are expected to be related to individual loci trade-offs [@Savolainen2013]. Consequently, performane and functional traits allow to assess fitness, and thus help to explore genetic variability and environmental heterogeneity link due to local adaptation.

# Role of intraspecific variability

## Within species: from local adaptation to speciation ?

Tree species species have an increased genetic diversity within species [@Hamrick1992b], with high propension to hybridize increasing genetic diversity [@Petit2004]. In addition, large population of juvenile trees are under strong and variable selection [@Petit2006]. Thus, both increased tree intraspecific genetic diversity and juvenile strong and variable selection promotes local adapation among tree species. On the other hand, tree shows high gene flow within and among species, which could reduce divergence and speciation events [@Petit2006], while conserving local adaptation (McKay&Latta 2002 & others).

Consequently, trees high intraspecific genetic diversity despite a strong gene flow could promote rapid adaptive changes and increased local adaptation instead of speciation [@Petit2006]. Effectivelly, trees are predicted to have lower diversitfication rate, and thus a lower extinction rate with a morpholocgical stasis [@Petit2006]. Moreover, trees are capable of rapid adaptation to new and changing environmental conditions, with increased ability to colonize new habitats [@Petit2004a]. Still, if functional traits under selection by local environment within local adaptation are linked to traits involved in reproduction (genetic linkage or pleiotropy), speciation could become a by-product of local adaptation [@Lascoux2016].

As a conclusion, we hypothetize that tree evolutionary asset could be a great ability to local adaptation despite low speciation rates [@Petit2006], with local adaptation leading to speciation [@Lascoux2016].

* include Savolainen 2007
* include Kawecki 2004
* include Tigano 2016

## Within communtiy: motor of species coexistence ?

Several authors suggested hypothesis or have shown evidence of intraspecific variability [@Lichstein2007]. Following observations of community trait shifts due to intraspecific variability, @Jung2010 concluded that intraspecific trait variability promotes species coexistence, by facilitating species to pass through environmental filtering. In addition, studying limestone grassland functional diversity, @LeBagousse-Pinguet2014 were able to relate increasing interspecific trait overlap through increased intraspecific variability to a greater species coexistence. Effectively, @Clark2010 suggested that intraspecific variability allows species to differ in their distribution of the response to the environment and thus to pass environmental filtering, which would have occurred on species average. @Clark2010 found this hypothesis to be consistent with theories that predict a better species coexistence with competition being stronger within than between species. Similarly, @Chesson2000a suggested that intraspecific variability promotes species coexistence through stabilizing mechanisms "if negative intraspecific interactions tend to be greater than interspecific interactions". In addition, some authors suggested that intraspecific level should held evidences of mechanisms promoting species coexistence and thus biodiversity. @Laughlin2013 suggested to test limiting similarity hypothesis in the trait space incorporating intraspecific variability. Similarly, @Laughlin2012 suggested that intraspecific variability could answer paradox in theories of species coexistence.

Intraspecific variability might play a different role depending on the studied organism. More especially, long-lived species, as tropical trees, have high ontogenetic variation and phenotypic plasticity that might be resulting of a high intraspecific variability to face environmental hazards before they reach sexual maturity [@Borges2009; @Sultan1987]. Similarly, @Callaway2003 suggested that intraspecific variability, through phenotypic plasticity in response to neighbors, might promote community diversity and species coexistence, letting species adjust the composition of their population.

Finally, @Aarssen1983 suggested the "competitive combining ability" hypothesis which hypothesize species coexistence to held on the ability of each species to respond to spatial and variable selection imposed by neighbors. Thus, this species ability of answering selection promotes biodiversity through species coexistence and stabilize species composition among communities [@Vellend2006a].

# Conclusion

## Intraspecific variability and Biodiversity

Understanding characteristics, causes and consequences of biodiversity is a fundamental challenge to ecology and evolution. Biodiversity presents three nested levels going from individual to ecosystem, through the species concept. Yet, species concepts and definition have been largely debated. Moreover, most of biodiversity origin and maintenance theories stand on the species level. 

However, little is known about intraspecific variability, the individual level of biodiversity. Despite a large amount of evidences of important intraspecific variability, notably in ecologically important phenotypic traits, we still know little about the effects of this intraspecific variability on population dynamics, species interactions and ecosystem processes [@Hughes2008; @Mittelbach2015a]. On the other hand, several studies have shown or suggested an important role of intraspecific variability within species and within community promoting species coexistence and thus biodiversity origin and maintenance. 

Intraspecific variability results ultimately in phenotypic variation. Phenotypic variation will be shaped by the interaction between the genotype and the environment. That is why @Hughes2008 synthesis suggests that : "future studies of the ecological effects of genetic diversity should draw on classic approaches in evolutionary biology to identify genotype–phenotype relationships, which should advance our mechanistic understanding of genetic diversity effects."

## Future directions

Consequently, we want to further explore genoptype-environment interaction in shaping the phenotypic variability of species, and thus get insights into origins and roles of intraspecific variability in biodiversity origin and maintenance. We thus want to follow recommendation of @Turcotte2016 to further progress on both the empirical and theoretical front for a more general integration of plasticity, intraspecific variation, and rapid evolution into community ecology. Consequently we could help to build a theory of  community ecology starting with individuals, because interactions with the biotic and abiotic environment are ultimately based at the level of the individual [@Violle2012].

Genetic markers have already been shown to be useful to help understand the role of intraspecific variability in promoting biodiversity [@Whitlock2007]. Regarding methods, one useful important point unraveled by @Hughes2008 is methods from the species diversity are seldom applicable for the intraspecific variability. Nevertheless, @Whitlock2007 warned about the study of genotype-environment interactions in natural communities, such as tropical forest, due to the myriad ways in which genotypes can interact with their environment. In addition, since density-related processes seem to matter, it might be more pertinent to reason in terms of the response in the species per area, than in terms of individual-based response to selection. Finally, diachronic study of allele frequencies in seeds, seedlings, or saplings could give a view on how selection changes allele frequencies

To conclude, one way to simplify the system for a better understanding of processes is to start with the genotype being the only parameter static over an individual lifespan, contrarily to environment and phenotype. Consequently, we should first focus on the link between genotypes and environmental conditions through ecological genomics. Once the genotype-environment links unraveled, we can then move forward by exploring the role of the interaction in shaping phenotypic variability. A second asset can be to move progressively into the exploration of the role of genotype-environment interaction with phenotype by using progressively more and more complex traits, from simple (e.g. metabolites) to complex (e.g. growth).

[@Uriarte2010]

# References
