---
title: Ecological genomics of niche exploitation and individual performance in tropical
  forest trees
author: "Sylvain Schmitt, Myriam Heuertz, Bruno Hérault, Niklas Tysklind"
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
output:
  bookdown::html_document2:
    theme: readable
    toc: true
    toc_float: yes
    number_sections: yes
  bookdown::pdf_document2:
    toc: false
    number_sections: false
link-citations: yes
bibliography: /home/sylvain/Documents/Bibliography/library.bib
---

# Introduction

## *Why studying biodiversity ?*

Characterizing biological diversity, or so-called biodiversity, and understanding its causes and consequences have been central to the development of ecology and evolution [@Messier2010]. Three simple questions arise from this statement: (1) what is biodiversity, (2) what is the cause of its existence, (3) and what are the consequences of its existence. Characterizing biodiversity is a *sine qua non* condition to embrace the two following questions. Once the biodiversity is characterised we can study its causes. But biodiversity is dynamic, so we can study its origin, maintenance, and future, or more generally how it evolves. Once biodiversity is characterised, we can also study consequences of its existence. But this is a different question which will not be addressed here despite a huge litterature around the question [@Cardinale2012; @diaz_biodiversity_2006; @Liang2016; @Loreau2000; @Naeem2002; @Oliver2015; @Yachi1999].

## *What is biodiviersity ?*

Biodiversity can be divided in three fundamental categories: genetic, species and ecosystem diversity. Ecosystem diversity encompass the range of terrestrial and aquatic environements found on earth classified into ecosystems. Ecosystems encompass both the biological community of interacting organisms and their physical environment. Moreover, species diversity represents species in which are categorized the interacting organisms of the ecosystem. Species have been defined as groups of organims which are reproducing isolated from other such groups, protecting the integrity of their genotypes [@Mayr1996]. This reflects the biological species concept based on reproductive isolation. But species concepts and defintions have been largely debated [@Mayden1997], especially concerning plants, and many species concepts can be defined (phylogenetic, biological, ecological, morphological or genetic, see @DeQueiroz2007). However, indivduals presents variations in performance, phenotypes, and genes within species itself representing genetic diversity. To avoid any further confusions we will use intraspecific variability to qualificate this biodiversity level, comprising individual diversity, genetic diversity, intraspecific trait variability, and phenotypic variability.

## *What are the causes of biodiversity existence ?*

Earth present a lagre amount of terrestrial and marine ecosystems. Among theim, the outstanding biodiversity of coral reefs and tropical rainforests has always fascinated ecologists [@connell_diversity_1978], and so they represent interesting ecosystems to study. At the species level, different theories have been developed to explain the persistence of biodiversity. Niche theory explains species coexistence depending on niche differences to limit competitive exclusion [@Weiher; @lortie_rethinking_2004-1], while neutral theory shows that maintenance of high diversity is possible even for functionally equivalent species, because of stochastic life, death, reproduction and dispersal dynamics [@Hubbell2001]. But numerous theories exists [@wright2002plant]. Still, theories often ignore genetic biodiversity represented by intraspecific variability arising from indivdual diversity inside populations and communities. 

*Yet, numerous studies have shown that (i) intraspecific variation is high [@Messier2010; @Vieilledent2010], (ii) intraspecific variation play an important role at population and community level [@Albert2010; @Albert2011a; @Albert2015; @Messier2010], (iii) intraspecific variation can answer paradox in theories of species coexistence [@Laughlin2012], and (iv) intraspecific variation is needed to understand maintenance of species coexistence [@chave_neutral_2004; @Chesson2000a; @Clark2007; @Clark2010; @Violle2012] and therefore is one of the causes of biodiversity existence.* **To change to be less redundant with subsequent part.**

# Instraspecific variability importance

## Intraspecific variability is ignored

1. "a much needed demonstration of the pivotal role of intraspecific variability in ecology" [@chave_neutral_2004]
1. "Site and individual variability are typically ignored when considering crown size and light interception by trees, and residual variability is relegated to a residual error term, which is then ignored when studying ecological processes." [@Vieilledent2010]

## Intraspecific variation is large

1. @Vieilledent2010 found individual variability to account for a large amount of the variation in allometric relations
1. @Siefert2015a meta-analysis found on average an overall intraspecific trait variation (ITV) of 25% within communities and 32% among communities
1. @Hulshof2010, partitioning variation of leaf traits in costa rican dry forest, even found that ITV ranged from 36 to 83% of total variance 
1. whereas @Messier2010 found 12 to 30% of variation

## Intraspecific variation play a role at population and community level

1. "Community mean height, leaf area, and SLA increased in response to fertilization, and these shifts were driven almost entirely by intraspecific variation." [@Siefert2016]
1. "Trait shifts due to species turnover were generally weak and opposed intraspecific responses." [@Siefert2016]
1. "However, when intraspecific variation is heritable, allowing for the possibility of trait evolution, communities are much more resilient against environmental disturbance and exhibit far more predictable trait patterns." [@Barabas2016]

## Intraspecific variation play role in biodiversity origin and maintenance

**Take care to differentiate theories to evidences !**

1. "Further progress on both the empirical and theoretical front should culminate in a more general integration of plasticity, intraspecific variation, and rapid evolution into community ecology." [@Turcotte2016]
1. "Because interactions with the biotic and abiotic environment are ultimately based at the level of the individual, it makes sense to build a theory of community ecology starting with individuals." [@Violle2012]
1. "Our findings suggest that intraspecific trait variability promotes species coexistence, by enabling species to pass through both abiotic and biotic filters. " [cite Jung et al, 2010]
1. @Chesson2000a suggested two diversity maintenance mechanisms, the second being the stabilizing mechanisms: "if negative intraspecific interactions tend to be greater than intraspecific interactions"
1. "Variation among individuals within populations allows species to differ in their distributions of responses to the environment despite the fact that the populations to which they belong do not differ on average" [@Clark2010]
1. "Consistent with theory predicting that coexistence depends on competition being stronger within than between species" [@Clark2010]
1. "Just a variation among individuals is required to maintain species by natural selection, providing a means for adaptive evolution in response to many factors ... explaining why large number of intensely competitive species coexist" [@Clark2010]
1. "Traitspace can test for the effects of limiting similarity by explicitly incorporating intraspecific trait variation." [cite Laughlin et Laughlin, 2013]
1. "We may expect long-lived (i.e. woody) species to have high onto- genetic variation and express strong phenotypic plasticity to face environmental hazards over their lifetimes, leading to high ITV (Sultan 1987; Borges 2009)."
1. "Previous work suggests that ITV should be most important in species-poor
communities (e.g. MacArthur 1972; Antonovics 1992; Whi-tham et al. 2006), and niche theory predicts that the relative extent of ITV should decrease with increasing species richness (Violle et al. 2012). However, few studies have empirically examined this relationship in plant communities, and these have produced conflicting results (Hulshof et al. 2013; Le Bagousse-Pinguet et al. 2014)."

# Origin and role of intraspecific variability

## *What is intraspecific variability ? (Intro paragraph)*

1. Intraspecific variability is represented by phenotypic variation
1. Phenotypic variation will be shaped by (i) genetic heritage, through genotypes, (ii) environment with spatial and temporal heterogeneity, (iii) ontogeny over tree lifetime,  and (iv) random through stochastic factors

## Genotypic variability

1. Tree species have great size, long life time, numerous seeds,large effective population sizes [@Brown2004], outcrossing mating system and maintain a strong gene flow [@Hamrick1992; @Nybom2004]. 
1. Forest trees present a large degree of local adaptation [@Savolainen2013].
1. Genetic local adaptation arise from new mutations, standing genetic variation and adaptive introgression [@Tigano2016].
1. The genotype is a strong determinant of the phenotype in a given environment
1. Tropical tree genetic diversity [@Scotti2016] in combination to the environement results in phenotypic variability [@Albert2015] and ultimately to *in situ* performance differences [@Bec2015]
1. Selection is very strong at early life stages in forest trees: this is the moment where the largest changes in allele frequencies occur between generations. The responses of different individuals to selection pressures can be highly variable, across a population at a given time, but also (potentially) across time for a given individual, and response can be non-linear and counter-intuitive. For instance, stress can trigger lesser growth, but can also affect the investment into reproduction. Thus, the most stressed individuals might reproduce more. As a consequence, the least adapted individuals might disproportionally contribute to allele frequencies in regeneration before selection. This is an example of a “mechanism of diversity maintenance” in the system (but perhaps selection is so strong that the evolutionary influence of this is small). Given such processes, to understand adaptive processes in the population one should examine large sample sizes. And, since density-related processes seem to matter, it might be more pertinent to reason in terms of the response in the species per area, than in terms of individual-based response to selection. 
1. The hybridization / species complex component: the fact of belonging to a species complex increases the (genetic) diversity on which selection can act, thus increasing the chances for local adaptation to happen. Genomes are like mosaics of regions that are permeable to introgression (the regions leading to adaptation of the complex) and regions that are impermeable (those important for the species-specific adaptation)
* "The concept of dynamic species pools is underappreciated in community assembly." [@Mittelbach2015a]

## Environmental heterogeneity

1. Environmental variation should explain a higher proportion of phenotypic variation (generally speaking) given the genotype than what is currently demonstrated
1. Local environment is both abiotic (nutrients, water, light...) and biotic (competition, predation)
1. Environmental variation has a spatial (e.g., topography, soil variables) and a temporal (water availability, light environment, competitors) component
1. Environmental variation has a temporal component that has been little exploited

## Phenotypic variability

1. Phenotypes are composed of traits, from simple (metabolites) to complex (growth)
1. Basic functional traits resulting from transcript expression can be considered as primary traits. Interactions in individuals biochemistrial traits will then be the basis for individual physiological and morphological traits.
1. a static genotype is transcribed into RNA under the influence of environmental cues, leading to the production of a metabolic signal (the metabolite data: a spectrum of molecule signatures combine into metabolic profiles), which results in a phenotypic trait expression. This signal varies over time within a given individual, as a function of temporal variation in the environment.
1. Phenotypes can vary across the lifespan of individuals
1. Phenotypic plasticity can be reversible, also called phenotypic flexibility, or irreversible, also called development plasticity [@Turcotte2016].
1. Populations adapt to the environment at short term through phenotypic flexibility, over a lifetime through development plasticity, and among individuals and generation through local adaptations
1. Phenotypic plasiticy can play on morphology, physiology, phenology, and ontgeny [@Turcotte2016]
1. "For many traits, much of this variation (intraspecific variability) is caused by phenotypic plasticity." [@Turcotte2016]
1. Perfomance traits are growth, reproduction and survival. Fitness (**define fitness**) of the individual will then result in the balance of those three performance traits (**add example of opposite trade-offs**).
1. The problem of the winners: we observe the phenotypes after the worst period of selection. Some researchers use currently diachronic approaches, e.g., examining cohorts of individuals established under variable past environmental conditions (pre-industrial, post-industrial, recent). Perhaps examining allele frequencies in seeds / seedlings / saplings gives a view on how selection changes allele frequencies; one can also follow a given cohort for several years and monitor changes in allele frequencies “in real time”. For now there is no concrete intention to follow any of those approaches. 

# Conclusion

## Intraspecific variability and Biodiversity

**Summarize simply and shortly all previous paragraphs highlighting the take home messages (to be listed below)**

## Future directions

**Develop future directions that we wish to explore and also point to develop that we won't explore**

1. How to simplify the system to understand processes: The genotype is static over an individual’s lifespan, environment and phenotype vary. We discussed that focussing first on ecological genomics, i.e., on the connection of genotype and environment, should be very pertinent. This is to explore association of genotypes with well-characterized environmental conditions. Paracou has multiple dimensions of environmental data, including the time component that geneticists have so far largely ignored. The larger samples of genetic data to be acquired in Sylvain’s thesis will convey this task the necessary power
1. We are interested in dissecting the roles of genotypes, heterogeneous environments, ontogeny and stochastic factors in intraspecific variation
1.  In practical terms, we can start by examining genotype-habitat associations in each focal species, and then examine the same associations as a function of individual hybrid index (relative proportions of genes from parental species)
1. **Better understand origin of intraspecific variability to better understand its role in biodiviersity origin and maintenance**

## References