---
title: Supplementary Materials
author: Sylvain Schmitt, Niklas Tysklind, Géraldine Derroire, Myriam Heuertz, Bruno Herault
date: '`r Sys.Date()`'
output:
  bookdown::html_document2:
    number_sections: false
    toc: no
    toc_float: no
  bookdown::word_document2: default
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
linestretch: 1.5
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

\makeatletter
\renewcommand*{\thetable}{\arabic{table}}
\renewcommand*{\thefigure}{\arabic{figure}}
\let\c@table\c@figure
\makeatother 

\renewcommand{\figurename}{Supplementary Material S.}
\renewcommand{\tablename}{Supplementary Material S.}

```{r config, message=FALSE, warning=FALSE, include=FALSE}
rm(list = ls()); invisible(gc())
library(knitr)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(tidyverse)
library(ggfortify)
library(broom)
library(rstan)
library(bayesplot)
theme_set(bayesplot::theme_default())
opts_chunk$set(echo = F, message = F, warning = F, 
               fig.height = 8, fig.width = 8,
               cache = T, cache.lazy = F)
path <- "~/Documents/BIOGECO/PhD/data/Paracou/"
```

```{r trees}
d <- 20
trees <- src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>% 
  tbl("Paracou") %>% 
  filter(CensusYear == 2015) %>%
  filter(Species != "Indet.") %>% 
  mutate(DBH = CircCorr/pi) %>% 
  collect() %>% 
  filter(Xfield > d, Xfield < 250-d, Yfield > d, Yfield < 250-d)
load("../distribution_save/env.Rdata")
load("../distribution_save/Competition.Rdata")
Competition <- Competition %>% 
  left_join(dplyr::select(trees, idTree, Genus, Species)) %>% 
  group_by(idTree) %>% 
  mutate(dij = ifelse(dij <1, 1, dij)) %>% 
  summarise(NCIhetero = log(sum(DBHj^2*exp(-0.25*dij)*(1-as.numeric(Species == Speciesj)))+1),
            NCIcon = log(sum(DBHj^2*exp(-0.25*dij)*as.numeric(Species == Speciesj))+1))
complexes <- bind_rows(
  data.frame(Complex = "Chartacea", Genus = "Eschweilera",
             Species = c("simiorum", "congestiflora")),
  data.frame(Complex = "Parvifolia", Genus = "Eschweilera",
             Species = c("pedicellata", "coriacea", "decolorans", "sagotiana",
                         "wachenheimii", "grandiflora_form2")),
  data.frame(Complex = "Licania", Genus = "Licania",
             Species = c("alba", "membranacea", "canescens", "micrantha",
                         "ovalifolia", "sprucei", "densiflora",
                         "laxiflora", "parvifructa")),
  data.frame(Complex = "Iryanthera", Genus = "Iryanthera",
             Species = c("hostmannii", "sagotiana")),
  data.frame(Complex = "Talisia", Genus = "Talisia",
             Species = c("hexaphylla", "praealta", "simaboides")),
  data.frame(Complex = "Symphonia", Genus = "Symphonia",
             Species = c("globulifera", "sp.1")))
data <- trees %>% 
  left_join(env) %>% 
  left_join(complexes) %>% 
  left_join(Competition) %>% 
  filter(!is.na(Plot))
```

```{r correlations, fig.cap="Correlation of abiotic topographic variables and neighbor crowding indexes (NCI). All variables, relative elevation (RelEl), slope, curvature (Curv), aspect, topgraphic rudgeness index (TRI), and topgraphic wetness index (TWI) are derived from the digital evlevation model (DEM) obtaine through LiDAR campaign in 2015, the digital canopy model (DCM) has been obtained in the same campaign, and neighbor crowding index (NCI) of heterospecific (NCIh) or conspecific (NCIc) are derived from Paracou census campaign of 2015."}
data %>% 
  dplyr::select(DEM, RelativeElevation, Slope, Curvature, TRI, TWI,
                MNC, NCIhetero, NCIcon) %>% 
  rename(DCM = MNC, NCIh = NCIhetero, NCIc = NCIcon, 
         RelEl = RelativeElevation, Curv = Curvature) %>% 
  na.omit() %>% 
  cor(.) %>% 
  corrplot::corrplot.mixed()
```

```{r ModelsTable, render="pandoc"}
data.frame(
  Name = c("$B_0$", "$B_{\\alpha}$", "$B_{\\alpha, \\alpha_2}$", "$B_{\\alpha, \\beta}$",
           "$B_{\\alpha, \\beta}2$", "$B_{\\alpha, \\beta}3$"),
  Formula = c("$Presence \\sim \\mathcal{B}ernoulli(logit^{-1}(\\alpha_0))$",
              "$Presence \\sim \\mathcal{B}ernoulli(logit^{-1}(\\alpha_0+\\alpha*Environment))$",
              "$Presence \\sim \\mathcal{B}ernoulli(logit^{-1}(\\alpha_0+\\alpha*Environment+\\alpha_2*Environment^2))$",
              "$Presence \\sim \\mathcal{B}ernoulli(logit^{-1}(\\alpha_0+\\alpha*Environment+Environment^{\\beta}))$",
              "$Presence \\sim \\mathcal{B}ernoulli(logit^{-1}(\\alpha_0+\\alpha*(Environment+Environment^{\\beta})))$",
              "$Presence \\sim \\mathcal{B}ernoulli(logit^{-1}(\\alpha_0+Environment^{\\alpha}+Environment^{\\beta}))$")  
) %>% 
  kable(caption = "Model tested for species complex distribution.", format = "pandoc", escape = F) %>% 
  kable_styling(full_width = F)
```

```{r Predictions, fig.cap="Habitat suitability of single taxa model for every model form and three theoric species distribution cases. Three species distribution cases have been simulated: (i) the environmental variable has no effect, (ii) the niche optimum is a intermediate value of the environmental variable range, and (iii) the niche optimum is a limit of the environmental variable range."}
n <- 100
data <- list(
  no = data.frame(Environment = seq(0, 1, length.out = 100),
                  Presence = c(rep(0:1, 50))),
  intermediate = data.frame(Environment = seq(0, 1, length.out = n),
                            Presence = c(rep(0, 20), 
                                         rep(0:1,10),
                                         rep(1,20),
                                         rep(0:1,10),
                                         rep(0,20))),
  limit = data.frame(Environment = seq(0, 1, length.out = n), 
                     Presence = c(rep(0,30), rep(0:1,20), rep(1,30)))
)
mdata <- lapply(data, function(x) list(N = nrow(x),
                                       Presence = x$Presence,
                                       Environment = x$Environment))
load("../distribution_save/SingleModel.Rdata")
preds <- lapply(names(fits), function(model){
  lapply(as.list(names(data)), function(type)
    cbind(type = type, data[[type]],
          mu = apply(as.matrix(fits[[model]][[type]], pars = "theta"), 2, mean),
          t(apply(as.matrix(fits[[model]][[type]], pars = "theta"), 2, 
                  quantile, probs = c(0.05, 0.95))))) %>% 
    bind_rows() %>% 
    mutate(model = model)
}) %>% bind_rows()
preds %>% 
  mutate(model = recode_factor(model, B0 = "B[0]", Balpha = "B[alpha]",
                               Balpha2 = "B[alpha][.][alpha][2]",
                               Bbeta = "B[alpha][.][beta]",
                               Bbeta2 = "B[alpha][.][beta][2]",
                               Bbeta3 = "B[alpha][.][beta][3]")) %>% 
  ggplot(aes(x = Environment)) +
  geom_point(aes(y = Presence, col = as.factor(Presence))) +
  geom_point(aes(y = mu)) +
  geom_ribbon(aes(ymin = `5%`, ymax = `95%`), color = 'red', alpha = 0.2) +
  geom_line(aes(y = `5%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") +
  geom_line(aes(y = `95%`), col = "red", alpha = 1, size = 0.5, linetype = "dashed") +
  facet_grid(model ~ type, scales = "free", labeller = label_parsed) +
  ylab("Habitat suitabtility") + scale_color_discrete("Presence")
```