# Introduction plan

> [color=#e0f74c]
> This is the online editor of the plan of my PhD thesis introduction.
> You can comment in the viewer pan by selecting the text and using the comment menu.
> But you need to go into the edition mode to truly modify the text in markdown (no WYSIWYG-editing).
> Don't hesitate to contact me by Skype (or other) for any help.
> Anyway, if this solution of online editing works for you, it would be great for me.
> Indeed `HackMD` allows direct syncing of the document with my GitHub account, avoiding the double integration of your comments (contrarily to googledoc). 
> Moreover, writing this note, I'm discovering that the online editor is much more powerful than the markdown editor in Rstudio.
> Have a nice reviewing.
> [name=Sylvain SCHMITT]
> [time=Tue, Jun 30, 2020 4:52 PM]

1. Biodiversity within tropical forests of the Amazon Basin
    1. Tropical forests' outstanding biodiversity
    1. Threats that affect tropical forests
    1. Regional and local species richness in the Amazon Basin
    1. Many tree species but few tree genera in the Amazon Basin
    1. The paradoxical coexistence of closely-related species in sympatry
1. Biodiversity in closely-related species
    1. Species concepts and their limits
    1. Beyond species: species complexes and syngameons
    1. The neglected intraspecific variability
1. Species local coexistence in ecology
    1. Niche and neutral theory
    1. Neighbourhood crowding and competition
        * Janzen-Connell hypothesis
        * Neighbour density-dependence
        * Conspecific neighbour density-dependence
    1. Treefall and succession
        * Intermediate disturbance hypothesis
        * Successional niches
    1. Demography and fundamental tradeoffs
        * Growth, survival and reproduction
        * Fast-slow continuum, stature-recruitment trade-off, and reproductive strategy
    1. Functional traits: from fundamental tradeoffs to ecological niches
    1. *Transition (not a paragraph)* 
        * Ignore genotypic and phenotypic variation within species 
        * Ignore evolutionary forces driving past and future of biodiversity
1. Adaptive evolution: from individual genomes to tree species
    1. Bridging ecology and evolution: ecological genomics
        * ecologist often disregards individual genetic values
        * geneticist are often focused on the function of genes outside of their natural environment
        * genetic mechanisms that underlie the responses of organisms to their natural environments
        * eco-evolution litterature (Tutt, Dobzhansky, Pelletier, Bailey...)
    1. The genomic basis of adaptation
        1. Origin of genetic diversity
            * mutation
            * standing genetic variation
            * introgression
        1. Selection
            * hard sweep
            * soft sweep
            * polygenic adaptation 
            * adaptive introgression
        3. Detection of adaptations
            * mapping (GWAS)
            * selection scans
            * polygenic modelling
    3. Individual microgeographic adaptations
    4. Species adaptive radiations 
    5. Tree evolutionary peculiarities
1. Study context: long-term study site of Paracou in a coastal forest of the Guiana Shield
    1. The Amazon Basin and the Guiana Shield
        1. Geology, climate and pedology
            * poorer soils in the Guiana shield
        1. Forest dynamics
            * slower dynamics of the Guiana shield
        1. Past and current occupations
            * pre‐Columbian occupations
            * Coastal populations
            * Selective logging
            * Gold mining
            * Land use change
    1. The long-term study site of Paracou
        1. The experimental design
            * Diameter censuses
            * Logging
            * Biodiversity plots
            * Lidar
            * Hydrology and edaphic properties
            * Climate
        1. Local forest dynamics and species distribution
            * climate
            * water, soil, topography
            * gaps
            * growth-survival tradeoff
            * functional tradeoff and composition
            * reproduction and dispersion
        1. Local genetic variations and adaptations
            * spatial structure and gene dispersal
            * topography
            * gaps
            * logging
1. Study models: *Symphonia globulifera* and *Eschweilera* clade Parvifolia two species complexes of locally abundant trees
    1. *Symphonia*
        * Taxonomy
        * Morphology
        * Ecology
        * Biogeography
    1. *Eschweilera*
        * Taxonomy
        * Morphology
        * Ecology
        * Biogeography
1. Aims and general plan
    1. General
        * Q: Are individual genotypes and phenotypes adapted to microgeographic 
            topography and forest gap dynamics within and among species of species complexes?
        * H: Individual genetic and phenotypic variability within and among species 
            promotes local coexistence within species complexes through microgeographic adaptations to topography and forest gap dynamics.
        * include PhD scheme here
    1. Species distribution within and among species complexes
        1. Q: How are species distributed within and among species complexes along biotic and abiotic gradients in Paracou?
        1. H: Species complexes are widely spread across biotic and abiotic environments; whereas biotic and abiotic environments favour 
            niche differentiation among species within species complexes.
    1. Leaf functional traits within and among species
        1. Q: How does the abiotic environment influence individual leaf trait values among and within 
            closely-related species within species complexes?
        1. H: The abiotic environment shaped trait variation both among and within species in interaction with 
            tree diameter and access to light within species complexes.
    1. Individual and species adaptation to topography
        1. Q: Are tree species and individuals adapted to the fine-scale topographic gradient?
        1. H: Species are delineated along topography with fixed neutral and adaptive variants within species complexes.
    1. Individual and species adaptation to forest gap dynamics
        1. Q: Are tree species and individuals adapted to a trade-off between growth and competition in reponse to forest gap dynamics?
        1. H: Individual genotypes are adapted to a trade-off between growth and competition in response to forest gap dynamics.
    1. **Chapter 5?** Environment, adaptations, and coexistence within and among species
        1.  Q: How do tree species' and individual adaptations to microgeographic topography and forest gap 
            dynamics drive coexistence within and among species of the *Symphonia* species complex ?
        1. H: Genotypic adaptations within species of *Symphonia* decrease the risk of a stochastic local extinction 
            due to wide successional niches to respond to fine spatio-temporal dynamics of forest gaps; 
            while species adaptations stabilize local coexistence with differentiated species’s 
            topographic niches within the *Symphonia* species complexe.
