---
title: "A01 : Mortality test"
date: '`r Sys.Date()`'
author: Sylvain Schmitt
output:
  bookdown::html_document2:
    number_sections: no
    toc: true
    toc_float: yes
    theme: flatly
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
  bookdown::word_document2: default
linestretch: 1.5
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

```{r setup, include=FALSE}
#rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(kableExtra)
if(knitr:::is_html_output()) options(knitr.table.format = "html") 
if(knitr:::is_latex_output()) options(knitr.table.format = "latex") 
library(rstan)
library(bayesplot)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 8, fig.width = 8,
  cache = T, cache.lazy = F)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
path <- "../../../data/Paracou/"
```

```{r data}
paracou <-  src_sqlite(file.path(path, "trees", "Paracou.sqlite")) %>%
  tbl("Paracou") %>%
  filter(Genus == "Symphonia") %>% 
  mutate(dbh = CircCorr/pi) %>% 
  collect()
data <- paracou %>% 
  filter(!(Plot %in% 13:16)) %>% 
  group_by(idTree) %>% 
  mutate(Survivor = ifelse(1984 %in% CensusYear, 1, 0)) %>% 
  filter(Survivor == 0) %>% 
  mutate(dead = ifelse(2017 %in% CensusYear, 0, 1)) %>% 
  arrange(idTree, CensusYear) %>% 
  mutate(year = CensusYear - 1984) %>% 
  select(idTree, year, dead, dbh) %>% 
  mutate(recruit = first(year), death = last(year)) %>% 
  full_join(data.frame(idTree = rep(unique(.$idTree), each = 33),
                       year = rep(1:33,length(unique(.$idTree)))), .) %>% 
  group_by(idTree) %>% 
  mutate(dbh_est = ifelse(is.na(dbh), (lead(dbh) + lag(dbh))/2, dbh),
         dead_est = ifelse(is.na(dead), (lead(dead) + lag(dead))/2, dead)) %>% 
  ungroup() %>% 
  filter(!is.na(dbh_est))
ggplot(data, aes(year, dbh_est, col = as.factor(dead_est))) + 
  geom_point() + 
  geom_line(aes(group = idTree))
```

```{stan stanModel, output.var="Model", echo=T, eval=F}
functions{
  real log_F(
    int recruitment, // recruitment
    int y, // year
    int[] years, // censuses dates
    row_vector beta, // parameters
    vector[] x
  ){
    real ret ;
    real ret2 ;
    ret=0 ;
    for (j in years[recruitment]:(years[y-1]-1))
      ret-=exp(beta*x[j]) ;
    ret2=0 ;
    for (j in years[y-1]:(years[y]-1))
      ret2-=exp(beta*x[j]) ; 
    ret+=log_diff_exp(0, ret2) ;
    return ret ;
  }
  real cox_ll(
    int recruitment, // recruitment
    int death, // death
    int[] years, // census dates
    row_vector beta, // parameters
    vector[] x, // covariables per year
    int dead // censored index
  ){
    if(dead!=0){
      return log_F(recruitment, death, years, beta, x);
    }
    else{
    real likelihood ;
    likelihood = 1 ;
    for (y in (recruitment+1):death)
      likelihood -= exp(log_F(recruitment, y, years, beta, x)) ;
    return log(likelihood) ;
    }
  }
}

data {
  int<lower=1> Y ; // # of years
  int<lower=1> I ; // # of individuals
  int<lower=0> K ; // # number of covariables
  int<lower=1> L ; // total # of years
  int years[Y] ; // years
  vector[K] X[I,L] ; // covariables per individual and year, i.e. X[i,j, c] covariable c for individual i at census j, first column represents individual id
  int recruitment[I] ; // year of recruitment
  int death[I] ; // year of death or last census
  int dead[I] ; // dead during censuses
}
parameters{
  row_vector[K+1] beta ; // paramèters w beta[1] as intercept
}
model{
  for (i in 1:I)
    target+= cox_ll(recruitment[i], death[i], years, beta, X[i], dead[i]) ;
}
```

```{r fits}
data_ind <- select(data, idTree, recruit, death, dead_est) %>% 
  na.omit() %>% 
  unique()
fit <- sampling(Model, chains = 2, save_warmup = F,
                data = list(Y = length(unique(data$year)), # # of years
                            I = length(unique(data$idTree)), # # of individuals
                            K = 3, # # number of covariables
                            L = nrow(data), # total # of years
                            years = 1:length(unique(data$year)), # years
                            X = data %>% 
                              select(idTree, year, dbh_est) %>% 
                              mutate(idTree = as.numeric(as.factor(idTree))), # covariables per individual and year
                            recruitment = data_ind$recruit, # year of recruitment
                            death = data_ind$death, # year of death or last census
                            dead = data_ind$dead_est# dead during censuses
                ))
save(fit, file = "./mortality_save/death.Rdata")
load("./mortality_save/death.Rdata")

data %>% 
  mutate(intercept = 1) %>% 
  select(idTree, year, intercept, dbh_est) %>% 
  mutate(idTree = as.numeric(as.factor(idTree))) %>% 
  simplify2array(by(., ., as.matrix))
```

```{r mcmc, fig.cap="Markov chains trace plot after warmup for leaf thickness model."}
check_divergences(fit)
# mcmc_trace(as.array(fit), facet_args = list(labeller = label_parsed))
```


