#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
if (length(args)==0)
  stop("At least one argument must be supplied (simulation number).n", call.=FALSE)
chain <- as.numeric(args[1])
var <- as.character(args[2])
print(paste("Chain number is", chain))
print(paste("Variable is", var))
load("../parvicapture_save/dataEnv.Rdata")
library(rstan)
options(mc.cores = 1)
rstan_options(auto_write = T)
model <- stan_model("../parvicapture_models/AnimalLog2.stan")
fit <- sampling(model, chains = 1, data = mdata[[var]], save_warmup = F,
                     control = list(adapt_delta = 0.99, max_treedepth = 12))
save(fit, file = paste0("../parvicapture_save/EnvGeno2/", var, ".chain", chain, ".Rdata"))
