---
title: Gbs - BRIDGE - Paracou links
author: Sylvain SCHMITT
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: journal
    toc: yes
    toc_depth: 5
    toc_float: yes
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---


```{r set, message=FALSE, warning=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
path <- "~/Documents/BIOGECO/PhD/data/links/"
library(knitr)
library(readr)
library(dplyr)
library(tidyr)
opts_chunk$set(
  echo = T, message = F, warning = F, fig.height = 6, fig.width = 8,
    cache = T, cache.lazy = F)
```

```{r opening, message=FALSE, warning=FALSE}
t1 <- read_csv(file.path(path, 'Symphonia_ind_names.csv'))
t2 <- read_csv(file.path(path, 'Symphonia_ind_coords.csv'))
t3 <- read_csv(file.path(path, 'Symphonia_Paracou.csv'))
t <- t1 %>% 
  left_join(t2, by = c("ID" = "Ind_ID")) %>% 
  inner_join(t3, by = c("ID" = "Sample_ORI")) %>% 
  select(ID, pop_num, Species, CODE_SAMPLE) %>% 
  separate(CODE_SAMPLE, c("plot", "square", "id"), sep = "_")
rm(t1, t2, t3)
DT::datatable(t)
```

We obtained links for 75 individuals of Paracou.
