---
title: "A12: Competition"
date: '`r Sys.Date()`'
output:
  bookdown::html_document2:
    number_sections: false
    toc: true
    toc_float: yes
  bookdown::word_document2: default
  github_document: default
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
    keep_tex: true
linestretch: 1.5
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

```{r setup, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(parallel)
library(tidyverse)
library(ggfortify)
library(raster)
library(rstan)
library(bayesplot)
library(leaflet)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = T)
path <- "~/Documents/BIOGECO/PhD/data/Paracou/"
crs <- '+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0' # global crs definition
```

```{r individuals}
ind <- googlesheets::gs_title("Measures_Symphonia") %>% 
  googlesheets::gs_read("Individuals") %>% 
  bind_rows(googlesheets::gs_title("Measures_Eschweilera") %>% 
              googlesheets::gs_read("Individuals") %>% 
              mutate(Date = as.character(Date))) %>% 
  mutate(CodeParacou = paste0("P", Plot, "-", SubPlot, "-", TreeFieldNum))
```

```{r trees}
trees <- src_sqlite(file.path(path, "trees/Paracou.sqlite")) %>% 
  tbl("Paracou") %>% 
  mutate(CodeParacou = paste0("P", Plot, "-", SubPlot, "-", TreeFieldNum)) %>% 
  filter(CodeParacou %in% ind$CodeParacou) %>% 
  collect() %>% 
  mutate(DBH = CircCorr*pi) %>% 
  group_by(idTree) %>% 
  arrange(desc(CensusYear)) %>% 
  filter(CensusYear == first(CensusYear)) %>% 
  filter(CensusYear >= 2015) %>% 
  dplyr::select(idTree, CodeParacou, Plot, SubPlot, TreeFieldNum, 
         Xfield, Yfield, Xutm, Yutm, DBH, Family, Genus, Species)
```

```{r env}
limits <- shapefile(file.path(path, "limits", "OverallPlots.shp"))
limits <- subset(limits, TypePlot %in% c("DisturbancesPlots", "BiodiversityPlots"))
limits <- subset(limits, TypeSub != "Buffer25m")
limits <- spTransform(limits, CRSobj = crs)
coordinates(trees) <- ~ Xutm + Yutm
proj4string(trees) <- '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0'
trees <- spTransform(trees, CRSobj = crs)
```

# Introduction

The aim of this document is to plan the circonference measurement of trees outside of the plot for the competition submodel. Figure \@ref(fig:plot) shows sampled individuals distribution in Paracou with plots limit. We need to check how many individuals are close to the plot limits.

```{r plot, fig.cap="Sampled individuals distribution in Paracou."}
treesPal <- colorFactor(RColorBrewer::brewer.pal(length(unique(trees$Genus)), "Accent"),
                        as.factor(trees$Genus))
leaflet() %>%
  addPolylines(data = limits, group = 'Limits', color = 'black') %>%
  addLayersControl(overlayGroups = c('Limits', "Trees"),
                   options = layersControlOptions(collapsed = F)) %>%
  addCircles(data = trees, radius = ~DBH/50, color = treesPal(trees$Genus),
             label = paste(trees$Genus, trees$Species), group = "Trees") %>%
  addLegend(pal = treesPal, values = levels(as.factor(trees$Genus)),
            title = 'Trees')
```

# Distance

```{r dist, echo=T}
library(spatstat)
test <- trees@data %>% 
  filter(Plot != 16) %>% 
  rename(X = "Xfield", Y="Yfield") %>% 
  mutate(species = paste(Genus,Species, sep="_")) %>% 
  mutate(PointWeight = DBH) %>% 
  mutate(PointName = CodeParacou) %>%
  rename(PointType = species)
test <- dbmss::wmppp(as.data.frame(test), window = owin(c(0,250), c(0,250)),
                     unitname=c("metres", "metres"))
summary(unlist(lapply(lapply(mapply(function(x,y) disc(10, centre = c(x, y)), 
              x = test$x, y = test$y, SIMPLIFY = F), function(tree)
                intersect.owin(test$window, tree)), area)) < 314.0331)

test16 <- trees@data %>% 
  filter(Plot == 16) %>% 
  mutate(row = ceiling(SubPlot/5)) %>% 
  mutate(col = SubPlot - (row-1)*5) %>% 
  mutate(Xfield = Xfield + (5-row)*100) %>% 
  mutate(Yfield = Yfield + (col-1)*100) %>% 
  rename(X = "Xfield", Y="Yfield") %>% 
  mutate(species = paste(Genus,Species, sep="_")) %>% 
  mutate(PointWeight = DBH) %>% 
  mutate(PointName = CodeParacou) %>%
  rename(PointType = species)
test16 <- dbmss::wmppp(as.data.frame(test16), window = owin(c(0,500), c(0,500)),
                     unitname=c("metres", "metres"))
summary(unlist(lapply(lapply(mapply(function(x,y) disc(10, centre = c(x, y)), 
              x = test16$x, y = test16$y, SIMPLIFY = F), function(tree)
                intersect.owin(test16$window, tree)), area)) < 314.0331)
```

