---
title: "Sampling Ecuador"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

```{r setup, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(flexdashboard)
library(rgdal)
library(raster)
library(leaflet)
library(starmie)
library(rstan)
library(bayesplot)
library(abind)
library(ggrepel)
library(tidyverse)
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
    cache = T, cache.lazy = F)
```

# General

##

### Material

1. To command:
    + 1 BigShot (2 tubes + head)
    + 1 Launching bag
    + 1 BigShot elastic
    + 1 Launching rope    
    + 1-2 gloves pairs
    + water proof notepad
    
1. Stock BIOGECO:
    + 1 BigShot elastic
    + 1 Launching rope
    + 2 gloves pairs
    + 10 launching weights
    + Clip board
    + Ziplocks
    + Silicagel
    + Tea bags
    + Labels
    + Black bags
    + Plastic boxes
    + Field box
    + Falcons
1. To look for:
    + Helmets ?
    + Camera GPS (or camera + GPS)
    + Binoculars
    + Micrometer
    + SPAD
    + Scanner
    + Microbalance
    + Herbarium press
    + Pruiner
    + Scissors
    + Marker pens
    + Envelopes
1. To ask for in Ecuador:
    + SIG data for maps
    + Binoculars
    + Micrometer
    + SPAD
    + Scanner
    + Microbalance
    + Herbarium press

##

### Docs & Planning

* [Field protocol](https://docs.google.com/document/d/1Gt4s2h5LStjo98JuSdfgBfeKGqJa5NI7GGSGOpHECpg/edit?usp=sharing)
* [Fresh measurements protocol](https://docs.google.com/document/d/1GIhNYu_vLHJb27RZqore1D9MPNmxl3X75d86a5QZguA/edit?usp=sharing)
* [*Eschweilera* individuals](https://docs.google.com/spreadsheets/d/1RRyAJtaGR9FqIkE-OjPwLS8_y66vUTl-wBxtYWIQBuo/edit?usp=sharing)
* [*Eschweilera* vegetative characters](https://drive.google.com/open?id=1PDsblv48gaWy98wKOae5ovCRxWiRIhcAN_zfX4H1-kU)
* [Dawkins index](https://drive.google.com/open?id=14Tfwscrti2QlkMprHrD3hZjZQnX9YRKK)


1. before 12.07 Material command
1. 13.08-16.08 Tiputini sampling
1. 17.08-18.08 Yasuni sampling

### Maps

* ...

# Samples

