---
title: "Data exploration"
output: 
  html_document
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

```{r setup, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(flexdashboard)
library(googlesheets)
library(tidyverse)
library(stringdist)
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
    cache = F, cache.lazy = F)
```

```{r data load}
ind <- gs_title("Measures") %>% 
  gs_read("Individuals", range = cell_cols(2:13))
SPAD <- gs_title("Measures") %>% 
  gs_read("SPAD", range = cell_cols(2:9))
fresh <- gs_title("Measures") %>% 
  gs_read("Fresh", range = cell_cols(2:10))
# dry <- gs_title("Measures") %>% 
#   gs_read("Dry", range = cell_cols(2:7))
# leaves <- SPAD %>% 
#   left_join(fresh, by = c('Parcelle', 'Carré', 'Numéro', 'Feuille')) %>% 
#   left_join(dry, by = c('Parcelle', 'Carré', 'Numéro', 'Feuille'))
# rm(SPAD, fresh, dry)
```

# Data check

```{r individuals check, warning=TRUE}
IDs <- list(ind = with(ind, paste0('P', Parcelle, '-', Carré, '-', Numéro)),
            SPAD =  unique(with(SPAD, paste0('P', Parcelle, '-', Carré, '-', Numéro))),
            fresh = unique(with(fresh, paste0('P', Parcelle, '-', Carré, '-', Numéro))))

# Number of individuals
if(!all(unlist(lapply(IDs, length))[-1] == unlist(lapply(IDs, length))[1])){
  warning("Tables do not have the same number of individuals.\n")
  invalids <- names(which(unlist(lapply(IDs, length))[-1] != unlist(lapply(IDs, length))[1]))
  warning(invalids, " table(s) is(are) invalid(s).\n")
  for(invalid in invalids)
    diff <- length(IDs[[1]]) - length(IDs[[invalid]])
    if(diff > 0)
      warning(invalid, " table is missing ", abs(diff)," individual(s).\n")
    else
      warning(invalid, " table have ", abs(diff)," extra individual(s).\n")
}
  
# Individual names 
## SPAD table
diff <- max(length(sort(with(IDs, setdiff(ind,SPAD)))),
length(sort(with(IDs, setdiff(SPAD,ind)))))
if(diff > 0)
  warning("There are ", diff, " non matching individuals between individual and SPAD tables.\n")
ind_IDs_diff <- sort(with(IDs, setdiff(ind,SPAD)))
SPAD_IDs_diff <- sort(with(IDs, setdiff(SPAD,ind)))
for(id in ind_IDs_diff)
  warning(SPAD_IDs_diff[amatch(id, SPAD_IDs_diff, maxDist = Inf)],
          " is not a misspel of ", id, " ?\n")
## fresh table
diff <- max(length(sort(with(IDs, setdiff(ind,fresh)))),
length(sort(with(IDs, setdiff(fresh,ind)))))
if(diff > 0)
  warning("There are ", diff, " non matching individuals between individual and fresh tables.\n")
ind_IDs_diff <- sort(with(IDs, setdiff(ind,fresh)))
fresh_IDs_diff <- sort(with(IDs, setdiff(fresh,ind)))
for(id in ind_IDs_diff)
  warning(fresh_IDs_diff[amatch(id, fresh_IDs_diff, maxDist = Inf)],
          " is not a misspel of ", id, " ?\n")
```

```{r Ind values check, warning=TRUE}
## Date
Date <- ind %>% 
  select(Date) %>% 
  separate(Date, c("Day", "Month", "Year"))
if(all(Date$Year > 2017))
  warning("There is a wrong year in one date.\n")
if(!all(Date$Month %in% 10:12))
  warning("There is a wrong month in one date.\n")
if(!all(as.numeric(Date$Day) %in% 1:31))
  warning("There is a wrong month in one date.\n")
## Time
Time <- ind %>% 
  select(Time) %>% 
  separate(Time, c('Hour', 'Minute'), 'H')
if(!all(Time$Hour %in% 1:24))
  warning("Lines ", paste(which(!(Time$Hour %in% 1:24)), collapse = ', '),
          " have a wrong hour format.\n")
if(!all(as.numeric(Time$Minute) %in% 0:59))
  warning("Lines ", paste(which(!(as.numeric(Time$Minute) %in% 0:59)), collapse = ', '),
          " have a wrong minutes format.\n")
## Parcelle
if(!all(ind$Parcelle %in% 1:16))
  warning("Lines ", paste(which(!(ind$Parcelle %in% 1:16)), collapse = ', '),
          " have a wrong Parcelle number.\n")
## Carré
if(!all(ind$Carré %in% 1:25))
  warning("Lines ", paste(which(!(ind$Carré %in% 1:25)), collapse = ', '),
          " have a wrong Carré number.\n")
## Numéro
if(!all(ind$Numéro %in% 1:4000))
  warning("Lines ", paste(which(!(ind$Numéro %in% 1:4000)), collapse = ', '),
          " have a wrong Numéro number.\n")
## Dawkins
Dawkins <- c(NA, '1A', '1B', '2A', '2B', '2C', '3A',
             '3B', '3C', '4A', '4B', '4C', '5A', '5B')
if(!all(ind$Dawkins %in% Dawkins))
  warning("Lines ", paste(which(!(ind$Dawkins %in% Dawkins)), collapse = ', '),
          " have a wrong Dawkins index.\n")
## Position
Positions <- c(NA, 'TOP', 'MID-TOP', 'MID', 'MID-LOW', 'LOW',
             'CANOPY', 'REJET')
if(!all(ind$Position %in% Positions))
  warning("Lines ", paste(which(!(ind$Position %in% Positions)), collapse = ', '),
          " have a wrong Position code.\n")
## Pneumato
if(!all(ind$Pneumato %in% 0:1))
  warning("Lines ", paste(which(!(ind$Pneumato %in% 0:1)), collapse = ', '),
          " have a wrong Pneumato code.\n")
## Contrefort
if(!all(ind$Contrefort %in% 0:300))
  warning("Lines ", paste(which(!(ind$Contrefort %in% 0:300)), collapse = ', '),
          " have a wrong Contrefort value.\n")
## Échasse
if(!all(ind$Échasse %in% 0:1000))
  warning("Lines ", paste(which(!(ind$Échasse %in% 0:300)), collapse = ', '),
          " have a wrong Échasse value.\n")
## Écorce
Barks <- c('S', 'G', 'SG')
if(!all(ind$Écorce %in% Barks))
  warning("Lines ", paste(which(!(ind$Écorce %in% Barks)), collapse = ', '),
          " have a wrong Écorce code.\n")
## Bois
if(!all(ind$Bois %in% c(NA, 0:1)))
  warning("Lines ", paste(which(!(ind$Bois %in% c(NA, 0:1))), collapse = ', '),
          " have a wrong Bois code.\n")
```

```{r SPAD values check, warning=TRUE}
## Parcelle
if(!all(SPAD$Parcelle %in% 1:16))
  warning("Lines ", paste(which(!(SPAD$Parcelle %in% 1:16)), collapse = ', '),
          " have a wrong Parcelle number.\n")
## Carré
if(!all(SPAD$Carré %in% 1:25))
  warning("Lines ", paste(which(!(SPAD$Carré %in% 1:25)), collapse = ', '),
          " have a wrong Carré number.\n")
## Numéro
if(!all(SPAD$Numéro %in% 1:4000))
  warning("Lines ", paste(which(!(SPAD$Numéro %in% 1:4000)), collapse = ', '),
          " have a wrong Numéro number.\n")
## Feuille
if(!all(SPAD$Feuille %in% 1:4000))
  warning("Lines ", paste(which(!(SPAD$Feuille %in% 1:4000)), collapse = ', '),
          " have a wrong Feuille number.\n")
## SPAD
test <- function(x) ((x > 20 & x < 100) | is.na(x))
if(!all(apply(SPAD[5:7], 1, function(x) all(sapply(x, test)))))
  warning("Lines ", paste(which(!apply(SPAD[5:7], 1, function(x) all(sapply(x, test)))), 
                          collapse = ', '), " have a wrong SPAD value.\n")
```

```{r fresh values check, warning=TRUE}
## Parcelle
if(!all(fresh$Parcelle %in% 1:16))
  warning("Lines ", paste(which(!(fresh$Parcelle %in% 1:16)), collapse = ', '),
          " have a wrong Parcelle number.\n")
## Carré
if(!all(fresh$Carré %in% 1:25))
  warning("Lines ", paste(which(!(fresh$Carré %in% 1:25)), collapse = ', '),
          " have a wrong Carré number.\n")
## Numéro
if(!all(fresh$Numéro %in% 1:4000))
  warning("Lines ", paste(which(!(fresh$Numéro %in% 1:4000)), collapse = ', '),
          " have a wrong Numéro number.\n")
## Feuille
if(!all(fresh$Feuille %in% 1:4000))
  warning("Lines ", paste(which(!(fresh$Feuille %in% 1:4000)), collapse = ', '),
          " have a wrong Feuille number.\n")
## LT
test <- function(x) ((x > 50 & x < 600) | is.na(x))
if(!all(apply(fresh[5:7], 1, function(x) all(sapply(x, test)))))
  warning("Lines ", paste(which(!apply(fresh[5:7], 1, function(x) all(sapply(x, test)))), 
                          collapse = ', '), " have a wrong LT value.\n")
## Poids frais
test <- function(x) ((x > 0.1 & x < 5) | is.na(x))
if(!all(sapply(fresh$`Poids frais`, test)))
  warning("Lines ", paste(which(!(sapply(fresh$`Poids frais`, test))), 
                          collapse = ', '), " have a wrong Poids frais value.\n")
```