---
title: "Environment"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

```{r setup, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(flexdashboard)
library(raster)
library(leaflet)
library(greta)
library(tidyverse)
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
    cache = T, cache.lazy = F)
path <- "~/Documents/BIOGECO/PhD/data/Paracou"
```

# Wetness

## Model

```{r}
# global crs definition
crs <- '+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0'
# Elevation
dem <- raster(file.path(path, "topography", "MNT_ParacouAvril2009_5m.tif"))
# Wetness
wetness <- raster("./env/wetness.tiff")
projection(wetness) <- projection(dem)
wetness <- projectRaster(wetness, crs = crs)
# Limits
limits <- shapefile(file.path(path, "limits", "OverallPlots.shp"))
limits <- spTransform(limits, CRSobj = crs)
# hydrology
hydro <- shapefile(file.path(path, "hydrology", "WaterTable.shp"))
hydro <- spTransform(hydro, CRSobj = crs)
hydro_pal <- colorFactor('Greys', as.factor(hydro$TypeWatEN), reverse = T)
# Map
leaflet() %>%
  addPolylines(data = limits, group = 'Limits', color = 'black') %>%
  addRasterImage(wetness) %>% 
    addPolygons(data = hydro, group = 'WaterTable',
              opacity = 0, fillOpacity = 0.3, fill = T, 
              fillColor = ~hydro_pal(TypeWatEN), label = ~TypeWatEN)
```

## Validation

```{r}
wetness.hydro <- raster::extract(wetness, hydro)
hydro_r <- rasterize(hydro, wetness)
data.frame(wetness = values(wetness), 
           hydro =  as.factor(hydro$TypeWatEN[values(hydro_r)])) %>% 
  filter(!is.na(hydro)) %>% 
  ggplot(aes(hydro, wetness)) +
  geom_boxplot() +
  coord_flip()
```

# Distribution

```{r presence}
trees <- read.csv(file.path(path, 'trees/Symphonia_Paracou.csv'),
                  dec=",", stringsAsFactors = F) %>% 
  filter(campagne == 2015) %>% 
  filter(code_vivant == 1) %>% 
  filter(code_mesure == 0) %>% 
  filter(n_parcelle != 18)
treesXY <- trees
coordinates(treesXY) <- ~Xutm + Yutm
proj4string(treesXY) <- '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0'
treesXY <- spTransform(treesXY, CRSobj = crs)
trees$wetness <- raster::extract(wetness, treesXY)
trees <- trees %>% 
  filter(espece != "Indet.") %>% 
  mutate(presence_globulifera = as.numeric(espece == "globulifera")) %>% 
  mutate(presence_sp1 = as.numeric(espece == "sp.1"))
```

```{r m1_g}
presence_globulifera <- trees %>% 
  filter(espece == "globulifera") %>% 
  select(presence_globulifera) %>% 
  as_data()
wetness_m <- trees %>% 
  filter(espece == "globulifera") %>% 
  select(wetness) %>% 
  as_data()
alpha <- gamma(10^-2, 10^-2)
p <- ilogit(alpha*wetness_m)
distribution(presence_globulifera) <- bernoulli(p)
m1_g <- model(alpha)
fit1_g <- mcmc(m1_g)
pars1_g <- opt(m1_g)
```

```{r m1_s, eval = F}
presence_sp1 <- trees %>% 
  filter(espece == "sp.1") %>% 
  select(presence_globulifera) %>% 
  as_data()
wetness_m <- trees %>% 
  filter(espece == "sp.1") %>% 
  select(wetness) %>% 
  as_data()
alpha <- gamma(10^-2, 10^-2)
p <- ilogit(alpha*wetness_m)
distribution(presence_sp1) <- bernoulli(p)
m1_s <- model(alpha)
fit1_s <- mcmc(m1_s)
pars1_s <- opt(m1_s)
```

```{r m2_g}
presence_globulifera <- trees %>% 
  select(presence_globulifera) %>% 
  as_data()
wetness_m <- trees %>% 
  select(wetness) %>% 
  as_data()
alpha <- gamma(10^-2, 10^-2)
p <- ilogit(alpha*wetness_m)
distribution(presence_globulifera) <- bernoulli(p)
m2_g <- model(alpha)
fit2_g <- mcmc(m2_g)
pars2_g <- opt(m2_g)
```

```{r m2_s}
presence_sp1 <- trees %>% 
  select(presence_globulifera) %>% 
  as_data()
wetness_m <- trees %>% 
  select(wetness) %>% 
  as_data()
alpha <- gamma(10^-2, 10^-2)
p <- ilogit(alpha*wetness_m)
distribution(presence_sp1) <- bernoulli(p)
m2_s <- model(alpha)
fit2_s <- mcmc(m2_s)
pars2_s <- opt(m2_s)
```

```{r m3_g}
presence_globulifera <- trees %>% 
  select(presence_globulifera) %>% 
  as_data()
wetness_m <- trees %>% 
  select(wetness) %>% 
  as_data()
alpha <- gamma(10^-2, 10^-2)
mu <- gamma(10^-2, 10^-2)
p <- ilogit(alpha*wetness_m)
distribution(presence_globulifera) <- bernoulli(p)
m3_g <- model(mu, alpha)
fit3_g <- mcmc(m3_g)
pars3_g <- opt(m3_g)
```

```{r result}
trees %>%
  mutate(pred_m1_g = faraway::ilogit(wetness*pars1_g$par)) %>% 
  # mutate(pred_m1_s = faraway::ilogit(wetness*pars1_s$par)) %>% 
  mutate(pred_m2_g = faraway::ilogit(wetness*pars2_g$par)) %>% 
  mutate(pred_m2_s = faraway::ilogit(wetness*pars2_s$par)) %>% 
  select(wetness, presence_globulifera, 
         pred_m1_g, # pred_m1_s,
         pred_m2_g, pred_m2_s) %>% 
  ggplot(aes(wetness, presence_globulifera)) +
  geom_point(alpha = 0.3) +
  geom_line(aes(wetness, pred_m1_g), col = "blue") +
  # geom_line(aes(wetness, 1-pred_m1_s), col = "blue") +
  geom_line(aes(wetness, pred_m2_g), col = "red") +
  geom_line(aes(wetness, 1-pred_m2_s), col = "red")
```

## References