---
title: An eco-evolutionary perspective on local coexistence within Neotropical species complexes
output:
  bookdown::html_document2:
    number_sections: false
    toc: true
    toc_float: yes
  bookdown::word_document2: default
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
linestretch: 1.5
csl: /home/sylvain/Documents/Bibliography/csl/oikos.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
link-citations: yes
---

**Undefined title**

**We need to discuss authors order, order below not fixed yet.**

1. Sylvain Schmitt
    - Corresponding author
    - sylvain.m.schmitt@gmail.com
    - orcid.org/0000-0001-7759-7106
    - Univ. Bordeaux, INRAE, BIOGECO, 69 route d’Arcachon, 33610 Cestas France
1. Niklas Tysklind
    - Niklas.Tysklind@ecofog.gf
    - INRAE, UMR EcoFoG (Agroparistech, CNRS, Cirad, Université des Antilles, Université de la Guyane), Campus Agronomique, 97310 Kourou, French Guiana
1. Myriam Heuertz
    - heuertzm@gmail.com
    - orcid.org/0000-0002-6322-3645
    - Univ. Bordeaux, INRAE, BIOGECO, 69 route d’Arcachon, 33610 Cestas France
1. Bruno Hérault
    - bruno.herault@cirad.fr
    - orcid.org/0000-0002-6950-7286
    - CIRAD, UPR Forêts et Sociétés, Yamoussoukro, Côte d’Ivoire
    - Forêts et Sociétés, Univ Montpellier, CIRAD, Montpellier, France
    - Institut National Polytechnique Félix Houphouët-Boigny, INP-HB, Yamoussoukro, Côte d’Ivoire

\newpage 

# Abstract

*To be writen depending on manuscript review and aimed journal.*


## Keywords

xx ; xx ; xx

\newpage 

# Introduction

# Material and Methods

# Results

# Discussion

# Acknowledgements

We thank the University of Bordeaux for a PhD grant to Sylvain Schmitt. 
XXX.
This study was partially funded by an Investissement d’Avenir grant of the ANR: CEBA (ANR-10-LABEX-0025).

# Authors’ contributions

# Data accessibility

\newpage 

# References

<div id="refs"></div>

\newpage 

## Table captions

__Table \@ref(tab:headcount)__ 

## Figure captions

__Figure \@ref(fig:PCA)__ 
